objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Credit Status</label>
        <picklist>
            <picklistValues>
                <fullName>Good Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>SME_Customer</fullName>
        <active>true</active>
        <label>SME-Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Call_Report__c.object
<CustomObject>
    <description>This object tracks the Call Plan and Call Report</description>
    <fields>
        <fullName>CIS_ID__c</fullName>
        <label>CIS ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call Plans / Call Reports</relationshipLabel>
        <relationshipName>Call_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Plan_Date__c</fullName>
        <label>Plan Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Call Plan / Call Report</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Call Plan / Call Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Plans / Call Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is updated by DIH (HRIS): A = Active, I=Inactive</description>
        <label>Status Code</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Override_Controller_Test.cls
@isTest
private class Override_Controller_Test {

    public static String accountNameRM = 'rmCreatedAccountName';
	@testSetup static void setupAccount(){
		Mockup_Test mt = new Mockup_Test().setUpTest();

        System.runAs([SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameRM LIMIT 1][0]){
            mt.newAccount(accountNameRM,GlobalConstants.POOL,Mockup_Test.getRecordTypeAccountIdByName(GlobalConstants.SME_CUSTOMER));
        }

	}

	@isTest static void testCustomerOverride() {
		Customer_OverrideListView_Controller controller = new Customer_OverrideListView_Controller();
		controller.redirectToListView();
	}
	
	@isTest static void testContactOverride() {

		Account targetAccount = [SELECT Id FROM Account WHERE Name = :Override_Controller_Test.accountNameRM LIMIT 1];
		System.runAs([SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameRM LIMIT 1][0]){
			Call_Report__c callreportObj = new Call_Report__c(
				CIS_ID__c = targetAccount.Id,
				Status__c = GlobalConstants.PLAN,
				Plan_Date__c = System.Today()
			);
			insert callreportObj;

			ApexPages.StandardController stdController = new ApexPages.StandardController(callreportObj);
	        ApexPages.currentPage().getParameters().put('id',callreportObj.Id);
			Contact_Override_Controller controller = new Contact_Override_Controller(stdController);
		}
		
	}

}