objects/Account.object
<CustomObject>
    <fields>
        <fullName>CIS__c</fullName>
        <externalId>true</externalId>
        <label>CIS ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Credit Status</label>
        <picklist>
            <picklistValues>
                <fullName>Good Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>SME_Customer</fullName>
        <active>true</active>
        <label>SME-Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>SME_Prospect</fullName>
        <active>true</active>
        <label>SME-Prospect</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Lead_Campaign_Event_Code__c</fullName>
        <externalId>true</externalId>
        <label>Lead/Campaign/Event Code</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Campaign_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Campaign code setup using for Target List reward calculation</description>
    <fields>
        <fullName>NewBooking_Code__c</fullName>
        <label>NewBooking Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ThankYou_Code__c</fullName>
        <label>ThankYou Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Campaign Setting</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Total_BA_Prosaving__c</fullName>
        <label>Total BA Prosaving</label>
        <summarizedField>Opportunity_Product__c.BA_Prosaving__c</summarizedField>
        <summaryFilterItems>
            <field>Opportunity_Product__c.Status__c</field>
            <operation>equals</operation>
            <value>Setup</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity_Product__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_BA_Protection__c</fullName>
        <label>Total BA Protection</label>
        <summarizedField>Opportunity_Product__c.BA_Protection__c</summarizedField>
        <summaryFilterItems>
            <field>Opportunity_Product__c.Status__c</field>
            <operation>equals</operation>
            <value>Setup</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity_Product__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Front_End_Fee__c</fullName>
        <label>Total Front End Fee</label>
        <summarizedField>Opportunity_Product__c.Front_End_Fee__c</summarizedField>
        <summaryFilterItems>
            <field>Opportunity_Product__c.Status__c</field>
            <operation>equals</operation>
            <value>Setup</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity_Product__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Target_List__c.object
<CustomObject>
    <description>This object tracks the list of Targeted Lead and Campaign Member list</description>
    <fields>
        <fullName>CIS_ID_Prospect_Name__c</fullName>
        <label>CIS ID / Prospect Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Campaign_Members_Leads</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Campaign_Reward_Calc__c</fullName>
        <label>Campaign Reward Calc</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External_ID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Lead_Campaign__c</fullName>
        <label>Lead/Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Target Lists</relationshipLabel>
        <relationshipName>Campaign_Members_Leads</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Target Lists</relationshipLabel>
        <relationshipName>Target_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Done</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Interested This Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>App In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interested but not register</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stock Negotiation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Create Write Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Credit Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case is Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Credit Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial Loan Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Loan Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Target List</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TargetListTriggerHandler.cls
public without sharing class TargetListTriggerHandler extends TriggerHandler {
    private Set<Id> campIds;
    private Set<Id> accountIds;

    public override void allBefore() {
        campIds = new Set<Id>();
        accountIds = new Set<Id>();
    }

    public override void beforeInsert() {
        for(Target_List__c eachTarget : (List<Target_List__c>) Trigger.new) {
            if(eachTarget.Lead_Campaign__c != null)
                campIds.add(eachTarget.Lead_Campaign__c);
            if(eachTarget.CIS_ID_Prospect_Name__c != null)
                accountIds.add(eachTarget.CIS_ID_Prospect_Name__c);
        }
    }

    public override void beforeUpdate() {
        Target_List__c oldRecord;
        for(Target_List__c eachTarget : (List<Target_List__c>) Trigger.new) {
            oldRecord = (Target_List__c) Trigger.oldMap.get(eachTarget.Id);
            if(eachTarget.Lead_Campaign__c != oldRecord.Lead_Campaign__c || eachTarget.CIS_ID_Prospect_Name__c != oldRecord.CIS_ID_Prospect_Name__c) {
                if(eachTarget.Lead_Campaign__c != null)
                    campIds.add(eachTarget.Lead_Campaign__c);
                if(eachTarget.CIS_ID_Prospect_Name__c != null)
                    accountIds.add(eachTarget.CIS_ID_Prospect_Name__c);
            }
        }

        /*
         * Created by: chumphon.k@kbtg.tech
         * Created date: 22-Mar-2016
         * Description: CR-006 Clear NewBooking and re-calculate Thankyou campaign reward
        */
        List<Target_List__c> updateTargetList = new List<Target_List__c>();
        Target_List__c oldTarget = (Target_List__c)Trigger.old[0];
        Target_List__c newTarget = (Target_List__c)Trigger.new[0];
        if(oldTarget.Status__c != newTarget.Status__c && oldTarget.Status__c == 'Registered') {

            // *** Get campaign id of NewBooking and Thankyou
            Campaign_Setting__c campaignSetting = Campaign_Setting__c.getOrgDefaults();
            String campaignNewBookingCode = campaignSetting.NewBooking_Code__c;
            String campaignThankyouCode = campaignSetting.ThankYou_Code__c;
            Id campaignNewBookingID, campaignThankyouID;

            List<Campaign> campaignNewBooking = [SELECT Id FROM Campaign Where Lead_Campaign_Event_Code__c = :campaignNewBookingCode And IsActive = true];
            if(campaignNewBooking.Size() > 0){campaignNewBookingID = campaignNewBooking[0].Id;}
            List<Campaign> campaignThankyou = [SELECT Id FROM Campaign Where Lead_Campaign_Event_Code__c = :campaignThankyouCode And IsActive = true];
            if(campaignThankyou.Size() > 0){campaignThankyouID = campaignThankyou[0].Id;}
            
            if(campaignNewBookingID != null && String.isNotBlank(campaignNewBookingID) && campaignThankyouID != null && String.isNotBlank(campaignThankyouID)){
                if(oldTarget.Lead_Campaign__c == campaignNewBookingID) {
                    // Clear NewBooking and re-calculate Thankyou campaign reward
                    newTarget.Campaign_Reward_Calc__c = '-';
                    CampaignRewardCalculation calc = new CampaignRewardCalculation();
            
                    for(Target_List__c target : [Select ID, Status__c, Opportunity__r.Total_Front_End_Fee__c, Opportunity__r.Total_BA_Prosaving__c, Opportunity__r.Total_BA_Protection__c FROM Target_List__c WHERE Lead_Campaign__c = :campaignThankyouID and Opportunity__c = :newTarget.Opportunity__c]) {
                        target.Campaign_Reward_Calc__c = calc.CalculateThankyou(target.Opportunity__r.Total_Front_End_Fee__c, target.Opportunity__r.Total_BA_Prosaving__c, target.Opportunity__r.Total_BA_Protection__c);
                        updateTargetList.add(Target);
                    }
                    if(updateTargetList.size() > 0) update updateTargetList;
                }
            }
        }
    }

    public override void beforeFinally() {
        if(campIds != null && !campIds.isEmpty()) concatExternalId();
    }

    public void concatExternalId() {
        Id RECORDTYPE_SME_CUSTOMER = GlobalUtility.getRecordTypeAccountIdByName(GlobalConstants.SME_CUSTOMER);
        Id RECORDTYPE_SME_PROSPECT = GlobalUtility.getRecordTypeAccountIdByName(GlobalConstants.SME_PROSPECT);

        Map<Id, Account> accountMap = new Map<Id, Account>([SELECT Id, RecordTypeId, CIS__c FROM Account WHERE Id IN :accountIds]);
        Map<Id, Campaign> campaignMap = new Map<Id, Campaign>([SELECT Id, Lead_Campaign_Event_Code__c FROM Campaign WHERE Id IN :campIds]);

        for(Target_List__c eachTarget : (List<Target_List__c>) Trigger.new) {
            if(accountMap.containsKey(eachTarget.CIS_ID_Prospect_Name__c) && campaignMap.containsKey(eachTarget.Lead_Campaign__c)) {
                if(accountMap.get(eachTarget.CIS_ID_Prospect_Name__c).RecordTypeId == RECORDTYPE_SME_PROSPECT) {
                    eachTarget.External_ID__c = campaignMap.get(eachTarget.Lead_Campaign__c).Lead_Campaign_Event_Code__c + '' + accountMap.get(eachTarget.CIS_ID_Prospect_Name__c).Id;
                } else if(accountMap.get(eachTarget.CIS_ID_Prospect_Name__c).RecordTypeId == RECORDTYPE_SME_CUSTOMER) {
                    eachTarget.External_ID__c = campaignMap.get(eachTarget.Lead_Campaign__c).Lead_Campaign_Event_Code__c + '' + accountMap.get(eachTarget.CIS_ID_Prospect_Name__c).CIS__c;
                }
            }
        }
    }
}