objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>SME_Customer</fullName>
        <active>true</active>
        <label>SME-Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Associated_Customer__c.object
<CustomObject>
    <description>This object tracks the additional Customer and Contact for one call plan/call report</description>
    <fields>
        <fullName>Associated_Customer_Type__c</fullName>
        <label>Associated Customer Type</label>
        <picklist>
            <picklistValues>
                <fullName>Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Interested</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Borrower_Type__c</fullName>
        <label>Borrower Type</label>
        <picklist>
            <picklistValues>
                <fullName>Main Borrower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Co Borrower</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Call_Plan_Call_Report__c</fullName>
        <label>Call Plan / Call Report</label>
        <referenceTo>Call_Report__c</referenceTo>
        <relationshipLabel>Associated Customers</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CIS</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Associated Customers</relationshipLabel>
        <relationshipName>Customer_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Secondary_Call_Plan_Call_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Call Plan / Call Report</label>
        <referenceTo>Call_Report__c</referenceTo>
        <relationshipLabel>Associated Customers (Secondary Call Plan / Call Report)</relationshipLabel>
        <relationshipName>Associated_Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Associated Customer</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Customers</pluralLabel>
    <recordTypes>
        <fullName>Interested</fullName>
        <active>true</active>
        <description>Associate Customer is interested.</description>
        <label>Interested</label>
    </recordTypes>
    <recordTypes>
        <fullName>Not_Interested</fullName>
        <active>true</active>
        <description>Associate Customer is not interested.</description>
        <label>Not Interested</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Call_Report__c.object
<CustomObject>
    <description>This object tracks the Call Plan and Call Report</description>
    <fields>
        <fullName>CIS_ID__c</fullName>
        <label>CIS ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call Plans / Call Reports</relationshipLabel>
        <relationshipName>Call_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Offer_Interest__c</fullName>
        <label>Offer Interest</label>
        <picklist>
            <controllingField>Offer_Credit_Product__c</controllingField>
            <picklistValues>
                <fullName>Interest and can apply</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interest with condition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cannot apply</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer not interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interested with condition</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Call Plan / Call Report</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Call Plan / Call Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Plans / Call Reports</pluralLabel>
    <recordTypes>
        <fullName>CallReport</fullName>
        <active>true</active>
        <description>with Call Plan section</description>
        <label>Call Report</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AssociatedCustomerTrigger_Test.cls
@isTest
private class AssociatedCustomerTrigger_Test {
	public static final String accountNameTM = 'accountNameTM';
	public static final String accountNameRM = 'accountNameRM';

	@testSetup static void setupAccount(){
		Mockup_Test mt = new Mockup_Test().setUpTestAdmin().setUpTestWithExtension();

		System.runAs([SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameTM LIMIT 1][0]){
            mt.newAccount(accountNameTM,GlobalConstants.POOL,Mockup_Test.getRecordTypeAccountIdByName(GlobalConstants.SME_CUSTOMER));
        }
        System.runAs([SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameRM LIMIT 1][0]){
            mt.newAccount(accountNameRM,GlobalConstants.PORT,Mockup_Test.getRecordTypeAccountIdByName(GlobalConstants.SME_CUSTOMER));
        }
	}

	@isTest static void testInsertAssociatedCustomerRecordTypeInterestedAndBowwerTypeEqualCoBowwerThenInsertCallReportInterest() {
		Id recordType = GlobalUtility.getRecordTypeIdFromSObjectByDevName('Associated_Customer__c','Interested');
		Account tmAccount = [SELECT Id FROM Account WHERE Name = :accountNameTM];
		Account rmAccount = [SELECT Id FROM Account WHERE Name = :accountNameRM];

		Call_Report__c callReport = new Call_Report__c(
			CIS_ID__c = tmAccount.Id
		);
		insert callReport;

		Associated_Customer__c assoCus = new Associated_Customer__c(
			RecordTypeId = recordType,
			Associated_Customer_Type__c = 'Interested',
			Borrower_Type__c = 'Co Borrower',
			Call_Plan_Call_Report__c = callReport.Id,
			Customer__c = rmAccount.Id
		);

		Test.startTest();
			insert assoCus;
		Test.stopTest();

		Associated_Customer__c assoCusResult = [SELECT Id,Secondary_Call_Plan_Call_Report__c FROM Associated_Customer__c WHERE Id = :assoCus.Id];
		Call_Report__c callReportResult = [SELECT Id,Offer_Interest__c FROM Call_Report__c WHERE CIS_ID__c = :rmAccount.Id];

		System.assertNotEquals(null,callReportResult.Id);
		System.assertEquals('Interest and can apply',callReportResult.Offer_Interest__c);
		
		System.assertEquals(assoCusResult.Secondary_Call_Plan_Call_Report__c,callReportResult.Id);
	}
	
	@isTest static void testInsertAssociatedCustomerRecordTypeNotInterestedAndBowwerTypeEqualCoBowwerThenInsertCallReportNotInterest() {
		Id recordType = GlobalUtility.getRecordTypeIdFromSObjectByDevName('Associated_Customer__c','Not_Interested');
		Account tmAccount = [SELECT Id FROM Account WHERE Name = :accountNameTM];
		Account rmAccount = [SELECT Id FROM Account WHERE Name = :accountNameRM];

		Call_Report__c callReport = new Call_Report__c(
			CIS_ID__c = tmAccount.Id
		);
		insert callReport;

		Associated_Customer__c assoCus = new Associated_Customer__c(
			RecordTypeId = recordType,
			Associated_Customer_Type__c = 'Not Interest',
			Borrower_Type__c = 'Co Borrower',
			Call_Plan_Call_Report__c = callReport.Id,
			Customer__c = rmAccount.Id
		);

		Test.startTest();
			insert assoCus;
		Test.stopTest();

		Associated_Customer__c assoCusResult = [SELECT Id,Secondary_Call_Plan_Call_Report__c FROM Associated_Customer__c WHERE Id = :assoCus.Id];
		Call_Report__c callReportResult = [SELECT Id,Offer_Interest__c FROM Call_Report__c WHERE CIS_ID__c = :rmAccount.Id];

		System.assertNotEquals(null,callReportResult.Id);
		System.assertEquals('Not interest',callReportResult.Offer_Interest__c);
		
		System.assertEquals(assoCusResult.Secondary_Call_Plan_Call_Report__c,callReportResult.Id);
	}
	
}