objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>SME_Customer</fullName>
        <active>true</active>
        <label>SME-Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Call_Report__c.object
<CustomObject>
    <description>This object tracks the Call Plan and Call Report</description>
    <fields>
        <fullName>CIS_ID__c</fullName>
        <label>CIS ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call Plans / Call Reports</relationshipLabel>
        <relationshipName>Call_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Plan_Amount__c</fullName>
        <label>Plan Amount</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Call Plan / Call Report</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Call Plan / Call Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Plans / Call Reports</pluralLabel>
    <recordTypes>
        <fullName>CallReport</fullName>
        <active>true</active>
        <description>with Call Plan section</description>
        <label>Call Report</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Call_Report_Lead__c.object
<CustomObject>
    <description>This object tracks the Lead associated to Call Plan/Call Report</description>
    <fields>
        <fullName>Call_Plan_Call_Report__c</fullName>
        <label>Call Plan / Call Report</label>
        <referenceTo>Call_Report__c</referenceTo>
        <relationshipName>Leads</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Target_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target List</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Target_List__c.Lead_Campaign__r.Status</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>Target_List__c.Lead_Campaign__r.Sub_Type__c</field>
                <operation>notEqual</operation>
                <value>Value Chain</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Target_List__c</referenceTo>
        <relationshipLabel>Call Reports / Leads</relationshipLabel>
        <relationshipName>Associated_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Call Report / Lead</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Reports / Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Call_Report_Opportunity__c.object
<CustomObject>
    <description>This object track the relationship between Call Report and Opportunity for the many to many relationship</description>
    <fields>
        <fullName>Call_Plan_Call_Report__c</fullName>
        <label>Call Plan / Call Report</label>
        <referenceTo>Call_Report__c</referenceTo>
        <relationshipName>Call_Report_Opportunity</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.OwnerId</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Call Reports / Opportunities</relationshipLabel>
        <relationshipName>Call_Report_Opportunity</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Call Report / Opportunity</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Reports / Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Campaign.object
<CustomObject>
    <recordTypes>
        <fullName>SME_Event</fullName>
        <active>true</active>
        <description>SME Marketing Event</description>
        <label>SME-Event</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CIS_ID__c</fullName>
        <formula>Account.Name</formula>
        <label>CIS ID</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity_Lead__c.object
<CustomObject>
    <description>This object tracks the Lead associated to Opportunity</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities / Leads</relationshipLabel>
        <relationshipName>Opportunities_Leads</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Target_List__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Target List</label>
        <referenceTo>Target_List__c</referenceTo>
        <relationshipLabel>Opportunities / Leads</relationshipLabel>
        <relationshipName>Opportunities_Leads</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Opportunity / Lead</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities / Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Target_List__c.object
<CustomObject>
    <description>This object tracks the list of Targeted Lead and Campaign Member list</description>
    <fields>
        <fullName>CIS_ID_Prospect_Name__c</fullName>
        <label>CIS ID / Prospect Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Campaign_Members_Leads</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Lead_Campaign__c</fullName>
        <label>Lead/Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Target Lists</relationshipLabel>
        <relationshipName>Campaign_Members_Leads</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Target Lists</relationshipLabel>
        <relationshipName>Target_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Target List</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CallReportOpportunity_Test.cls
/**
* @author komsan.wi@beryl8.com
* @30/09/2015 created new
*/
@isTest
private class CallReportOpportunity_Test {
    public static String accountNameTM = 'tmCreatedAccountName';
    public static String accountNameRM = 'rmCreatedAccountName';
    public static String accountNameAH = 'ahCreatedAccountName';
	@testSetup static void setupAccount(){
		Mockup_Test mt = new Mockup_Test().setUpTest();

		System.runAs([SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameTM LIMIT 1][0]){
            mt.newAccount(accountNameTM,GlobalConstants.POOL,Mockup_Test.getRecordTypeAccountIdByName(GlobalConstants.SME_CUSTOMER));
        }
        /*System.runAs([SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameRM LIMIT 1][0]){
            mt.newAccount(accountNameRM,GlobalConstants.POOL,Mockup_Test.getRecordTypeAccountIdByName(GlobalConstants.SME_CUSTOMER));
        }
        System.runAs([SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameAH LIMIT 1][0]){
            mt.newAccount(accountNameAH,GlobalConstants.POOL,Mockup_Test.getRecordTypeAccountIdByName(GlobalConstants.SME_CUSTOMER));
        }*/
	}
	static testMethod void defaultLeadToOpportunity(){
		System.runAs([SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameTM LIMIT 1][0]){
			Account testAcc = [SELECT Id FROM Account WHERE Name = :CallReportOpportunity_Test.accountNameTM LIMIT 1];
			Opportunity opp1 = Mockup_Test.newOpportunity(testAcc.Id, 'Tester1', GlobalConstants.CREATE_WRITE_UP, GlobalConstants.NON_CMAS);
			insert opp1;		

			Campaign camp = Mockup_Test.newCampaign(UserInfo.getUserId(), 'TestCampaign', System.now(), System.now().addDays(1), System.now().addDays(-1), GlobalConstants.ACTIVE, GlobalConstants.SME_EVENT, GlobalConstants.LEAD_FOR_SALES);
            insert camp;

			Target_List__c target = new Target_List__c();
			target.Lead_Campaign__c = camp.Id;
			target.CIS_ID_Prospect_Name__c = testAcc.Id;
			insert target;

			Call_Report__c callReport = new Call_Report__c();
			callReport.Plan_Amount__c = 50000;
			callReport.CIS_ID__c = testAcc.Id;
			insert callReport;

			Call_Report_Lead__c callReportLead = new Call_Report_Lead__c();
			callReportLead.Call_Plan_Call_Report__c = callReport.Id;
			callReportLead.Target_List__c = target.Id;
			insert callReportLead;

			Call_Report_Opportunity__c callReportOpp = new Call_Report_Opportunity__c();
			callReportOpp.Call_Plan_Call_Report__c = callReport.Id;
			callReportOpp.Opportunity_Name__c = opp1.Id;

			Test.startTest();
				insert callReportOpp;
			Test.stopTest();

			Opportunity_Lead__c oppLead = [SELECT Target_List__c FROM Opportunity_Lead__c WHERE Opportunity__c = :callReportOpp.Opportunity_Name__c LIMIT 1];
			System.assertEquals(target.Id, oppLead.Target_List__c);
		}
	}
}