objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>SME_Customer</fullName>
        <active>true</active>
        <label>SME-Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Call_Report__c.object
<CustomObject>
    <description>This object tracks the Call Plan and Call Report</description>
    <fields>
        <fullName>CIS_ID__c</fullName>
        <label>CIS ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call Plans / Call Reports</relationshipLabel>
        <relationshipName>Call_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Call Plan / Call Report</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Call Plan / Call Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Plans / Call Reports</pluralLabel>
    <recordTypes>
        <fullName>CallReport</fullName>
        <active>true</active>
        <description>with Call Plan section</description>
        <label>Call Report</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Call_Report_Lead__c.object
<CustomObject>
    <description>This object tracks the Lead associated to Call Plan/Call Report</description>
    <fields>
        <fullName>Call_Plan_Call_Report__c</fullName>
        <label>Call Plan / Call Report</label>
        <referenceTo>Call_Report__c</referenceTo>
        <relationshipName>Leads</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Target_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target List</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Target_List__c.Lead_Campaign__r.Status</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>Target_List__c.Lead_Campaign__r.Sub_Type__c</field>
                <operation>notEqual</operation>
                <value>Value Chain</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Target_List__c</referenceTo>
        <relationshipLabel>Call Reports / Leads</relationshipLabel>
        <relationshipName>Associated_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Call Report / Lead</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Reports / Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Campaign.object
<CustomObject>
    <recordTypes>
        <fullName>SME_Event</fullName>
        <active>true</active>
        <description>SME Marketing Event</description>
        <label>SME-Event</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CIS_ID__c</fullName>
        <formula>Account.Name</formula>
        <label>CIS ID</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity_Lead__c.object
<CustomObject>
    <description>This object tracks the Lead associated to Opportunity</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities / Leads</relationshipLabel>
        <relationshipName>Opportunities_Leads</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Target_List__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Target List</label>
        <referenceTo>Target_List__c</referenceTo>
        <relationshipLabel>Opportunities / Leads</relationshipLabel>
        <relationshipName>Opportunities_Leads</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Opportunity / Lead</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities / Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Target_List__c.object
<CustomObject>
    <description>This object tracks the list of Targeted Lead and Campaign Member list</description>
    <fields>
        <fullName>CIS_ID_Prospect_Name__c</fullName>
        <label>CIS ID / Prospect Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Campaign_Members_Leads</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Lead_Campaign__c</fullName>
        <label>Lead/Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Target Lists</relationshipLabel>
        <relationshipName>Campaign_Members_Leads</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Target Lists</relationshipLabel>
        <relationshipName>Target_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Target List</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OpportunityLead_Test.cls
@isTest
private class OpportunityLead_Test {
	public static String accountNameAH = 'accountNameAH';

	@testSetup static void setupUser(){
		Mockup_Test mt = new Mockup_Test().setUpTest();

		System.runAs([SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameAH LIMIT 1][0]){
            mt.newAccount(accountNameAH,GlobalConstants.POOL,Mockup_Test.getRecordTypeAccountIdByName(GlobalConstants.SME_CUSTOMER));
        }
	}

	static testMethod void testAddOppLead(){
		String ahRcCode = '99996';
		String ahName = 'Name4';
		String ahEmpId = '2342411';

		System.runAs([SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameAH LIMIT 1][0]){

			Account testAcc = [SELECT Id FROM Account WHERE Name = :OpportunityLead_Test.accountNameAH LIMIT 1];

			Opportunity opp = Mockup_Test.newOpportunity(testAcc.Id, 'Tester1', GlobalConstants.CREATE_WRITE_UP, GlobalConstants.NON_CMAS);
			insert opp;		

			Campaign camp = Mockup_Test.newCampaign(UserInfo.getUserId(), 'TestCampaign', System.now(), System.now().addDays(1), System.now().addDays(-1), GlobalConstants.ACTIVE, GlobalConstants.SME_EVENT, GlobalConstants.LEAD_FOR_SALES);
            insert camp;

            Campaign camp2 = Mockup_Test.newCampaign(UserInfo.getUserId(), 'TestCampaign2', System.now(), System.now().addDays(1), System.now().addDays(-1), GlobalConstants.ACTIVE, GlobalConstants.SME_EVENT, GlobalConstants.LEAD_FOR_SALES);
            insert camp2;

			Target_List__c target = new Target_List__c();
			target.Lead_Campaign__c = camp.Id;
			target.CIS_ID_Prospect_Name__c = testAcc.Id;
			insert target;

			Target_List__c target2 = new Target_List__c();
			target2.Lead_Campaign__c = camp2.Id;
			target2.CIS_ID_Prospect_Name__c = testAcc.Id;
			insert target2;

			//Call_Report__c callReport = new Call_Report__c();
			//callReport.CIS_ID__c = testAcc.Id;
			//insert callReport;

			//Call_Report_Lead__c callReportLead = new Call_Report_Lead__c();
			//callReportLead.Call_Plan_Call_Report__c = callReport.Id;
			//callReportLead.Target_List__c = target.Id;
			//insert callReportLead;

			Opportunity_Lead__c oppLead = new Opportunity_Lead__c();
			oppLead.Opportunity__c = opp.Id;
			oppLead.Target_List__c = target.Id;

			Opportunity_Lead__c oppLead2 = new Opportunity_Lead__c();
			oppLead2.Opportunity__c = opp.Id;
			oppLead2.Target_List__c = target2.Id;

			Test.startTest();
				try {
					insert oppLead2;
					System.assertNotEquals(null, [SELECT Id FROM Opportunity_Lead__c WHERE Id = :oppLead2.Id LIMIT 1]);
				} catch (Exception e) {
					Boolean expectedExceptionThrown =  e.getMessage().contains('Opportunity Lead need to be the same name') ? true : false;
					//System.assertEquals(expectedExceptionThrown, true);
				}				
				insert oppLead;
				System.assertNotEquals(null, [SELECT Id FROM Opportunity_Lead__c WHERE Id = :oppLead.Id LIMIT 1]);
			Test.stopTest();
			
		}

	}

	static testMethod void testOppLead(){
		String ahRcCode = '99996';
		String ahName = 'Name4';
		String ahEmpId = '2342411';

		System.runAs([SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameAH LIMIT 1][0]){

			Account testAcc = [SELECT Id FROM Account WHERE Name = :OpportunityLead_Test.accountNameAH LIMIT 1];

			Opportunity opp = Mockup_Test.newOpportunity(testAcc.Id, 'Tester1', GlobalConstants.CREATE_WRITE_UP, GlobalConstants.NON_CMAS);
			insert opp;		

			Campaign camp = Mockup_Test.newCampaign(UserInfo.getUserId(), 'TestCampaign', System.now(), System.now().addDays(1), System.now().addDays(-1), GlobalConstants.ACTIVE, GlobalConstants.SME_EVENT, GlobalConstants.LEAD_FOR_SALES);
            insert camp;

            Campaign camp2 = Mockup_Test.newCampaign(UserInfo.getUserId(), 'TestCampaign2', System.now(), System.now().addDays(1), System.now().addDays(-1), GlobalConstants.ACTIVE, GlobalConstants.SME_EVENT, GlobalConstants.LEAD_FOR_SALES);
            insert camp2;

			Target_List__c target = new Target_List__c();
			target.Lead_Campaign__c = camp.Id;
			target.CIS_ID_Prospect_Name__c = testAcc.Id;
			insert target;

			Target_List__c target2 = new Target_List__c();
			target2.Lead_Campaign__c = camp2.Id;
			target2.CIS_ID_Prospect_Name__c = testAcc.Id;
			insert target2;

			Call_Report__c callReport = new Call_Report__c();
			callReport.CIS_ID__c = testAcc.Id;
			insert callReport;

			Call_Report_Lead__c callReportLead = new Call_Report_Lead__c();
			callReportLead.Call_Plan_Call_Report__c = callReport.Id;
			callReportLead.Target_List__c = target.Id;
			insert callReportLead;

			Opportunity_Lead__c oppLead = new Opportunity_Lead__c();
			oppLead.Opportunity__c = opp.Id;
			oppLead.Target_List__c = target.Id;

			Opportunity_Lead__c oppLead2 = new Opportunity_Lead__c();
			oppLead2.Opportunity__c = opp.Id;
			oppLead2.Target_List__c = target2.Id;

			Test.startTest();
				try {
					insert oppLead2;
				} catch (Exception e) {
					Boolean expectedExceptionThrown =  e.getMessage().contains('Opportunity Lead need to be the same name') ? true : false;
					System.assertEquals(expectedExceptionThrown, true);
				}
				
				insert oppLead;
				System.assertNotEquals(null, [SELECT Id FROM Opportunity_Lead__c]);
			Test.stopTest();
			
		}

	}
	
}