objects/Account.object
<CustomObject>
    <fields>
        <fullName>AH_Name__c</fullName>
        <formula>Owner.AH_Name__c</formula>
        <label>AH Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AH_RC_Code__c</fullName>
        <formula>Owner.AH_RC_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AH RC Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NH_Name__c</fullName>
        <formula>Owner.NH_Name__c</formula>
        <label>NH Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NH_RC_Code__c</fullName>
        <formula>Owner.NH_RC_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NH RC Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ownership_Text__c</fullName>
        <label>Ownership</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Permanent_AH_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Permanent AH Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Accounts (Permanent AH Name)</relationshipLabel>
        <relationshipName>AccountsPermanentAHName</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Permanent_NH_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Permanent NH Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Accounts (Permanent NH Name)</relationshipLabel>
        <relationshipName>AccountsPermanentNHName</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Permanent_Owner_Extension__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Permanent Owner Extension</label>
        <referenceTo>User_Extension__c</referenceTo>
        <relationshipLabel>Accounts (Permanent Owner Extension)</relationshipLabel>
        <relationshipName>AccountsPermanentOwnerExtension</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Permanent_Team_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Permanent Team Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Accounts (Permanent Team Name)</relationshipLabel>
        <relationshipName>AccountsPermanentTeamName</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Port_Pool__c</fullName>
        <label>Port / Pool</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RC_Code__c</fullName>
        <formula>Owner.RC_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RC Code</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Team_Structure__c.object
<CustomObject>
    <fields>
        <fullName>AH_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AH Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Team Structure</relationshipLabel>
        <relationshipName>Team_Structure</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AH_RC_Code__c</fullName>
        <label>AH RC Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NH_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NH Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Team Structure (NH Name)</relationshipLabel>
        <relationshipName>Team_Structure1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NH_RC_Code__c</fullName>
        <label>NH RC Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RC_Code__c</fullName>
        <label>RC Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Team Structure</label>
    <nameField>
        <label>Team Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Structure</pluralLabel>
    <recordTypes>
        <fullName>Team</fullName>
        <active>true</active>
        <label>Team</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>AH_Name__c</fullName>
        <label>AH Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AH_RC_Code__c</fullName>
        <label>AH RC Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NH_Name__c</fullName>
        <label>NH Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NH_RC_Code__c</fullName>
        <label>NH RC Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RC_Code__c</fullName>
        <label>RC Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/User_Extension__c.object
<CustomObject>
    <description>To store user&apos;s information.</description>
    <fields>
        <fullName>Team_Structure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>User Extension</relationshipLabel>
        <relationshipName>User_Extension</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Extension</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Extension</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Extension</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SME_FixAccountPermanentOwner_Batch.cls
global class SME_FixAccountPermanentOwner_Batch extends ApplicationLog_Service implements Database.Batchable<sObject>, Database.stateful {
    
    private static final String CLASS_NAME = 'SME_FixAccountPermanentOwner_Batch';

    Map<String, Id> userExMapByUser;
    Map<Id, User> userMap;
    Map<String, Team_Structure__c> teamIdMapByRC;
    String query;
    
    global SME_FixAccountPermanentOwner_Batch() {
        userMap = new Map<Id, User>([SELECT Id, RC_Code__c, AH_RC_Code__c, NH_RC_Code__c, IsActive, Profile.Name, ManagerId, Manager.ManagerId, Manager.IsActive, Manager.Manager.Id, Manager.Manager.IsActive FROM User]);

        teamIdMapByRC = new Map<String, Team_Structure__c>();
        List<Team_Structure__c> teamList = [SELECT Id, RC_Code__c, AH_Name__c, NH_Name__c FROM Team_Structure__c];
        for(Team_Structure__c eachTeam : teamList) {
            if(eachTeam.RC_Code__c != null)
                teamIdMapByRc.put(eachTeam.RC_Code__c, eachTeam);
        }

        userExMapByUser = new Map<String, Id>();
        List<User_Extension__c> userExList = [SELECT Id, User__c FROM User_Extension__c];
        for(User_Extension__c eachEx : userExList) {
            if(eachEx.User__c != null)
                userExMapByUser.put(eachEx.User__c, eachEx.Id);
        }

        this.query = 'SELECT Id, Port_Pool__c, Ownership_Text__c, RecordType.DeveloperName, OwnerId FROM Account';
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Account> scope) {
        User ownerUser;
        List<Account> updateAccount = new List<Account>();
        for(Account eachAccount : scope) {
            if(userMap.containsKey(eachAccount.OwnerId)) {
                ownerUser = userMap.get(eachAccount.OwnerId);
            } else {
                addLog(CLASS_NAME,'Cannot find Account Owner from Owner Id : ' + eachAccount.OwnerId);
                continue;
            }

            if(ownerUser.Profile.Name == GlobalConstants.SME_ADMIN || eachAccount.RecordType.DeveloperName == GlobalConstants.SME_PROSPECT_DEVNAME) { // Prospect
                if(eachAccount.RecordType.DeveloperName == GlobalConstants.SME_PROSPECT_DEVNAME) {
                    eachAccount.Ownership_Text__c = GlobalConstants.OWNERSHIP_TEMPORARY;    
                }
                if(ownerUser.Profile.Name == GlobalConstants.SME_ADMIN) {
                    eachAccount.Ownership_Text__c = null;
                }
                
                eachAccount.Port_Pool__c = null;
                eachAccount.Permanent_Owner_Extension__c = null;
                eachAccount.Permanent_Team_Name__c = null;
                eachAccount.Permanent_AH_Name__c = null; 
                eachAccount.Permanent_NH_Name__c = null;
            } else if (eachAccount.RecordType.DeveloperName == GlobalConstants.SME_CUSTOMER_DEVNAME) { // Customer
                if(eachAccount.Port_Pool__c == GlobalConstants.PORT) { // Port
                    // If Port_Pool__c = Port Ownership = Permanent only
                    eachAccount.Ownership_Text__c = GlobalConstants.OWNERSHIP_PERMANENT;
                    // Permanent Owner = Current Owner
                    eachAccount = setPermanentOwner(ownerUser, eachAccount);
                    if(eachAccount == null) continue;
                } else if(eachAccount.Port_Pool__c == GlobalConstants.POOL) { // Pool
                    if(ownerUser.Profile.Name == GlobalConstants.SME_RM) {
                        eachAccount.Ownership_Text__c = GlobalConstants.OWNERSHIP_TEMPORARY;
                        // Permanent Owner = Current Owner Manager
                        if(ownerUser.Manager != null) {
                            eachAccount = setPermanentOwner(userMap.get(ownerUser.ManagerId), eachAccount);
                            if(eachAccount == null) continue;
                        } else {
                            addLog(CLASS_NAME,'Cannot find Manager of RM User Id : ' + ownerUser.Id);
                            continue;
                        }
                    } else if(ownerUser.Profile.Name == GlobalConstants.SME_TM || ownerUser.Profile.Name == GlobalConstants.SME_AH) {
                        eachAccount.Ownership_Text__c = GlobalConstants.OWNERSHIP_PERMANENT;
                        // Permanent Owner = Current Owner
                        eachAccount = setPermanentOwner(ownerUser, eachAccount);
                        if(eachAccount == null) continue;
                    }
                } else if(eachAccount.Port_Pool__c == null && (eachAccount.Ownership_Text__c == null || eachAccount.Ownership_Text__c == GlobalConstants.OWNERSHIP_TEMPORARY)) { // Converted Customer
                    eachAccount.Ownership_Text__c = GlobalConstants.OWNERSHIP_TEMPORARY;
                    eachAccount.Permanent_Owner_Extension__c = null;
                    eachAccount.Permanent_Team_Name__c = null;
                    eachAccount.Permanent_AH_Name__c = null; 
                    eachAccount.Permanent_NH_Name__c = null;
                } else {
                    addLog(CLASS_NAME,'Port/Pool is null from Account Id : ' + eachAccount.Id);
                    continue;
                }
            }
            updateAccount.add(eachAccount);
        }
        clearance(updateAccount);
    }
    
    private Account setPermanentOwner(User ownerUser, Account eachAccount) {
        if(ownerUser.IsActive) { // Check Is Active
            if(userExMapByUser.containsKey(ownerUser.Id)) {
                eachAccount.Permanent_Owner_Extension__c = userExMapByUser.get(ownerUser.Id);
            } else {
                addLog(CLASS_NAME,'Cannot map User Extension from User Id : ' + ownerUser.Id);
                return null;
            }
            
            if(teamIdMapByRC.containsKey(ownerUser.RC_Code__c)) {
                Team_Structure__c eachTeam = teamIdMapByRC.get(ownerUser.RC_Code__c);
                if(ownerUser.Profile.Name == GlobalConstants.SME_RM || ownerUser.Profile.Name == GlobalConstants.SME_TM) {
                    eachAccount.Permanent_Team_Name__c = eachTeam.Id;
                    eachAccount.Permanent_AH_Name__c = eachTeam.AH_Name__c;
                    eachAccount.Permanent_NH_Name__c = eachTeam.NH_Name__c;
                } else if(ownerUser.Profile.Name == GlobalConstants.SME_AH) {
                    eachAccount.Permanent_Team_Name__c = null;
                    eachAccount.Permanent_AH_Name__c = eachTeam.Id;
                    eachAccount.Permanent_NH_Name__c = eachTeam.NH_Name__c;
                } else if(ownerUser.Profile.Name == GlobalConstants.SME_NH) {
                    eachAccount.Permanent_Team_Name__c = null;
                    eachAccount.Permanent_AH_Name__c = null;
                    eachAccount.Permanent_NH_Name__c = eachTeam.Id;
                }
                
            } else {
                addLog(CLASS_NAME,'Cannot map Team Structure from RC Code : ' + ownerUser.RC_Code__c);
                return null;
            }

            return eachAccount;
        } else {
            if(ownerUser.Manager != null) {
                return setPermanentOwner(userMap.get(ownerUser.ManagerId), eachAccount);    
            } else {
                eachAccount.Permanent_Owner_Extension__c = null;
                eachAccount.Permanent_Team_Name__c = null;
                eachAccount.Permanent_AH_Name__c = null;
                eachAccount.Permanent_NH_Name__c = null;
                return eachAccount;
            }
        }
    }

    private void clearance(List<Account> updateAccount){
        if(!updateAccount.isEmpty()){
            TriggerHandler.bypass('AccountTriggerHandler');
            update updateAccount;
        }
        super.clearance();
    }

    global void finish(Database.BatchableContext BC) {
        
    }
    
}