objects/Account.object
<CustomObject>
    <fields>
        <fullName>NH_RC_Code__c</fullName>
        <formula>Owner.NH_RC_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NH RC Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <formula>CASE( Primary_Segment_Code__c,
&quot;UM&quot;, IMAGE(&quot;/resource/SMESegment&quot;,&quot;SME&quot;),
&quot;UR&quot;, IMAGE(&quot;/resource/SMESegment&quot;,&quot;SME&quot;),
&quot;SM&quot;, IMAGE(&quot;/resource/SMESegment&quot;,&quot;SME&quot;),
&quot;SR&quot;, IMAGE(&quot;/resource/SMESegment&quot;,&quot;SME&quot;),
&quot;LM&quot;, IMAGE(&quot;/resource/SMESegment&quot;,&quot;SME&quot;),
&quot;LR&quot;, IMAGE(&quot;/resource/SMESegment&quot;,&quot;SME&quot;),
IMAGE(&quot;/resource/Non_SME_Segment&quot;,&quot;Non-SME&quot;,60,90))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Segment</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_RM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service RM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Bulk_Assignment__c.object
<CustomObject>
    <description>This object will be help to manage and stored bulk assignment history</description>
    <fields>
        <fullName>Service_RM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service RM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Bulk_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bulk Assignment</label>
    <nameField>
        <displayFormat>BulkAssign-{0000000000}</displayFormat>
        <label>Bulk Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bulk Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Team_Structure__c.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NH_RC_Code__c</fullName>
        <label>NH RC Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <picklist>
            <picklistValues>
                <fullName>Small</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Team Structure</label>
    <nameField>
        <label>Team Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Structure</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>NH_RC_Code__c</fullName>
        <label>NH RC Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/User_Extension__c.object
<CustomObject>
    <description>To store user&apos;s information.</description>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <formula>User__r.Segment__c</formula>
        <label>Segment</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team_Structure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>User Extension</relationshipLabel>
        <relationshipName>User_Extension</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Extension</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Extension</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Extension</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/User_Service.cls
public class User_Service {
    public static Map<Id, User> allUserMap;
    public static Map<Id, User> allOldUserMap;
    public static Map<String, User_Extension__c> userExtensionMapByUserId;
    public static Map<String, Team_Structure__c> teamMapByRC;

    public static Map<String, User_Extension__c> getUserExtensionMapByUser() {
        List<User_Extension__c> userExtList = new List<User_Extension__c>();
        userExtList = [SELECT Id, User__c, OwnerId FROM User_Extension__c];
        Map<String, User_Extension__c>  userExtMapByUser = new Map<String, User_Extension__c> ();
        
        for(User_Extension__c eachUserExt : userExtList) {
            userExtMapByUser.put(eachUserExt.User__c, eachUserExt);
        }
        return userExtMapByUser;
    }

    public static Map<String, Team_Structure__c> getAllTeamStructureMapByRC() {
        List<Team_Structure__c> teamStructureList = new List<Team_Structure__c>();
        teamStructureList = [SELECT Id, External_ID__c, OwnerId, Segment__c, Name, Type__c,NH_RC_Code__c FROM Team_Structure__c];
        Map<String, Team_Structure__c> allTeamMapByRc = new Map<String, Team_Structure__c>();

        for(Team_Structure__c eachTeam : teamStructureList) {
            allTeamMapByRc.put(eachTeam.External_ID__c, eachTeam);
        }
        return allTeamMapByRc;
    }

    //public static void inactiveServiceRM(Map<Id, Bulk_Assignment__c> assignMapByCurrentUser) {
    //    List<Account> accountUpdateList = new List<Account>();
    //    accountUpdateList = [SELECT Id, Service_RM__c FROM Account WHERE Service_RM__c IN:assignMapByCurrentUser.keyset()];
    //    for(Account eachAccount : accountUpdateList) {
    //        if(assignMapByCurrentUser.containsKey(eachAccount.Service_RM__c)) {
    //            eachAccount.Service_RM__c = null;
    //        }
    //    }
    //    if(accountUpdateList.size() > 0)
    //        update accountUpdateList;
    //}
}