objects/Account.object
<CustomObject>
    <fields>
        <fullName>Delete_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Delete Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Previous_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Credit Status</label>
        <picklist>
            <picklistValues>
                <fullName>Good Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>SME_Customer</fullName>
        <active>true</active>
        <label>SME-Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Call_Report__c.object
<CustomObject>
    <description>This object tracks the Call Plan and Call Report</description>
    <fields>
        <fullName>Actual_Visit_Date__c</fullName>
        <defaultValue>IF(CONTAINS($RecordType.DeveloperName,&quot;CallReport&quot;),TODAY(),NULL)</defaultValue>
        <inlineHelpText>ห้ามเกินกว่าวันปัจจุบัน</inlineHelpText>
        <label>Actual Visit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CIS_ID__c</fullName>
        <label>CIS ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call Plans / Call Reports</relationshipLabel>
        <relationshipName>Call_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Expected_Credit_Amount__c</fullName>
        <label>Expected Credit Amount (Baht)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Offer_Credit_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Offer Credit Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Offer_Interest__c</fullName>
        <label>Offer Interest</label>
        <picklist>
            <controllingField>Offer_Credit_Product__c</controllingField>
            <picklistValues>
                <fullName>Interest and can apply</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interest with condition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cannot apply</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer not interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interested with condition</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Plan_Date__c</fullName>
        <label>Plan Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Call Plan / Call Report</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Call Plan / Call Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Plans / Call Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CIS_ID__c</fullName>
        <formula>Account.CIS__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CIS ID</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Actual_Visit_Date__c</fullName>
        <description>Call Report Actual Visit Date</description>
        <label>Actual Visit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CIS_ID__c</fullName>
        <formula>Account.Name</formula>
        <label>CIS ID</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Pool_Visibility__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>This custom setting is for controlling visibility of customer pool</description>
    <fields>
        <fullName>Group_Indicate__c</fullName>
        <label>Group Indicate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role_Name__c</fullName>
        <label>Role Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Pool Visibility</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is updated by DIH (HRIS): A = Active, I=Inactive</description>
        <label>Status Code</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Account_OwnerChange_Test.cls
/**
* @author komsan.wi@beryl8.com
* @12/07/2015 createddate
*/
@isTest
private class Account_OwnerChange_Test {
    public static String accountNameTM = 'tmCreatedAccountName';
    public static String accountNameRM = 'rmCreatedAccountName';
    public static String accountNameAH = 'ahCreatedAccountName';

    public static String contactNameTM = 'tmCreatedContactName';
    public static String contactNameRM = 'rmCreatedContactName';
    public static String contactNameAH = 'ahCreatedContactName';

    public static String lastNameTM = 'tmCreatedLastName';
    public static String lastNameRM = 'rmCreatedLastName';
    public static String lastNameAH = 'ahCreatedLastName';
    @testSetup static void setupUser(){
        Mockup_Test mt = new Mockup_Test().setUpTestWithRCCode();
        
        System.runAs([SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameTM LIMIT 1][0]){
            mt.newAccountWithContact(accountNameTM,contactNameTM,lastNameTM,'Pool',Mockup_Test.getRecordTypeAccountIdByName(GlobalConstants.SME_CUSTOMER));
        }
        System.runAs([SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameRM LIMIT 1][0]){
            mt.newAccountWithContact(accountNameRM,contactNameRM,lastNameRM,'Pool',Mockup_Test.getRecordTypeAccountIdByName(GlobalConstants.SME_CUSTOMER));
        }
        System.runAs([SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameAH LIMIT 1][0]){
            mt.newAccountWithContact(accountNameAH,contactNameAH,lastNameAH,'Pool',Mockup_Test.getRecordTypeAccountIdByName(GlobalConstants.SME_CUSTOMER));
        }
    }
    static testMethod void changeOwnershipWhenCreateCallReport(){
        Account targetAccount = [SELECT Id,Delete_Flag__c,OwnerId,Previous_Owner__c FROM Account WHERE Name = :Account_OwnerChange_Test.accountNameTM LIMIT 1];
        User userRM = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameRM LIMIT 1];
        User userTM = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameTM LIMIT 1];
        System.assertEquals(userTM.Id,targetAccount.OwnerId);
        System.assertEquals(null,targetAccount.Previous_Owner__c);
        System.runAs(userRM){
            Call_Report__c callreportObj;
            
            callreportObj = new Call_Report__c(
                CIS_ID__c = targetAccount.Id,
                Status__c = 'Plan',
                Plan_Date__c = System.Today(),
                Offer_Interest__c = 'Interest and can apply',
                Expected_Credit_Amount__c = 100000,
                RecordTypeId = GlobalUtility.getRecordTypeIdFromSObjectByDevName('Call_Report__c',GlobalConstants.CALL_PLAN_DEVNAME),
                Offer_Credit_Product__c = true,
                Actual_Visit_Date__c  = System.Today()-1
            );
            Test.startTest();
                insert callreportObj;
            Test.stopTest();
            Account finalAccount = [SELECT Id,Delete_Flag__c,OwnerId,Previous_Owner__c FROM Account WHERE Name = :Account_OwnerChange_Test.accountNameTM LIMIT 1];
            Contact finalContact = [SELECT Id,OwnerId FROM Contact WHERE Account.Name = :Account_OwnerChange_Test.accountNameTM LIMIT 1];

            System.assertEquals(userRM.Id,finalContact.OwnerId);
            System.assertEquals(userRM.Id,finalAccount.OwnerId);
            System.assertEquals(userTM.Id,finalAccount.Previous_Owner__c);
        }
    }
    static testMethod void changeOwnershipWhenCreateCallReportANDCreatedSharingRule(){
        // Create custom setting
        Pool_Visibility__c areaBKK1 = new Pool_Visibility__c();
        areaBKK1.Group_Indicate__c = 'Bangkok';
        areaBKK1.Name = 'RC' + Mockup_Test.NH_RC_CODE;
        areaBKK1.Role_Name__c = 'เครือข่ายลูกค้าผู้ประกอบการ 1 (กทม.2)';
        insert areaBKK1;

        ////////////////////////

        Account targetAccount = [SELECT Id,Delete_Flag__c,OwnerId,Previous_Owner__c FROM Account WHERE Name = :Account_OwnerChange_Test.accountNameAH LIMIT 1];
        User userRM = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameRM LIMIT 1];
        User userTM = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameTM LIMIT 1];
        User userAH = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameAH LIMIT 1];
        System.assertEquals(userAH.Id,targetAccount.OwnerId);
        System.assertEquals(null,targetAccount.Previous_Owner__c);
        System.runAs(userTM){
            Call_Report__c callreportObj;
            callreportObj = new Call_Report__c(
                CIS_ID__c = targetAccount.Id,
                Status__c = 'Plan',
                Plan_Date__c = System.Today(),
                Offer_Interest__c = 'Interest and can apply',
                Expected_Credit_Amount__c = 100000,
                RecordTypeId = GlobalUtility.getRecordTypeIdFromSObjectByDevName('Call_Report__c',GlobalConstants.CALL_PLAN_DEVNAME),
                Offer_Credit_Product__c = true,
                Actual_Visit_Date__c  = System.Today()-1
            );
            Test.startTest();
                insert callreportObj;
            Test.stopTest();
        }
        Account finalAccount = [SELECT Id,Delete_Flag__c,OwnerId,Previous_Owner__c FROM Account WHERE Name = :Account_OwnerChange_Test.accountNameAH LIMIT 1];
        
        System.assertEquals(targetAccount.Id,finalAccount.Id);
        System.assertEquals(userTM.Id,finalAccount.OwnerId);
        System.assertEquals(userAH.Id,finalAccount.Previous_Owner__c);

        List<AccountShare> finalAccountShare = new List<AccountShare>();
        finalAccountShare = [SELECT Id FROM AccountShare WHERE AccountId = :finalAccount.Id AND RowCause='Manual'];
        System.assert(finalAccountShare!=null);
        System.assertEquals(1,finalAccountShare.size());
        
    }
    @isTest static void changeOwnershipWhenCreateCallReportANDCreatedSharingRuleANDReleaseBack(){
        // Create custom setting
        Pool_Visibility__c areaBKK1 = new Pool_Visibility__c();
        areaBKK1.Group_Indicate__c = 'Bangkok';
        areaBKK1.Name = 'RC' + Mockup_Test.NH_RC_CODE;
        areaBKK1.Role_Name__c = 'เครือข่ายลูกค้าผู้ประกอบการ 1 (กทม.2)';
        insert areaBKK1;

        ////////////////////////

        Account targetAccount = [SELECT Id,Delete_Flag__c,OwnerId,Previous_Owner__c FROM Account WHERE Name = :Account_OwnerChange_Test.accountNameAH LIMIT 1];
        User userRM = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameRM LIMIT 1];
        User userTM = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameTM LIMIT 1];
        User userAH = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameAH LIMIT 1];
        System.assertEquals(userAH.Id,targetAccount.OwnerId);
        System.assertEquals(null,targetAccount.Previous_Owner__c);
        Call_Report__c callreportObj;
        System.runAs(userTM){
            Opportunity targetOp = Mockup_Test.newOpportunity(targetAccount.Id, 'TestOp', GlobalConstants.CREATE_WRITE_UP, GlobalConstants.NON_CMAS);
            insert targetOp;

            callreportObj = new Call_Report__c(
                CIS_ID__c = targetAccount.Id,
                Status__c = GlobalConstants.PLAN,
                Plan_Date__c = System.Today(),
                Offer_Interest__c = 'Interest and can apply',
                Expected_Credit_Amount__c = 100000,
                RecordTypeId = GlobalUtility.getRecordTypeIdFromSObjectByDevName('Call_Report__c',GlobalConstants.CALL_PLAN_DEVNAME),
                Offer_Credit_Product__c = true,
                Actual_Visit_Date__c  = System.Today()-1
            );
            
            insert callreportObj;
            Call_Report__c resultCallReport = [SELECT Offer_Interest__c FROM Call_Report__c WHERE Id = :callreportObj.Id];
            //System.assertEquals('123',resultCallReport.Offer_Interest__c);
            Account finalAccount = [SELECT Id,Delete_Flag__c,OwnerId,Previous_Owner__c FROM Account WHERE Name = :Account_OwnerChange_Test.accountNameAH LIMIT 1];
            
            System.assertEquals(targetAccount.Id,finalAccount.Id);
            System.assertEquals(userTM.Id,finalAccount.OwnerId);
            System.assertEquals(userAH.Id,finalAccount.Previous_Owner__c);

            List<AccountShare> finalAccountShare = new List<AccountShare>();
            finalAccountShare = [SELECT Id FROM AccountShare WHERE AccountId = :finalAccount.Id AND RowCause='Manual'];
            System.assert(finalAccountShare!=null);
            System.assertEquals(1,finalAccountShare.size());
        }
        Account_OwnerChange_Service.triggerInitialCall = false;
    }
}