objects/Account.object
<CustomObject>
    <fields>
        <fullName>AH_Name__c</fullName>
        <formula>Owner.AH_Name__c</formula>
        <label>AH Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_AH_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current AH Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Accounts (Current AH Name)</relationshipLabel>
        <relationshipName>AccountsCurrentAHName</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_NH_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current NH Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Accounts (Current NH Name)</relationshipLabel>
        <relationshipName>AccountsCurrentNHName</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Owner_Extension__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Owner Extension</label>
        <referenceTo>User_Extension__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>AccountsCurrentOwnerExtension</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Team_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Team Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Accounts (Current Team Name)</relationshipLabel>
        <relationshipName>AccountsCurrentTeamName</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NH_Name__c</fullName>
        <formula>Owner.NH_Name__c</formula>
        <label>NH Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Permanent_AH_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Permanent AH Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Accounts (Permanent AH Name)</relationshipLabel>
        <relationshipName>AccountsPermanentAHName</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Permanent_NH_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Permanent NH Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Accounts (Permanent NH Name)</relationshipLabel>
        <relationshipName>AccountsPermanentNHName</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Permanent_Owner_Extension__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Permanent Owner Extension</label>
        <referenceTo>User_Extension__c</referenceTo>
        <relationshipLabel>Accounts (Permanent Owner Extension)</relationshipLabel>
        <relationshipName>AccountsPermanentOwnerExtension</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Permanent_Team_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Permanent Team Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Accounts (Permanent Team Name)</relationshipLabel>
        <relationshipName>AccountsPermanentTeamName</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RC_Code__c</fullName>
        <formula>Owner.RC_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RC Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Credit Status</label>
        <picklist>
            <picklistValues>
                <fullName>Good Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Bulk_Assignment__c.object
<CustomObject>
    <description>This object will be help to manage and stored bulk assignment history</description>
    <fields>
        <fullName>AssignmentOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>AssignmentOwner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Execute</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Bulk Assignment</label>
    <nameField>
        <displayFormat>BulkAssign-{0000000000}</displayFormat>
        <label>Bulk Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bulk Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Call_Report__c.object
<CustomObject>
    <description>This object tracks the Call Plan and Call Report</description>
    <fields>
        <fullName>Current_AH_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AH Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Call Plans / Call Reports (Current AH Name)</relationshipLabel>
        <relationshipName>Call_Plans_Call_Reports4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_NH_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NH Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Call Plans / Call Reports (Current NH Name)</relationshipLabel>
        <relationshipName>Call_Plans_Call_Reports5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Owner_Extension__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner Extension</label>
        <referenceTo>User_Extension__c</referenceTo>
        <relationshipLabel>Call Plans / Call Reports</relationshipLabel>
        <relationshipName>Call_Plans_Call_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Team_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Call Plans / Call Reports (Current Team Name)</relationshipLabel>
        <relationshipName>Call_Plans_Call_Reports3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Call Plan / Call Report</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Call Plan / Call Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Plans / Call Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Current_AH_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AH Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Opportunities (Current AH Name)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_NH_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NH Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Opportunities (Current NH Name)</relationshipLabel>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Owner_Extension__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner Extension</label>
        <referenceTo>User_Extension__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Team_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Team_Structure__c.object
<CustomObject>
    <fields>
        <fullName>AH_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AH Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Team Structure</relationshipLabel>
        <relationshipName>Team_Structure</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Call_Report__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Call Report</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NH_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NH Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Team Structure (NH Name)</relationshipLabel>
        <relationshipName>Team_Structure1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RC_Code__c</fullName>
        <label>RC Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Team Structure</label>
    <nameField>
        <label>Team Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Structure</pluralLabel>
    <recordTypes>
        <fullName>Team</fullName>
        <active>true</active>
        <label>Team</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>AH_Name__c</fullName>
        <label>AH Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Employee ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NH_Name__c</fullName>
        <label>NH Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RC_Code__c</fullName>
        <label>RC Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is updated by DIH (HRIS): A = Active, I=Inactive</description>
        <label>Status Code</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/User_Extension__c.object
<CustomObject>
    <description>To store user&apos;s information.</description>
    <fields>
        <fullName>Call_Report__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Call Report</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <formula>User__r.Employee_ID__c</formula>
        <label>Employee ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Team_Structure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>User Extension</relationshipLabel>
        <relationshipName>User_Extension</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Extension</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Extension</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Extension</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/UserExtension_Service.cls
public class UserExtension_Service {

	private String userExtId;
	private String userObjId;
	private String userObjName;
	private String userObjEmployeeId;
	private String userObjTeam;

	public static Map<String, Id> allTeamMapByRc;
	public static Map<Id, Team_Structure__c> allTeamStructureMap;
	public static Map<String, Id> allUserExtMapByUser;
	public static List<SObject> updateGlobalList;

	public UserExtension_Service(User_Extension__c userExt) {
		this.userObjId = userExt.User__c;
        this.userObjName = userExt.Name;
        this.userObjEmployeeId = userExt.External_ID__c;
        this.userObjTeam = userExt.Team_Structure__c;
        this.userExtId = userExt.Id;
	}

	public UserExtension_Service(User userObj) {
		this.userObjId = userObj.Id;
        this.userObjName = userObj.Name;
        this.userObjEmployeeId = userObj.Employee_ID__c;
	}

	public static Map<Id, User> getAllUserMapByUserExt() {
		Map<Id, User_Extension__c> userExtensionMap = new Map<Id, User_Extension__c>([SELECT Id, User__c FROM User_Extension__c]);
        Map<Id, User> userMap = new Map<Id, User>([SELECT Id,IsActive,Profile.Name,ManagerId,Manager.ManagerId,Manager.Manager.ManagerId,Manager.IsActive,Manager.Manager.IsActive,Manager.Manager.Manager.IsActive FROM User]);
		Map<Id, User> resultMap = new Map<Id, User>();
		for(User_Extension__c eachUserExt : userExtensionMap.values()) {
			if(eachUserExt.User__c != null && userMap.containsKey(eachUserExt.User__c))
            	resultMap.put(eachUserExt.Id, userMap.get(eachUserExt.User__c));
        }
        return resultMap;
	}


	public static Map<String, Id> getUserExtensionMap(Set<String> empIds) {
		List<User_Extension__c> userExtList = new List<User_Extension__c>();
		userExtList = [SELECT Id, External_ID__c FROM User_Extension__c WHERE External_Id__c IN :empIds];
        Map<String, Id> userExtMapByEmpId = new Map<String, Id>();
		
		for(User_Extension__c eachUserExt : userExtList) {
            userExtMapByEmpId.put(eachUserExt.External_ID__c, eachUserExt.Id);
        }

        return userExtMapByEmpId;
	}

	public static Map<String, Id> getUserExtensionMapByUser() {
		List<User_Extension__c> userExtList = new List<User_Extension__c>();
		userExtList = [SELECT Id, User__c FROM User_Extension__c];
        Map<String, Id>  userExtMapByEmpId = new Map<String, Id> ();
		
		for(User_Extension__c eachUserExt : userExtList) {
            userExtMapByEmpId.put(eachUserExt.User__c, eachUserExt.Id);
        }

        return userExtMapByEmpId;
	}

	public static Map<String, Id> getAllTeamStructureMapByRC() {
		List<Team_Structure__c> teamStructureList = new List<Team_Structure__c>();
        teamStructureList = [SELECT Id, External_ID__c FROM Team_Structure__c];
		Map<String, Id> teamMapByRc = new Map<String, Id>();

        for(Team_Structure__c eachTeam : teamStructureList) {
            teamMapByRc.put(eachTeam.External_ID__c, eachTeam.Id);
        }
        return teamMapByRc;
	}

	public static Map<String, Id> getTeamStructureMap(Set<String> rcCodes) {
		List<Team_Structure__c> teamStructureList = new List<Team_Structure__c>();
        teamStructureList = [SELECT Id, External_ID__c FROM Team_Structure__c WHERE External_Id__c IN :rcCodes];
		Map<String, Id> teamMapByRc = new Map<String, Id>();

        for(Team_Structure__c eachTeam : teamStructureList) {
            teamMapByRc.put(eachTeam.External_ID__c, eachTeam.Id);
        }
        return teamMapByRc;
	}

	@future
	public static void insertUserExtension(String userExtStringList) {
		List<User_Extension__c> userExtList = (List<User_Extension__c>) JSON.deserialize(userExtStringList, List<User_Extension__c>.class);
		insert userExtList;
	}

	@future
	public static void updateUserExtension(String userExtStringList) {
		List<User_Extension__c> userExtList = (List<User_Extension__c>) JSON.deserialize(userExtStringList, List<User_Extension__c>.class);
		update userExtList;
	}

	//public static void reassignRelatedObject(Map<Id, Bulk_Assignment__c> assignMapByCurrentUser) {
	//	Map<Id, User_Extension__c> userExtMap = new Map<Id, User_Extension__c>(
	//	[SELECT Id, Team_Structure__c, Team_Structure__r.AH_Name__c, Team_Structure__r.NH_Name__c, User__c,
	//		(Select Id, Permanent_Owner_Extension__c, Permanent_Owner_Extension__r.User__c 
	//		FROM AccountsPermanentOwnerExtension__r WHERE Permanent_Owner_Extension__r.User__c IN :assignMapByCurrentUser.keySet())
	//	FROM User_Extension__c]);

	//	Map<String, User_Extension__c> userExtMapByUserId = new Map<String, User_Extension__c>();
	//	for(User_Extension__c eachUserExt : userExtMap.values()) {
 //           userExtMapByUserId.put(eachUserExt.User__c, eachUserExt);
 //       }

 //       List<Account> accountUpdateList = new List<Account>();
 //       Bulk_Assignment__c eachAssignment;
	//	for(User_Extension__c eachUserExt : userExtMap.values()) {			
	//		// Account
	//		for(Account eachAccount : eachUserExt.AccountsPermanentOwnerExtension__r) {
	//			eachAssignment = assignMapByCurrentUser.get(eachAccount.Permanent_Owner_Extension__r.User__c);
	//			if(eachAccount.Permanent_Owner_Extension__c != null && 
	//			assignMapByCurrentUser.containsKey(eachAccount.Permanent_Owner_Extension__r.User__c) &&
	//			userExtMapByUserId.containsKey(eachAssignment.AssignmentOwner__c)) {
	//				eachAccount.Permanent_Owner_Extension__c = userExtMapByUserId.get(eachAssignment.AssignmentOwner__c).Id;
	//				// Inactive extension dont find new team set
	//				//eachAccount.Permanent_Team_Name__c = userExtMapByUserId.get(eachAssignment.AssignmentOwner__c).Team_Structure__c;
	//				//eachAccount.Permanent_AH_Name__c = userExtMapByUserId.get(eachAssignment.AssignmentOwner__c).Team_Structure__r.AH_Name__c;
	//				//eachAccount.Permanent_NH_Name__c = userExtMapByUserId.get(eachAssignment.AssignmentOwner__c).Team_Structure__r.NH_Name__c;
	//				accountUpdateList.add(eachAccount);
	//			}
	//		}
	//	}

	//	if(accountUpdateList.size() > 0) 
	//		update accountUpdateList;
	//}

	public static void teamChange(Map<Id, User_Extension__c> userExtMap) {
		List<Opportunity> updateOppList = new List<SObject>();
		List<Call_Report__c> updateCallRepList = new List<Call_Report__c>();
		// Call Report
		List<Call_Report__c> callReportUpdateList = new List<Call_Report__c>();
        callReportUpdateList = [SELECT Id,Current_Owner_Extension__c,Status__c FROM Call_Report__c WHERE Current_Owner_Extension__c IN :userExtMap.keySet()];

        if(UserExtension_Service.allTeamStructureMap == null) {
        	UserExtension_Service.allTeamStructureMap = new Map<Id, Team_Structure__c>([SELECT Id, RC_Code__c, External_Id__c, AH_Name__c, NH_Name__c FROM Team_Structure__c]);
        } 

        if(callReportUpdateList!=null && callReportUpdateList.size() > 0){
            for(Call_Report__c eachCallReport : callReportUpdateList){
                if(userExtMap.containsKey(eachCallReport.Current_Owner_Extension__c) && eachCallReport.Status__c == GlobalConstants.PLAN) {
                    eachCallReport.Current_Team_Name__c = userExtMap.get(eachCallReport.Current_Owner_Extension__c).Team_Structure__c;
                    eachCallReport.Current_AH_Name__c = UserExtension_Service.allTeamStructureMap.get(eachCallReport.Current_Team_Name__c).AH_Name__c;
                    eachCallReport.Current_NH_Name__c = UserExtension_Service.allTeamStructureMap.get(eachCallReport.Current_Team_Name__c).NH_Name__c;
                    updateCallRepList.add(eachCallReport);
                }
            }
        }
        // Opportunity
        List<Opportunity> opportunityUpdateList = new List<Opportunity>();
        opportunityUpdateList = [SELECT Id,Current_Owner_Extension__c,StageName,IsClosed FROM Opportunity WHERE Current_Owner_Extension__c IN :userExtMap.keySet()];    

        if(UserExtension_Service.allTeamStructureMap == null) {
        	UserExtension_Service.allTeamStructureMap = new Map<Id, Team_Structure__c>([SELECT Id, RC_Code__c, External_Id__c, AH_Name__c, NH_Name__c FROM Team_Structure__c]);
        } 

        if(opportunityUpdateList!=null && opportunityUpdateList.size() > 0){
            for(Opportunity eachOpportunity : opportunityUpdateList){
                if(userExtMap.containsKey(eachOpportunity.Current_Owner_Extension__c) && !eachOpportunity.IsClosed && (eachOpportunity.StageName != GlobalConstants.PARTIAL_LOAN_SETUP && eachOpportunity.StageName!=GlobalConstants.ALL_LOAN_SETUP && eachOpportunity.StageName != GlobalConstants.AUTO_CLOSED && eachOpportunity.StageName != GlobalConstants.CLOSE_LOST)){
                    eachOpportunity.Current_Team_Name__c = userExtMap.get(eachOpportunity.Current_Owner_Extension__c).Team_Structure__c;
                    eachOpportunity.Current_AH_Name__c = UserExtension_Service.allTeamStructureMap.get(eachOpportunity.Current_Team_Name__c).AH_Name__c;
                    eachOpportunity.Current_NH_Name__c = UserExtension_Service.allTeamStructureMap.get(eachOpportunity.Current_Team_Name__c).NH_Name__c;
                    updateOppList.add(eachOpportunity);
                }
            }
        }
        TriggerHandler.bypass('OpportunityTriggerHandler');
        TriggerHandler.bypass('CallReportTriggerHandler');
        if(updateCallRepList.size() > 0) update updateCallRepList;
        if(updateOppList.size() > 0) update updateOppList;
        TriggerHandler.clearAllBypasses();
	}
}