objects/Account.object
<CustomObject>
    <fields>
        <fullName>AH_RC_Code__c</fullName>
        <formula>Owner.AH_RC_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AH RC Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_AH_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current AH Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Accounts (Current AH Name)</relationshipLabel>
        <relationshipName>AccountsCurrentAHName</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_NH_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current NH Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Accounts (Current NH Name)</relationshipLabel>
        <relationshipName>AccountsCurrentNHName</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Owner_Extension__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Owner Extension</label>
        <referenceTo>User_Extension__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>AccountsCurrentOwnerExtension</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Team_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Team Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Accounts (Current Team Name)</relationshipLabel>
        <relationshipName>AccountsCurrentTeamName</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NH_RC_Code__c</fullName>
        <formula>Owner.NH_RC_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NH RC Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ownership_Text__c</fullName>
        <label>Ownership</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ownership__c</fullName>
        <formula>CASE(Port_Pool__c, 
&quot;Port&quot;, &quot;Permanent&quot;, 
&quot;Pool&quot;,  CASE(Owner.Profile.Name,
                  &quot;SME-AH&quot;, &quot;Permanent&quot;,
                  &quot;SME-TM&quot;, IF(Temporary_Ownership_Flag__c, &quot;Temporary&quot;, &quot;Permanent&quot;),
                  &quot;SME-RM&quot;, &quot;Temporary&quot;, 
                  &quot;&quot;),                      
&quot;&quot;, IF(OR(Owner.Profile.Name = &quot;SME-RM&quot;,Owner.Profile.Name = &quot;SME-TM&quot;), &quot;Temporary&quot;, &quot;&quot;),
&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Ownership</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Permanent_AH_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Permanent AH Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Accounts (Permanent AH Name)</relationshipLabel>
        <relationshipName>AccountsPermanentAHName</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Permanent_NH_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Permanent NH Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Accounts (Permanent NH Name)</relationshipLabel>
        <relationshipName>AccountsPermanentNHName</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Permanent_Owner_Extension__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Permanent Owner Extension</label>
        <referenceTo>User_Extension__c</referenceTo>
        <relationshipLabel>Accounts (Permanent Owner Extension)</relationshipLabel>
        <relationshipName>AccountsPermanentOwnerExtension</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Permanent_Team_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Permanent Team Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Accounts (Permanent Team Name)</relationshipLabel>
        <relationshipName>AccountsPermanentTeamName</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Previous_AH_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous AH Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Accounts (Previous AH Name)</relationshipLabel>
        <relationshipName>AccountsPreviousAHName</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Previous_NH_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous NH Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Accounts (Previous NH Name)</relationshipLabel>
        <relationshipName>AccountsPreviousNHName</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Previous_Owner_Extension__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Owner Extension</label>
        <referenceTo>User_Extension__c</referenceTo>
        <relationshipLabel>Accounts (Previous Owner Extension)</relationshipLabel>
        <relationshipName>AccountsPreviousOwnerExtension</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Previous_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Previous_Team_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Team Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Accounts (Previous Team Name)</relationshipLabel>
        <relationshipName>AccountsPreviousTeamName</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RC_Code__c</fullName>
        <formula>Owner.RC_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RC Code</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Team_Structure__c.object
<CustomObject>
    <fields>
        <fullName>AH_RC_Code__c</fullName>
        <label>AH RC Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NH_RC_Code__c</fullName>
        <label>NH RC Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RC_Code__c</fullName>
        <label>RC Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Team Structure</label>
    <nameField>
        <label>Team Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Structure</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>AH_RC_Code__c</fullName>
        <label>AH RC Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Employee ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NH_RC_Code__c</fullName>
        <label>NH RC Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RC_Code__c</fullName>
        <label>RC Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/User_Extension__c.object
<CustomObject>
    <description>To store user&apos;s information.</description>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <formula>User__r.Employee_ID__c</formula>
        <label>Employee ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Team_Structure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>User Extension</relationshipLabel>
        <relationshipName>User_Extension</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Extension</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Extension</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Year_End_Assignment__c.object
<CustomObject>
    <description>This object tracks the re-assignment of customer to RM port / TM port or Pool, Refer out at the end of the year</description>
    <fields>
        <fullName>CIS_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CIS ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Assign_Port_Yearly</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Final_Assigned_RM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Final Assigned/SelectedBy</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Year_End_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Year-End Assignment</label>
    <nameField>
        <displayFormat>Ref-{00000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Year-End Assignment</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SME_AccountOwnerInitial_Batch.cls
global class SME_AccountOwnerInitial_Batch implements Database.Batchable<sObject> {
	
	String query;
	private Map<String, Id> teamMapByRc;
	private Map<String, Id> userExtMapByEmpId;

	global SME_AccountOwnerInitial_Batch() {
		this.init();
	}
	
	private void init() {
		teamMapByRc = new Map<String, Id>();
		userExtMapByEmpId = new Map<String, Id>();

		List<Team_Structure__c> teamList = [SELECT Id, External_ID__c FROM Team_Structure__c];
		for(Team_Structure__c eachTeam : teamList) {
			teamMapByRc.put(eachTeam.External_ID__c, eachTeam.Id);
		}

		List<User_Extension__c> userExtList = [SELECT Id, External_ID__c FROM User_Extension__c];
		for(User_Extension__c eachUserExt : userExtList) {
			userExtMapByEmpId.put(eachUserExt.External_ID__c, eachUserExt.Id);
		}

		this.query = 'SELECT Id, Ownership__c, Owner.Employee_ID__c, Owner.RC_Code__c, Owner.AH_RC_Code__c, Owner.NH_RC_Code__c, Previous_Owner__c, Previous_Owner__r.Employee_ID__c, Previous_Owner__r.RC_Code__c, Previous_Owner__r.AH_RC_Code__c, Previous_Owner__r.NH_RC_Code__c FROM Account';
	}

	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<Account> accountList) {
   		Set<Id> accountIds = new Set<Id>();
   		for(Account eachAccount : accountList) {
   			accountIds.add(eachAccount.Id);
   		}
   		List<Year_End_Assignment__c> yearEndList = [SELECT Id, CIS_ID__c, Final_Assigned_RM__c, Final_Assigned_RM__r.Employee_ID__c, Final_Assigned_RM__r.RC_Code__c, Final_Assigned_RM__r.AH_RC_Code__c, Final_Assigned_RM__r.NH_RC_Code__c FROM Year_End_Assignment__c WHERE CIS_ID__c IN :accountIds];
   		Map<Id, Year_End_Assignment__c> yearEndMapByCIS = new Map<Id, Year_End_Assignment__c>();
   		for(Year_End_Assignment__c eachYearEnd : yearEndList) {
   			if(eachYearEnd.CIS_ID__c != null && eachYearEnd.Final_Assigned_RM__c != null)
   				yearEndMapByCIS.put(eachYearEnd.CIS_ID__c, eachYearEnd);
   		}

   		Year_End_Assignment__c tempYearEnd;
		for(Account eachAccount : accountList) {
			if(yearEndMapByCIS.containsKey(eachAccount.Id)) {
				tempYearEnd = yearEndMapByCIS.get(eachAccount.Id);
			}

			if(eachAccount.Ownership__c != null && eachAccount.Ownership__c == GlobalConstants.OWNERSHIP_PERMANENT) {
				eachAccount.Permanent_Owner_Extension__c = userExtMapByEmpId.get(eachAccount.Owner.Employee_ID__c);
				eachAccount.Permanent_AH_Name__c = teamMapByRc.get(eachAccount.Owner.AH_RC_Code__c);
				eachAccount.Permanent_NH_Name__c = teamMapByRc.get(eachAccount.Owner.NH_RC_Code__c);
				eachAccount.Permanent_Team_Name__c = teamMapByRc.get(eachAccount.Owner.RC_Code__c);
			} else {
				eachAccount.Permanent_Owner_Extension__c = (tempYearEnd != null) ? userExtMapByEmpId.get(tempYearEnd.Final_Assigned_RM__r.Employee_ID__c) : userExtMapByEmpId.get(eachAccount.Previous_Owner__r.Employee_ID__c);
				eachAccount.Permanent_AH_Name__c = (tempYearEnd != null) ? teamMapByRc.get(tempYearEnd.Final_Assigned_RM__r.AH_RC_Code__c) : teamMapByRc.get(eachAccount.Previous_Owner__r.AH_RC_Code__c);
				eachAccount.Permanent_NH_Name__c = (tempYearEnd != null) ? teamMapByRc.get(tempYearEnd.Final_Assigned_RM__r.NH_RC_Code__c) : teamMapByRc.get(eachAccount.Previous_Owner__r.NH_RC_Code__c);
				eachAccount.Permanent_Team_Name__c = (tempYearEnd != null) ? teamMapByRc.get(tempYearEnd.Final_Assigned_RM__r.RC_Code__c) : teamMapByRc.get(eachAccount.Previous_Owner__r.RC_Code__c);
			}
			
			eachAccount.Ownership_Text__c = eachAccount.Ownership__c;

			eachAccount.Previous_Owner_Extension__c = userExtMapByEmpId.get(eachAccount.Previous_Owner__r.Employee_ID__c);
			eachAccount.Previous_AH_Name__c = teamMapByRc.get(eachAccount.Previous_Owner__r.AH_RC_Code__c);
			eachAccount.Previous_NH_Name__c = teamMapByRc.get(eachAccount.Previous_Owner__r.NH_RC_Code__c);
			eachAccount.Previous_Team_Name__c = teamMapByRc.get(eachAccount.Previous_Owner__r.RC_Code__c);

			eachAccount.Current_Owner_Extension__c = userExtMapByEmpId.get(eachAccount.Owner.Employee_ID__c);
			eachAccount.Current_AH_Name__c = teamMapByRc.get(eachAccount.Owner.AH_RC_Code__c);
			eachAccount.Current_NH_Name__c = teamMapByRc.get(eachAccount.Owner.NH_RC_Code__c);
			eachAccount.Current_Team_Name__c = teamMapByRc.get(eachAccount.Owner.RC_Code__c);
		}

		update accountList;
	}
	
	global void finish(Database.BatchableContext BC) {
		
	}
	
}