objects/Account.object
<CustomObject>
    <fields>
        <fullName>AH_RC_Code__c</fullName>
        <formula>Owner.AH_RC_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AH RC Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_AH_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current AH Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Accounts (Current AH Name)</relationshipLabel>
        <relationshipName>AccountsCurrentAHName</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_NH_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current NH Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Accounts (Current NH Name)</relationshipLabel>
        <relationshipName>AccountsCurrentNHName</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Owner_Extension__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Owner Extension</label>
        <referenceTo>User_Extension__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>AccountsCurrentOwnerExtension</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Team_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Team Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Accounts (Current Team Name)</relationshipLabel>
        <relationshipName>AccountsCurrentTeamName</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NH_RC_Code__c</fullName>
        <formula>Owner.NH_RC_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NH RC Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner_Emp_ID__c</fullName>
        <formula>Owner.Employee_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owner Emp ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ownership_Text__c</fullName>
        <label>Ownership</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ownership__c</fullName>
        <formula>CASE(Port_Pool__c, 
&quot;Port&quot;, &quot;Permanent&quot;, 
&quot;Pool&quot;,  CASE(Owner.Profile.Name,
                  &quot;SME-AH&quot;, &quot;Permanent&quot;,
                  &quot;SME-TM&quot;, IF(Temporary_Ownership_Flag__c, &quot;Temporary&quot;, &quot;Permanent&quot;),
                  &quot;SME-RM&quot;, &quot;Temporary&quot;, 
                  &quot;&quot;),                      
&quot;&quot;, IF(OR(Owner.Profile.Name = &quot;SME-RM&quot;,Owner.Profile.Name = &quot;SME-TM&quot;), &quot;Temporary&quot;, &quot;&quot;),
&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Ownership</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Port_Pool__c</fullName>
        <label>Port / Pool</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RC_Code__c</fullName>
        <formula>Owner.RC_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RC Code</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Call_Report__c.object
<CustomObject>
    <description>This object tracks the Call Plan and Call Report</description>
    <fields>
        <fullName>CIS_ID__c</fullName>
        <label>CIS ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call Plans / Call Reports</relationshipLabel>
        <relationshipName>Call_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Current_AH_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AH Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Call Plans / Call Reports (Current AH Name)</relationshipLabel>
        <relationshipName>Call_Plans_Call_Reports4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_NH_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NH Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Call Plans / Call Reports (Current NH Name)</relationshipLabel>
        <relationshipName>Call_Plans_Call_Reports5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Owner_Extension__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner Extension</label>
        <referenceTo>User_Extension__c</referenceTo>
        <relationshipLabel>Call Plans / Call Reports</relationshipLabel>
        <relationshipName>Call_Plans_Call_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Team_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Call Plans / Call Reports (Current Team Name)</relationshipLabel>
        <relationshipName>Call_Plans_Call_Reports3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ownership__c</fullName>
        <label>Ownership</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Port_Pool__c</fullName>
        <label>Port / Pool</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Call Plan / Call Report</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Call Plan / Call Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Plans / Call Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Team_Structure__c.object
<CustomObject>
    <fields>
        <fullName>AH_RC_Code__c</fullName>
        <label>AH RC Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Call_Report__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Call Report</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NH_RC_Code__c</fullName>
        <label>NH RC Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RC_Code__c</fullName>
        <label>RC Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Team Structure</label>
    <nameField>
        <label>Team Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Structure</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User_Extension__c.object
<CustomObject>
    <description>To store user&apos;s information.</description>
    <fields>
        <fullName>Call_Report__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Call Report</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Team_Structure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>User Extension</relationshipLabel>
        <relationshipName>User_Extension</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Extension</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Extension</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SME_CallReportOwnerInitial_Batch.cls
global class SME_CallReportOwnerInitial_Batch implements Database.Batchable<sObject>, Database.Stateful {
	
	String query;
	private Map<String, Id> teamMapByRc;
	private Map<String, Id> userExtMapByEmpId;
	
	global SME_CallReportOwnerInitial_Batch() {
		this.init();
	}

	private void init() {
		teamMapByRc = new Map<String, Id>();
		userExtMapByEmpId = new Map<String, Id>();

		List<Team_Structure__c> teamList = [SELECT Id, External_ID__c FROM Team_Structure__c];
		for(Team_Structure__c eachTeam : teamList) {
			teamMapByRc.put(eachTeam.External_ID__c, eachTeam.Id);
		}

		List<User_Extension__c> userExtList = [SELECT Id, External_ID__c FROM User_Extension__c];
		for(User_Extension__c eachUserExt : userExtList) {
			userExtMapByEmpId.put(eachUserExt.External_ID__c, eachUserExt.Id);
		}

		this.query = 'SELECT Id, CIS_ID__c FROM Call_Report__c';
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<Call_Report__c> callReportList) {
		Map<Id, Id> accountMapByCallRepId = new Map<Id, Id>();
		for(Call_Report__c eachCallReport : callReportList) {
			accountMapByCallRepId.put(eachCallReport.Id, eachCallReport.CIS_ID__c);
		}

		Map<Id, Account> accountMap = new Map<Id, Account>([SELECT Id, Ownership_Text__c, Port_Pool__c, Owner_Emp_ID__c, RC_Code__c, AH_RC_Code__c, NH_RC_Code__c  FROM Account WHERE Id IN:accountMapByCallRepId.values()]);

		Account tempAccount;
		for(Call_Report__c eachCall : callReportList) {
			if(accountMap.containsKey(accountMapByCallRepId.get(eachCall.Id))) {
				tempAccount = accountMap.get(accountMapByCallRepId.get(eachCall.Id));

				if(teamMapByRc.containsKey(tempAccount.RC_Code__c)) 
					eachCall.Current_Team_Name__c = teamMapByRc.get(tempAccount.RC_Code__c);
				if(teamMapByRc.containsKey(tempAccount.AH_RC_Code__c)) 
					eachCall.Current_AH_Name__c = teamMapByRc.get(tempAccount.AH_RC_Code__c);
				if(teamMapByRc.containsKey(tempAccount.NH_RC_Code__c)) 
					eachCall.Current_NH_Name__c = teamMapByRc.get(tempAccount.NH_RC_Code__c);
				if(userExtMapByEmpId.containsKey(tempAccount.Owner_Emp_ID__c))
					eachCall.Current_Owner_Extension__c = userExtMapByEmpId.get(tempAccount.Owner_Emp_ID__c);

				eachCall.Port_Pool__c = tempAccount.Port_Pool__c;
				eachCall.Ownership__c = tempAccount.Ownership_Text__c;
			}
		}
		TriggerHandler.bypass('CallReportTriggerHandler');
		update callReportList;

	}
	
	global void finish(Database.BatchableContext BC) {
		
	}
	
}