objects/Account.object
<CustomObject>
    <fields>
        <fullName>Delete_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Delete Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Credit Status</label>
        <picklist>
            <picklistValues>
                <fullName>Good Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>SME_Customer</fullName>
        <active>true</active>
        <label>SME-Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Call_Report__c.object
<CustomObject>
    <description>This object tracks the Call Plan and Call Report</description>
    <fields>
        <fullName>CIS_ID__c</fullName>
        <label>CIS ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call Plans / Call Reports</relationshipLabel>
        <relationshipName>Call_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Firstname__c</fullName>
        <inlineHelpText>สำหรับสร้างบุคคลผู้ติดต่อใหม่</inlineHelpText>
        <label>Contact Firstname</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Lastname__c</fullName>
        <inlineHelpText>สำหรับสร้างบุคคลผู้ติดต่อใหม่</inlineHelpText>
        <label>Contact Lastname</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Phone__c</fullName>
        <inlineHelpText>สำหรับสร้างบุคคลผู้ติดต่อใหม่</inlineHelpText>
        <label>Contact Phone</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Date__c</fullName>
        <label>Plan Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Primary_Call_Report__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Primary Call Report</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Call Plan / Call Report</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Call Plan / Call Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Plans / Call Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is updated by DIH (HRIS): A = Active, I=Inactive</description>
        <label>Status Code</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/SME_CallReport_Initial_Batch_Test.cls
@isTest
private class SME_CallReport_Initial_Batch_Test {
	public static String accountNameRM = 'rmCreatedAccountName';
	@testSetup static void setupAccount(){
		Mockup_Test mt = new Mockup_Test().setUpTest();

        System.runAs([SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameRM LIMIT 1][0]){
            mt.newAccount(accountNameRM,GlobalConstants.POOL,Mockup_Test.getRecordTypeAccountIdByName(GlobalConstants.SME_CUSTOMER));
        }
	}
    static testMethod void testMethod1() {
		Account targetAccount = [SELECT Id,Delete_Flag__c FROM Account WHERE Name = :CallReport_Test.accountNameRM LIMIT 1];
		User userRM = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameRM LIMIT 1];
		Call_Report__c callreportObj;
		System.runAs(userRM){
			
			callreportObj = new Call_Report__c(
				Contact_Firstname__c = 'abc',
				Contact_Lastname__c = 'def',
				Contact_Phone__c = '123456789',
				CIS_ID__c = targetAccount.Id,
				Status__c = GlobalConstants.PLAN,
				Plan_Date__c = System.Today(),
				Primary_Call_Report__c = false
			);
			insert callreportObj;
		}
		Call_Report__c finalcallreport = [select id,Primary_Call_Report__c from call_report__c where id=:callreportObj.Id limit 1];
		system.assertEquals(false,finalcallreport.Primary_Call_Report__c);
		Test.startTest();
        	Database.executeBatch(new SME_CallReport_Initial_Batch());
        Test.stopTest();
        finalcallreport = [select id,Primary_Call_Report__c from call_report__c where id=:callreportObj.Id limit 1];
		system.assertEquals(true,finalcallreport.Primary_Call_Report__c);
    }
}