objects/Account.object
<CustomObject>
    <fields>
        <fullName>AH_Name__c</fullName>
        <formula>Owner.AH_Name__c</formula>
        <label>AH Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RC_Code__c</fullName>
        <formula>Owner.RC_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RC Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <formula>CASE( Primary_Segment_Code__c,
&quot;UM&quot;, IMAGE(&quot;/resource/SMESegment&quot;,&quot;SME&quot;),
&quot;UR&quot;, IMAGE(&quot;/resource/SMESegment&quot;,&quot;SME&quot;),
&quot;SM&quot;, IMAGE(&quot;/resource/SMESegment&quot;,&quot;SME&quot;),
&quot;SR&quot;, IMAGE(&quot;/resource/SMESegment&quot;,&quot;SME&quot;),
&quot;LM&quot;, IMAGE(&quot;/resource/SMESegment&quot;,&quot;SME&quot;),
&quot;LR&quot;, IMAGE(&quot;/resource/SMESegment&quot;,&quot;SME&quot;),
IMAGE(&quot;/resource/Non_SME_Segment&quot;,&quot;Non-SME&quot;,60,90))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Segment</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>SME_Customer</fullName>
        <active>true</active>
        <label>SME-Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Customer_Ownership_Request__c.object
<CustomObject>
    <description>This object tracks the on-going request for customer assignment via salesforce approval process</description>
    <fields>
        <fullName>AH_Name__c</fullName>
        <formula>Year_End_Assignment__r.AH_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AH Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CIS_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CIS ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Ownership Requests</relationshipLabel>
        <relationshipName>Customer_Ownership_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Refer_Out_Province__c</fullName>
        <label>Refer Out Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Refer_Out_Reason__c</fullName>
        <label>Refer Out Reason</label>
        <picklist>
            <controllingField>Request_Type__c</controllingField>
            <picklistValues>
                <fullName>TM Pool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wrong Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMLO List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exit Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Criminal Offense</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not SME Segment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Refer_Out_Segment__c</fullName>
        <label>Refer Out Segment</label>
        <picklist>
            <controllingField>Refer_Out_Reason__c</controllingField>
            <picklistValues>
                <fullName>CB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XS</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Refer_Out_Team__c</fullName>
        <label>Refer Out Team</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Customer Ownership Request</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Ownership Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Team_Province_Master_Data__c.object
<CustomObject>
    <fields>
        <fullName>Province_Name__c</fullName>
        <label>Province Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <picklist>
            <picklistValues>
                <fullName>SE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Team_Structure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Structure</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Team Province Master Datas</relationshipLabel>
        <relationshipName>Team_Province_Master_Datas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team Province Master Data</label>
    <nameField>
        <displayFormat>TPM-{000000}</displayFormat>
        <label>Team Province Master Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Province Master Datas</pluralLabel>
    <recordTypes>
        <fullName>On_Going</fullName>
        <active>true</active>
        <label>On-Going</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Team_Structure__c.object
<CustomObject>
    <fields>
        <fullName>AH_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AH Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Team Structure</relationshipLabel>
        <relationshipName>Team_Structure</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RC_Code__c</fullName>
        <label>RC Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <picklist>
            <picklistValues>
                <fullName>Small</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Team Structure</label>
    <nameField>
        <label>Team Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Structure</pluralLabel>
    <recordTypes>
        <fullName>Team</fullName>
        <active>true</active>
        <label>Team</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>AH_Name__c</fullName>
        <label>AH Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RC_Code__c</fullName>
        <label>RC Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Account_ReferOutInformation_Test.cls
@isTest
private class Account_ReferOutInformation_Test {
	public static String accountName = 'referOutCreatedAccountName';
	public static String contactName = 'referOutCreatedContactName';
	public static String lastName = 'referOutCreatedLastName';
	public static String accountNameReq = 'accountNameReq';
	@testSetup static void setupUser(){
        Mockup_Test mt = new Mockup_Test().setUpTestWithRCCode();
        System.runAs([SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameRM LIMIT 1][0]){
            mt.newAccount(accountName,GlobalConstants.PORT,GlobalConstants.OWNERSHIP_PERMANENT,Mockup_Test.getRecordTypeAccountIdByName(GlobalConstants.SME_CUSTOMER));
        }
    }

	@isTest static void testInitNewData() {
		Boolean expectedInitailDisabledFlag = true;
		String expectedInitailProvince = ' - ';
		String expectedInitailTeam = ' - ';
		Customer_Ownership_Request__c cusOwnershipReq = new Customer_Ownership_Request__c();
        Account_ReferOutInformation_Controller accountReferOutController = new Account_ReferOutInformation_Controller(new ApexPages.StandardController(cusOwnershipReq));
        System.assertEquals(expectedInitailDisabledFlag,accountReferOutController.disabledFlag);
        System.assertEquals(expectedInitailProvince,accountReferOutController.selectedProvince);
        System.assertEquals(expectedInitailTeam,accountReferOutController.selectedTeam);
	}

	@isTest static void testInitEditData() {
		Account targetAccount = [SELECT Id FROM Account WHERE Name = :accountName LIMIT 1];
        Boolean expectedInitailDisabledFlag = true;
		String expectedInitailProvince = ' - ';
		String expectedInitailTeam = ' - ';
		String expectedId;
		Customer_Ownership_Request__c cusOwnershipReq = new Customer_Ownership_Request__c(CIS_ID__c = targetAccount.id);
		insert cusOwnershipReq;
        expectedId = cusOwnershipReq.id;
        ApexPages.currentPage().getParameters().put('cisID', cusOwnershipReq.Id);
        Account_ReferOutInformation_Controller accountReferOutController = new Account_ReferOutInformation_Controller(new ApexPages.StandardController(cusOwnershipReq));

        System.assertEquals(expectedInitailDisabledFlag,accountReferOutController.disabledFlag);
        System.assertEquals(expectedInitailProvince,accountReferOutController.selectedProvince);
        System.assertEquals(expectedInitailTeam,accountReferOutController.selectedTeam);
        System.assertEquals(expectedId,accountReferOutController.mysObject.CIS_ID__c);
	}
	
	@isTest static void testCheckReasonConditionReasonOtherTeam() {
		Account targetAccount = [SELECT Id FROM Account WHERE Name = :accountName LIMIT 1];
        Boolean expectedDisabledFlag = false;
		Customer_Ownership_Request__c cusOwnershipReq = new Customer_Ownership_Request__c(CIS_ID__c = targetAccount.id,Refer_Out_Reason__c = GlobalConstants.REASON_OTHER_TEAM,Refer_Out_Segment__c = 'ME',Refer_Out_Team__c = 'testTeam');
		insert cusOwnershipReq;
        Account_ReferOutInformation_Controller accountReferOutController = new Account_ReferOutInformation_Controller(new ApexPages.StandardController(cusOwnershipReq));
		accountReferOutController.checkReasonCondition();
        System.assertEquals(expectedDisabledFlag,accountReferOutController.disabledFlag);
	}

	@isTest static void testCheckReasonConditionReasonNotOtherTeamOrWrongArea() {
		Account targetAccount = [SELECT Id FROM Account WHERE Name = :accountName LIMIT 1];
        Boolean expectedDisabledFlag = true;
		Customer_Ownership_Request__c cusOwnershipReq = new Customer_Ownership_Request__c(CIS_ID__c = targetAccount.id,Refer_Out_Reason__c = 'test',Refer_Out_Segment__c = 'ME',Refer_Out_Team__c = 'testTeam');
		insert cusOwnershipReq;
        Account_ReferOutInformation_Controller accountReferOutController = new Account_ReferOutInformation_Controller(new ApexPages.StandardController(cusOwnershipReq));
		accountReferOutController.checkReasonCondition();
        System.assertEquals(expectedDisabledFlag,accountReferOutController.disabledFlag);
	}
	
	@isTest static void testCheckSegmentConditionSelectedReferOutSegment() {
		Account targetAccount = [SELECT Id FROM Account WHERE Name = :accountName LIMIT 1];
        Boolean expectedDisabledFlag = false;
		Customer_Ownership_Request__c cusOwnershipReqReasonOther = new Customer_Ownership_Request__c(CIS_ID__c = targetAccount.id,Refer_Out_Reason__c = 'testReason',Refer_Out_Segment__c = 'ME',Refer_Out_Team__c = 'testTeam');
        Account_ReferOutInformation_Controller accountReferOutController = new Account_ReferOutInformation_Controller(new ApexPages.StandardController(cusOwnershipReqReasonOther));
        accountReferOutController.checkSegmentCondition();
        System.assertEquals(expectedDisabledFlag,accountReferOutController.disabledFlag);
	}

	@isTest static void testCheckSegmentConditionNotSelectedReferOutSegment() {
		Account targetAccount = [SELECT Id FROM Account WHERE Name = :accountName LIMIT 1];
        Boolean expectedDisabledFlag = true;
		String expectedProvince = ' - ';
		String expectedTeam = ' - ';
		Customer_Ownership_Request__c cusOwnershipReqReasonOther = new Customer_Ownership_Request__c(CIS_ID__c = targetAccount.id,Refer_Out_Reason__c = 'testReason',Refer_Out_Segment__c = '-',Refer_Out_Team__c = 'testTeam');
        Account_ReferOutInformation_Controller accountReferOutController = new Account_ReferOutInformation_Controller(new ApexPages.StandardController(cusOwnershipReqReasonOther));
        accountReferOutController.checkSegmentCondition();
        System.assertEquals(expectedDisabledFlag,accountReferOutController.disabledFlag);
        System.assertEquals(expectedProvince,accountReferOutController.selectedProvince);
        System.assertEquals(expectedTeam,accountReferOutController.selectedTeam);
	}
	
	@isTest static void testGetSelectedProvince() {
		Account targetAccount = [SELECT Id FROM Account WHERE Name = :accountName LIMIT 1];
        String expectedSelectedProvince = 'testReferProvince';
		Customer_Ownership_Request__c cusOwnershipReqReasonOther = new Customer_Ownership_Request__c(CIS_ID__c = targetAccount.id,Refer_Out_Reason__c = 'testReason',Refer_Out_Segment__c = 'testSegment',Refer_Out_Team__c = 'testTeam', Refer_Out_Province__c = expectedSelectedProvince);
        Account_ReferOutInformation_Controller accountReferOutController = new Account_ReferOutInformation_Controller(new ApexPages.StandardController(cusOwnershipReqReasonOther));
        accountReferOutController.selectedProvince = null; 
        System.assertEquals(expectedSelectedProvince,accountReferOutController.getSelectedProvince());

	}

	@isTest static void testGetSelectedProvinceNone() {
		Account targetAccount = [SELECT Id FROM Account WHERE Name = :accountName LIMIT 1];
        String expectedSelectedProvince = ' - ';
		Customer_Ownership_Request__c cusOwnershipReqReasonOther = new Customer_Ownership_Request__c(CIS_ID__c = targetAccount.id,Refer_Out_Reason__c = 'testReason',Refer_Out_Segment__c = 'testSegment',Refer_Out_Team__c = 'testTeam');
        Account_ReferOutInformation_Controller accountReferOutController = new Account_ReferOutInformation_Controller(new ApexPages.StandardController(cusOwnershipReqReasonOther));
        
        System.assertEquals(expectedSelectedProvince,accountReferOutController.getSelectedProvince());

	}

	@isTest static void testGetProvinceListNotFound() {
		Account targetAccount = [SELECT Id FROM Account WHERE Name = :accountName LIMIT 1];
		Customer_Ownership_Request__c cusOwnershipReqReasonOther = new Customer_Ownership_Request__c(CIS_ID__c = targetAccount.id,Refer_Out_Reason__c = 'testReason',Refer_Out_Segment__c = 'testSegment',Refer_Out_Team__c = 'testTeam');
        Account_ReferOutInformation_Controller accountReferOutController = new Account_ReferOutInformation_Controller(new ApexPages.StandardController(cusOwnershipReqReasonOther));
        accountReferOutController.getProvinceList();
        System.assertEquals(1,accountReferOutController.provinceList.size());
        System.assertEquals(0,accountReferOutController.teamList.size());
	}

	@isTest static void testGetProvinceList() {
		Account targetAccount = [SELECT Id FROM Account WHERE Name = :accountName LIMIT 1];
		Id ON_GOING_RECORD_TYPE_ID = GlobalUtility.getRecordTypeIdFromSObjectByDevName('Team_Province_Master_Data__c', 'On_Going');
		Customer_Ownership_Request__c cusOwnershipReqReasonOther = new Customer_Ownership_Request__c(CIS_ID__c = targetAccount.id,Refer_Out_Reason__c = GlobalConstants.REASON_WRONG_AREA,Refer_Out_Segment__c = 'ME',Refer_Out_Team__c = 'testTeam');
        Account_ReferOutInformation_Controller accountReferOutController = new Account_ReferOutInformation_Controller(new ApexPages.StandardController(cusOwnershipReqReasonOther));
        List<Team_Structure__c> listTeamStructure = [SELECT Id FROM Team_Structure__c];
        List<Team_Province_Master_Data__c> listTeamProvinceMasterData = new  List<Team_Province_Master_Data__c>();
		listTeamProvinceMasterData.add(new Team_Province_Master_Data__c(Province_Name__c = 'province 1',RecordTypeId = ON_GOING_RECORD_TYPE_ID,Segment__c = 'ME',Team_Structure__c = listTeamStructure[0].Id));
		listTeamProvinceMasterData.add(new Team_Province_Master_Data__c(Province_Name__c = 'province 2',RecordTypeId = ON_GOING_RECORD_TYPE_ID,Segment__c = 'ME',Team_Structure__c = listTeamStructure[1].Id));
		insert listTeamProvinceMasterData;

        accountReferOutController.getProvinceList();
        System.assertNotEquals(1,accountReferOutController.provinceList.size());
        System.assertNotEquals(0,accountReferOutController.teamList.size());
	}
	
	@isTest static void testSelectProvinceThenSelectTeamME() {
		Account targetAccount = [SELECT Id FROM Account WHERE Name = :accountName LIMIT 1];
		Id ON_GOING_RECORD_TYPE_ID = GlobalUtility.getRecordTypeIdFromSObjectByDevName('Team_Province_Master_Data__c', 'On_Going');
		Customer_Ownership_Request__c cusOwnershipReqReasonOther = new Customer_Ownership_Request__c(CIS_ID__c = targetAccount.id,Refer_Out_Reason__c = GlobalConstants.REASON_WRONG_AREA,Refer_Out_Segment__c = 'ME',Refer_Out_Team__c = 'testTeam');
        Account_ReferOutInformation_Controller accountReferOutController = new Account_ReferOutInformation_Controller(new ApexPages.StandardController(cusOwnershipReqReasonOther));
        List<Team_Structure__c> listTeamStructure = [SELECT Id FROM Team_Structure__c];

		Team_Structure__c ts1 = new Team_Structure__c(
			AH_Name__c = null,
			RC_Code__c = Mockup_Test.NH_RC_CODE,
			Name = System.Label.Filter_ME_Team + ' team 1',
			External_ID__c = '1'
		);
		insert ts1;

		Team_Structure__c ts2 = new Team_Structure__c(
			AH_Name__c = null,
			RC_Code__c = Mockup_Test.NH_RC_CODE,
			Name = System.Label.Filter_ME_Team + ' team 2',
			External_ID__c = '2'
		);
		insert ts2;

        List<Team_Province_Master_Data__c> listTeamProvinceMasterData = new  List<Team_Province_Master_Data__c>();
		listTeamProvinceMasterData.add(new Team_Province_Master_Data__c(Province_Name__c = 'province 1',RecordTypeId = ON_GOING_RECORD_TYPE_ID,Segment__c = 'ME',Team_Structure__c = listTeamStructure[0].Id));
		listTeamProvinceMasterData.add(new Team_Province_Master_Data__c(Province_Name__c = 'province 2',RecordTypeId = ON_GOING_RECORD_TYPE_ID,Segment__c = 'ME',Team_Structure__c = listTeamStructure[1].Id));
		listTeamProvinceMasterData.add(new Team_Province_Master_Data__c(Province_Name__c = 'province 3',RecordTypeId = ON_GOING_RECORD_TYPE_ID,Segment__c = 'ME',Team_Structure__c = ts1.Id));
		listTeamProvinceMasterData.add(new Team_Province_Master_Data__c(Province_Name__c = 'province 4',RecordTypeId = ON_GOING_RECORD_TYPE_ID,Segment__c = 'ME',Team_Structure__c = ts2.Id));
		insert listTeamProvinceMasterData;

        accountReferOutController.selectProvince();
        System.assertEquals(3,accountReferOutController.teamList.size());
	}

	@isTest static void testSelectProvinceThenSelectTeamSE() {
		Account targetAccount = [SELECT Id FROM Account WHERE Name = :accountName LIMIT 1];
		Id ON_GOING_RECORD_TYPE_ID = GlobalUtility.getRecordTypeIdFromSObjectByDevName('Team_Province_Master_Data__c', 'On_Going');
		Customer_Ownership_Request__c cusOwnershipReqReasonOther = new Customer_Ownership_Request__c(CIS_ID__c = targetAccount.id,Refer_Out_Reason__c = GlobalConstants.REASON_WRONG_AREA,Refer_Out_Segment__c = 'SE',Refer_Out_Team__c = 'testTeam');
        Account_ReferOutInformation_Controller accountReferOutController = new Account_ReferOutInformation_Controller(new ApexPages.StandardController(cusOwnershipReqReasonOther));
        List<Team_Structure__c> listTeamStructure = [SELECT Id FROM Team_Structure__c];

		Team_Structure__c ts1 = new Team_Structure__c(
			AH_Name__c = null,
			RC_Code__c = Mockup_Test.NH_RC_CODE,
			Name = System.Label.Filter_SE_Team + ' team 1',
			External_ID__c = '1'
		);
		insert ts1;

		Team_Structure__c ts2 = new Team_Structure__c(
			AH_Name__c = null,
			RC_Code__c = Mockup_Test.NH_RC_CODE,
			Name = System.Label.Filter_SE_Team + ' team 2',
			External_ID__c = '2'
		);
		insert ts2;

        List<Team_Province_Master_Data__c> listTeamProvinceMasterData = new  List<Team_Province_Master_Data__c>();
		listTeamProvinceMasterData.add(new Team_Province_Master_Data__c(Province_Name__c = 'province 1',RecordTypeId = ON_GOING_RECORD_TYPE_ID,Segment__c = 'SE',Team_Structure__c = listTeamStructure[0].Id));
		listTeamProvinceMasterData.add(new Team_Province_Master_Data__c(Province_Name__c = 'province 2',RecordTypeId = ON_GOING_RECORD_TYPE_ID,Segment__c = 'SE',Team_Structure__c = listTeamStructure[1].Id));
		listTeamProvinceMasterData.add(new Team_Province_Master_Data__c(Province_Name__c = 'province 3',RecordTypeId = ON_GOING_RECORD_TYPE_ID,Segment__c = 'SE',Team_Structure__c = ts1.Id));
		listTeamProvinceMasterData.add(new Team_Province_Master_Data__c(Province_Name__c = 'province 4',RecordTypeId = ON_GOING_RECORD_TYPE_ID,Segment__c = 'SE',Team_Structure__c = ts2.Id));
		insert listTeamProvinceMasterData;

        accountReferOutController.selectProvince();
        System.assertEquals(3,accountReferOutController.teamList.size());
	}

	@isTest static void testIfBlockTeamThenNotSave() {
		Account targetAccount = [SELECT Id FROM Account WHERE Name = :accountName LIMIT 1];
		Id ON_GOING_RECORD_TYPE_ID = GlobalUtility.getRecordTypeIdFromSObjectByDevName('Team_Province_Master_Data__c', 'On_Going');
		Customer_Ownership_Request__c cusOwnershipReqReasonOther = new Customer_Ownership_Request__c(CIS_ID__c = targetAccount.id,Refer_Out_Reason__c = GlobalConstants.REASON_WRONG_AREA,Refer_Out_Segment__c = 'SE',Refer_Out_Team__c = System.Label.Filter_SE_Team + ' team 1');
        Account_ReferOutInformation_Controller accountReferOutController = new Account_ReferOutInformation_Controller(new ApexPages.StandardController(cusOwnershipReqReasonOther));
        
        Team_Structure__c ts1 = new Team_Structure__c(
			AH_Name__c = null,
			RC_Code__c = Mockup_Test.NH_RC_CODE,
			Name = System.Label.Filter_SE_Team + ' team 1',
			External_ID__c = '99999'
		);
		insert ts1;

        PageReference result = accountReferOutController.save();
        System.assertEquals(null,result);
	}

	@isTest static void testSave() {
		Account targetAccount = [SELECT Id FROM Account WHERE Name = :accountName LIMIT 1];
		Id ON_GOING_RECORD_TYPE_ID = GlobalUtility.getRecordTypeIdFromSObjectByDevName('Team_Province_Master_Data__c', 'On_Going');
		Customer_Ownership_Request__c cusOwnershipReqReasonOther = new Customer_Ownership_Request__c(CIS_ID__c = targetAccount.id,Refer_Out_Reason__c = 'test other reason',Refer_Out_Segment__c = 'SE',Refer_Out_Team__c = System.Label.Filter_SE_Team + ' team 1');
        Account_ReferOutInformation_Controller accountReferOutController = new Account_ReferOutInformation_Controller(new ApexPages.StandardController(cusOwnershipReqReasonOther));
       
        Team_Structure__c ts1 = new Team_Structure__c(
			AH_Name__c = null,
			RC_Code__c = Mockup_Test.NH_RC_CODE,
			Name = System.Label.Filter_SE_Team + ' team 1',
			External_ID__c = '1'
		);
		insert ts1;

		Team_Structure__c ts2 = new Team_Structure__c(
			AH_Name__c = null,
			RC_Code__c = Mockup_Test.NH_RC_CODE,
			Name = 'Blocked team',
			External_ID__c = '99999'
		);
		insert ts2;

		Test.startTest();
			System.runAs([SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameRM LIMIT 1][0]){
        		accountReferOutController.save();
        	}
        Test.stopTest();
        List<Customer_Ownership_Request__c> result = [SELECT Id FROM Customer_Ownership_Request__c];
        System.assertEquals(1,result.size());
	}

}