objects/Account.object
<CustomObject>
    <fields>
        <fullName>Lead_To_Do__c</fullName>
        <label>Lead To Do</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Lead_To_Inform__c</fullName>
        <label>Campaign/Event</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Lead_for_Sales__c</fullName>
        <label>Lead for Sales</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Credit Status</label>
        <picklist>
            <picklistValues>
                <fullName>Good Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Target_List__c.object
<CustomObject>
    <description>This object tracks the list of Targeted Lead and Campaign Member list</description>
    <fields>
        <fullName>CIS_ID_Prospect_Name__c</fullName>
        <label>CIS ID / Prospect Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Campaign_Members_Leads</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Lead_Campaign__c</fullName>
        <label>Lead/Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Target Lists</relationshipLabel>
        <relationshipName>Campaign_Members_Leads</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Lead_To_Inform__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lead To Inform</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead_Type__c</fullName>
        <formula>TEXT( Lead_Campaign__r.Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lead Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Done</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Interested This Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>App In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interested but not register</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stock Negotiation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Create Write Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Credit Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case is Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Credit Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial Loan Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Loan Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Target List</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AccountLeadUpdate_Batch.cls
/**
* @author chutiwat.s@beryl8.com
* @26/01/2015 update
*/
global class AccountLeadUpdate_Batch implements Database.Batchable<sObject>, Database.Stateful {
    
    String query;
    List<Id> accountIds;
    Map<Id, Map<String, Set<String>>> mapTargetsByAccount;
    Boolean isCallFromInitial;

    global AccountLeadUpdate_Batch(Set<Id> setAccountIds) {
        accountIds = new List<Id>(setAccountIds);
        mapTargetsByAccount = new Map<Id, Map<String, Set<String>>>();
        this.query = 'SELECT Id, Name, CIS_ID_Prospect_Name__c, Lead_Type__c, Lead_Campaign__r.Name, Lead_Campaign__r.Status FROM Target_List__c WHERE CIS_ID_Prospect_Name__c IN (\'' + String.join(accountIds,'\',\'') + '\') AND Lead_Campaign__r.IsActive = true AND Status__c = \'New\' ORDER BY CIS_ID_Prospect_Name__c';
    }
    
    global AccountLeadUpdate_Batch(Set<Id> setAccountIds, Boolean isCallFromInitial) {
        this.isCallFromInitial = isCallFromInitial;
        accountIds = new List<Id>(setAccountIds);
        mapTargetsByAccount = new Map<Id, Map<String, Set<String>>>();
        this.query = 'SELECT Id, Name, CIS_ID_Prospect_Name__c, Lead_Type__c, Lead_Campaign__r.Name, Lead_Campaign__r.Status FROM Target_List__c WHERE CIS_ID_Prospect_Name__c IN (\'' + String.join(accountIds,'\',\'') + '\') AND Lead_Campaign__r.IsActive = true AND Status__c = \'New\' ORDER BY CIS_ID_Prospect_Name__c';
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Target_List__c> allTargetList) {
        for (Target_List__c eachTarget : allTargetList) {
            if(mapTargetsByAccount.containsKey(eachTarget.CIS_ID_Prospect_Name__c)) {
                if(mapTargetsByAccount.get(eachTarget.CIS_ID_Prospect_Name__c).get(eachTarget.Lead_Type__c) == null) {
                    Set<String> leadSetString = new Set<String>();
                    leadSetString.add(eachTarget.Lead_Campaign__r.Name);

                    mapTargetsByAccount.get(eachTarget.CIS_ID_Prospect_Name__c).put(eachTarget.Lead_Type__c, leadSetString);
                } else {
                    mapTargetsByAccount.get(eachTarget.CIS_ID_Prospect_Name__c).get(eachTarget.Lead_Type__c).add(eachTarget.Lead_Campaign__r.Name);            
                }
            } else {
                if(mapTargetsByAccount.size() >= Integer.valueOf(Label.Campaign_Lead_Batch_Size)) {
                    this.updateAccount();
                }
                
                Set<String> leadSetString = new Set<String>();
                leadSetString.add(eachTarget.Lead_Campaign__r.Name);

                mapTargetsByAccount.put(eachTarget.CIS_ID_Prospect_Name__c, new Map<String, Set<String>>{eachTarget.Lead_Type__c => leadSetString});
            }
        }

        if(mapTargetsByAccount.size() > 0) {
            this.updateAccount();    
        }
    }
    
    private void updateAccount() {
        System.debug('mapTargetsByAccount size:' + mapTargetsByAccount.size());
        System.debug('mapTargetsByAccount:' + mapTargetsByAccount);

        List<Account> updateAccount = new List<Account>();
        Account eachAccount;

        for (Id eachAccountId : mapTargetsByAccount.keySet()) {
            
            eachAccount = new Account(Id = eachAccountId);
            List<String> leadForSaleList = new List<String>();
            List<String> leadToInformList = new List<String>();
            List<String> leadToDoList = new List<String>();

            if(mapTargetsByAccount.get(eachAccountId).get(GlobalConstants.LEAD_FOR_SALES) != null) {
                leadForSaleList.addAll(mapTargetsByAccount.get(eachAccountId).get(GlobalConstants.LEAD_FOR_SALES));
            }

            if(mapTargetsByAccount.get(eachAccountId).get(GlobalConstants.LEAD_TO_INFORM) != null) {
                leadToInformList.addAll(mapTargetsByAccount.get(eachAccountId).get(GlobalConstants.LEAD_TO_INFORM));
            }

            if(mapTargetsByAccount.get(eachAccountId).get(GlobalConstants.CAMPAIGN) != null) {
                leadToInformList.addAll(mapTargetsByAccount.get(eachAccountId).get(GlobalConstants.CAMPAIGN));
            }

            if(mapTargetsByAccount.get(eachAccountId).get(GlobalConstants.LEAD_TO_DO) != null) {
                leadToDoList.addAll(mapTargetsByAccount.get(eachAccountId).get(GlobalConstants.LEAD_TO_DO));
            }
            
            eachAccount.Lead_for_Sales__c = leadForSaleList.isEmpty() ? null : String.join(leadForSaleList, ',');
            eachAccount.Lead_To_Do__c = leadToDoList.isEmpty() ? null : String.join(leadToDoList, ',');
            eachAccount.Lead_To_Inform__c = leadToInformList.isEmpty() ? null : String.join(leadToInformList, ',');
            updateAccount.add(eachAccount);
        }

        if(!updateAccount.isEmpty()) {
            Account_OwnerChange_Service.accountTriggerMap = new Map<Id,Account>();
            if(isCallFromInitial != null && isCallFromInitial) {
                update updateAccount;    
            } else {
                System.enqueueJob(new AccountLeadUpdate_Queue(updateAccount));    
            }

            mapTargetsByAccount.clear();
            if(mapTargetsByAccount.size() > 0) {
                mapTargetsByAccount = new Map<Id, Map<String, Set<String>>>();    
            }
        }
    }

    global void finish(Database.BatchableContext BC) {
        
    }
    
}