objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Credit Status</label>
        <picklist>
            <picklistValues>
                <fullName>Good Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>SME_Customer</fullName>
        <active>true</active>
        <label>SME-Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Call_Report__c.object
<CustomObject>
    <description>This object tracks the Call Plan and Call Report</description>
    <fields>
        <fullName>CIS_ID__c</fullName>
        <label>CIS ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call Plans / Call Reports</relationshipLabel>
        <relationshipName>Call_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Expected_Credit_Amount__c</fullName>
        <label>Expected Credit Amount (Baht)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Offer_Credit_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Offer Credit Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Offer_Interest__c</fullName>
        <label>Offer Interest</label>
        <picklist>
            <controllingField>Offer_Credit_Product__c</controllingField>
            <picklistValues>
                <fullName>Interest and can apply</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interest with condition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cannot apply</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer not interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interested with condition</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Plan_Date__c</fullName>
        <label>Plan Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Call Plan / Call Report</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Call Plan / Call Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Plans / Call Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Call_Report_Lead__c.object
<CustomObject>
    <description>This object tracks the Lead associated to Call Plan/Call Report</description>
    <fields>
        <fullName>Call_Plan_Call_Report__c</fullName>
        <label>Call Plan / Call Report</label>
        <referenceTo>Call_Report__c</referenceTo>
        <relationshipName>Leads</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT(Target_List__r.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target List</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Target_List__c.Lead_Campaign__r.Status</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>Target_List__c.Lead_Campaign__r.Sub_Type__c</field>
                <operation>notEqual</operation>
                <value>Value Chain</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Target_List__c</referenceTo>
        <relationshipLabel>Call Reports / Leads</relationshipLabel>
        <relationshipName>Associated_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>Target_List__r.Lead_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Call Report / Lead</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Reports / Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Lead_Campaign_Event_Code__c</fullName>
        <externalId>true</externalId>
        <label>Lead/Campaign/Event Code</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <label>Sub Type</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>Strong Formula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strong Hybrid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refinance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cheque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Chain</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Lead For Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead To Do</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead To Inform</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Target_List__c.object
<CustomObject>
    <description>This object tracks the list of Targeted Lead and Campaign Member list</description>
    <fields>
        <fullName>CIS_ID_Prospect_Name__c</fullName>
        <label>CIS ID / Prospect Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Campaign_Members_Leads</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>In_Call_Plan__c</fullName>
        <defaultValue>false</defaultValue>
        <label>In Call Plan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead_Campaign__c</fullName>
        <label>Lead/Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Target Lists</relationshipLabel>
        <relationshipName>Campaign_Members_Leads</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Done</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Interested This Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>App In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interested but not register</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stock Negotiation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Create Write Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Credit Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case is Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Credit Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial Loan Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Loan Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Target List</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is updated by DIH (HRIS): A = Active, I=Inactive</description>
        <label>Status Code</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CallReportLead_Test.cls
@isTest
private class CallReportLead_Test {
	public static String accountNameTM = 'tmCreatedAccountName';
    public static String accountNameRM = 'rmCreatedAccountName';
    public static String accountNameAH = 'ahCreatedAccountName';

	@testSetup static void setupAccount(){
		Mockup_Test mt = new Mockup_Test().setUpTest();

		System.runAs([SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameTM LIMIT 1][0]){
            mt.newAccount(accountNameTM,GlobalConstants.POOL,Mockup_Test.getRecordTypeAccountIdByName(GlobalConstants.SME_CUSTOMER));
        }
        System.runAs([SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameRM LIMIT 1][0]){
            mt.newAccount(accountNameRM,GlobalConstants.POOL,Mockup_Test.getRecordTypeAccountIdByName(GlobalConstants.SME_CUSTOMER));
        }
        System.runAs([SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameAH LIMIT 1][0]){
            mt.newAccount(accountNameAH,GlobalConstants.POOL,Mockup_Test.getRecordTypeAccountIdByName(GlobalConstants.SME_CUSTOMER));
        }
	}

	@isTest static void testAddTargetList() {
		Boolean expectedTargetListFlag = true;

		Account targetAccount = [SELECT Id FROM Account WHERE Name = :CallReportLead_Test.accountNameRM LIMIT 1];

		Campaign cm = new Campaign();
		cm.Lead_Campaign_Event_Code__c = 'TestCampaign';
		cm.Type__c = GlobalConstants.LEAD_TO_DO;
		cm.Name = 'TestCampaign';
		cm.IsActive = true;
		cm.Status = 'Active';
		cm.StartDate = System.Today() - 1;
		cm.EndDate = System.Today() + 1;
		cm.RecordTypeId = GlobalUtility.getRecordTypeCampaignIdByName('SME- Lead / Campaign');
		insert cm;

		Target_List__c tl = new Target_List__c();
		tl.CIS_ID_Prospect_Name__c = targetAccount.Id;
		tl.Lead_Campaign__c = cm.Id;
		tl.Status__c = GlobalConstants.STATUS_NEW;
		insert tl;

		Call_Report__c callreportObj;
		callreportObj = new Call_Report__c(
			RecordTypeId = GlobalUtility.getRecordTypeIdFromSObjectByDevName('Call_Report__c',GlobalConstants.NEW_CALL_PLAN_DEVNAME),
			CIS_ID__c = targetAccount.Id,
			Status__c = GlobalConstants.PLAN,
			Plan_Date__c = System.Today()
		);

		Test.startTest();
			insert callreportObj;
		Test.stopTest();

		Call_Report_Lead__c resultLead = new Call_Report_Lead__c();
		resultLead = [SELECT Id, Call_Plan_Call_Report__c, Target_List__c, Target_List__r.In_Call_Plan__c FROM Call_Report_Lead__c WHERE Call_Plan_Call_Report__c = :callreportObj.Id LIMIT 1];
		
		System.assert(resultLead != null);
		System.assertEquals(callreportObj.Id, resultLead.Call_Plan_Call_Report__c);
		System.assertEquals(tl.Id, resultLead.Target_List__c);
		System.assertEquals(expectedTargetListFlag, resultLead.Target_List__r.In_Call_Plan__c);
	}

	@isTest static void testDeleteTargetList() {
		Boolean expectedTargetListFlag = false;

		Account targetAccount = [SELECT Id FROM Account WHERE Name = :CallReportLead_Test.accountNameRM LIMIT 1];

		Campaign cm = new Campaign();
		cm.Lead_Campaign_Event_Code__c = 'TestCampaign';
		cm.Type__c = GlobalConstants.LEAD_TO_DO;
		cm.Name = 'TestCampaign';
		cm.IsActive = true;
		cm.Status = 'Active';
		cm.StartDate = System.Today() - 1;
		cm.EndDate = System.Today() + 1;
		cm.RecordTypeId = GlobalUtility.getRecordTypeCampaignIdByName('SME- Lead / Campaign');
		insert cm;

		Target_List__c tl = new Target_List__c();
		tl.CIS_ID_Prospect_Name__c = targetAccount.Id;
		tl.Lead_Campaign__c = cm.Id;
		tl.Status__c = GlobalConstants.STATUS_NEW;
		insert tl;

		Call_Report__c callreportObj;
		callreportObj = new Call_Report__c(
			RecordTypeId = GlobalUtility.getRecordTypeIdFromSObjectByDevName('Call_Report__c',GlobalConstants.NEW_CALL_PLAN_DEVNAME),
			CIS_ID__c = targetAccount.Id,
			Status__c = GlobalConstants.PLAN,
			Plan_Date__c = System.Today()
		);

		Test.startTest();
			insert callreportObj;

			Call_Report_Lead__c resultLead = new Call_Report_Lead__c();
			resultLead = [SELECT Id, Call_Plan_Call_Report__c, Target_List__c, Target_List__r.In_Call_Plan__c FROM Call_Report_Lead__c WHERE Call_Plan_Call_Report__c = :callreportObj.Id LIMIT 1];
			
			System.assert(resultLead != null);
			System.assertEquals(callreportObj.Id, resultLead.Call_Plan_Call_Report__c);
			System.assertEquals(tl.Id, resultLead.Target_List__c);
			System.assertEquals(true, resultLead.Target_List__r.In_Call_Plan__c);
		
			delete resultLead;
		Test.stopTest();

		Target_List__c finalTarget = [SELECT Id, In_Call_Plan__c FROM Target_List__c WHERE CIS_ID_Prospect_Name__c = :targetAccount.Id];

		System.assertEquals(expectedTargetListFlag, finalTarget.In_Call_Plan__c);
	}

	@isTest static void testDeleteTargetList2() {
		Boolean expectedTargetListFlag = true;

		Account targetAccount = [SELECT Id FROM Account WHERE Name = :CallReportLead_Test.accountNameRM LIMIT 1];

		Campaign cm = new Campaign();
		cm.Lead_Campaign_Event_Code__c = 'TestCampaign';
		cm.Type__c = GlobalConstants.LEAD_FOR_SALES;
		cm.Sub_Type__c = 'Strong Formula';
		cm.Name = 'TestCampaign';
		cm.IsActive = true;
		cm.Status = 'Active';
		cm.StartDate = System.Today() - 1;
		cm.EndDate = System.Today() + 1;
		cm.RecordTypeId = GlobalUtility.getRecordTypeCampaignIdByName('SME- Lead / Campaign');
		insert cm;

		Target_List__c tl = new Target_List__c();
		tl.CIS_ID_Prospect_Name__c = targetAccount.Id;
		tl.Lead_Campaign__c = cm.Id;
		tl.Status__c = GlobalConstants.STATUS_NEW;
		insert tl;

		Call_Report__c callreportObj = new Call_Report__c(
			RecordTypeId = GlobalUtility.getRecordTypeIdFromSObjectByDevName('Call_Report__c',GlobalConstants.NEW_CALL_PLAN_DEVNAME),
			CIS_ID__c = targetAccount.Id,
			Status__c = GlobalConstants.PLAN,
			Plan_Date__c = System.Today()
		);

		Call_Report__c callreportObj2 = new Call_Report__c(
			RecordTypeId = GlobalUtility.getRecordTypeIdFromSObjectByDevName('Call_Report__c',GlobalConstants.NEW_CALL_PLAN_DEVNAME),
			CIS_ID__c = targetAccount.Id,
			Status__c = GlobalConstants.PLAN,
			Plan_Date__c = System.Today()
		);
		insert callreportObj;
		insert callreportObj2;

		Call_Report_Lead__c resultLead = [SELECT Id, Call_Plan_Call_Report__c, Target_List__c, Target_List__r.In_Call_Plan__c FROM Call_Report_Lead__c WHERE Call_Plan_Call_Report__c = :callreportObj.Id LIMIT 1];
		Call_Report_Lead__c resultLead2 = [SELECT Id, Call_Plan_Call_Report__c, Target_List__c, Target_List__r.In_Call_Plan__c FROM Call_Report_Lead__c WHERE Call_Plan_Call_Report__c = :callreportObj2.Id LIMIT 1];

		System.assertEquals(callreportObj.Id, resultLead.Call_Plan_Call_Report__c);
		System.assertEquals(tl.Id, resultLead.Target_List__c);
		System.assertEquals(true, resultLead.Target_List__r.In_Call_Plan__c);
	
		System.assertEquals(callreportObj2.Id, resultLead2.Call_Plan_Call_Report__c);
		System.assertEquals(tl.Id, resultLead2.Target_List__c);
		System.assertEquals(true, resultLead2.Target_List__r.In_Call_Plan__c);


		Test.startTest();
			delete resultLead;
		Test.stopTest();

		Target_List__c finalTarget = [SELECT Id, In_Call_Plan__c FROM Target_List__c WHERE CIS_ID_Prospect_Name__c = :targetAccount.Id];

		System.assertEquals(expectedTargetListFlag, finalTarget.In_Call_Plan__c);
	}
	
	@isTest static void testUpdateTargetList() {
		Boolean expectedTargetListFlag = false;
		Boolean expectedTargetListFlag2 = true;

		Account targetAccount = [SELECT Id FROM Account WHERE Name = :CallReportLead_Test.accountNameRM LIMIT 1];

		Campaign cm = new Campaign();
		cm.Lead_Campaign_Event_Code__c = 'TestCampaign';
		cm.Type__c = GlobalConstants.LEAD_TO_DO;
		cm.Name = 'TestCampaign';
		cm.IsActive = true;
		cm.Status = 'Active';
		cm.StartDate = System.Today() - 1;
		cm.EndDate = System.Today() + 1;
		cm.RecordTypeId = GlobalUtility.getRecordTypeCampaignIdByName('SME- Lead / Campaign');
		insert cm;

		Target_List__c tl = new Target_List__c();
		tl.CIS_ID_Prospect_Name__c = targetAccount.Id;
		tl.Lead_Campaign__c = cm.Id;
		tl.Status__c = GlobalConstants.STATUS_NEW;
		insert tl;

		Target_List__c tl2 = new Target_List__c();
		tl2.CIS_ID_Prospect_Name__c = targetAccount.Id;
		tl2.Lead_Campaign__c = cm.Id;
		tl2.Status__c = GlobalConstants.STATUS_NEW;
		insert tl2;

		Call_Report__c callreportObj;
		callreportObj = new Call_Report__c(
			RecordTypeId = GlobalUtility.getRecordTypeIdFromSObjectByDevName('Call_Report__c',GlobalConstants.NEW_CALL_PLAN_DEVNAME),
			CIS_ID__c = targetAccount.Id,
			Status__c = GlobalConstants.PLAN,
			Plan_Date__c = System.Today()
		);

		insert callreportObj;

		Call_Report_Lead__c resultLead = new Call_Report_Lead__c();
		resultLead = [SELECT Id, Call_Plan_Call_Report__c, Target_List__c, Target_List__r.In_Call_Plan__c FROM Call_Report_Lead__c WHERE Call_Plan_Call_Report__c = :callreportObj.Id LIMIT 1];
		
		System.assertEquals(callreportObj.Id, resultLead.Call_Plan_Call_Report__c);
		System.assertEquals(tl.Id, resultLead.Target_List__c);
		System.assertEquals(true, resultLead.Target_List__r.In_Call_Plan__c);

		Test.startTest();
			resultLead.Target_List__c = tl2.Id;
			update resultLead;
		Test.stopTest();

		Target_List__c finalTarget = [SELECT Id, In_Call_Plan__c FROM Target_List__c WHERE CIS_ID_Prospect_Name__c = :targetAccount.Id AND Id = :tl.Id];
		Target_List__c finalTarget2 = [SELECT Id, In_Call_Plan__c FROM Target_List__c WHERE CIS_ID_Prospect_Name__c = :targetAccount.Id AND Id = :tl2.Id];

		System.assertEquals(expectedTargetListFlag, finalTarget.In_Call_Plan__c);
		System.assertEquals(expectedTargetListFlag2, finalTarget2.In_Call_Plan__c);
	}

	@isTest static void testUpdateTargetList2() {
		Boolean expectedTargetListFlag = true;
		Boolean expectedTargetListFlag2 = true;

		Account targetAccount = [SELECT Id FROM Account WHERE Name = :CallReportLead_Test.accountNameRM LIMIT 1];

		Campaign cm = new Campaign();
		cm.Lead_Campaign_Event_Code__c = 'TestCampaign';
		cm.Type__c = GlobalConstants.LEAD_FOR_SALES;
		cm.Sub_Type__c = 'Strong Formula';
		cm.Name = 'TestCampaign';
		cm.IsActive = true;
		cm.Status = 'Active';
		cm.StartDate = System.Today() - 1;
		cm.EndDate = System.Today() + 1;
		cm.RecordTypeId = GlobalUtility.getRecordTypeCampaignIdByName('SME- Lead / Campaign');
		insert cm;

		Target_List__c tl = new Target_List__c();
		tl.CIS_ID_Prospect_Name__c = targetAccount.Id;
		tl.Lead_Campaign__c = cm.Id;
		tl.Status__c = GlobalConstants.STATUS_NEW;
		insert tl;

		Target_List__c tl2 = new Target_List__c();
		tl2.CIS_ID_Prospect_Name__c = targetAccount.Id;
		tl2.Lead_Campaign__c = cm.Id;
		tl2.Status__c = GlobalConstants.STATUS_NEW;
		insert tl2;

		Call_Report__c callreportObj = new Call_Report__c(
			RecordTypeId = GlobalUtility.getRecordTypeIdFromSObjectByDevName('Call_Report__c',GlobalConstants.NEW_CALL_PLAN_DEVNAME),
			CIS_ID__c = targetAccount.Id,
			Status__c = GlobalConstants.PLAN,
			Plan_Date__c = System.Today()
		);

		Call_Report__c callreportObj2 = new Call_Report__c(
			RecordTypeId = GlobalUtility.getRecordTypeIdFromSObjectByDevName('Call_Report__c',GlobalConstants.NEW_CALL_PLAN_DEVNAME),
			CIS_ID__c = targetAccount.Id,
			Status__c = GlobalConstants.PLAN,
			Plan_Date__c = System.Today()
		);
		insert callreportObj;
		insert callreportObj2;

		Call_Report_Lead__c resultLead = [SELECT Id, Call_Plan_Call_Report__c, Target_List__c, Target_List__r.In_Call_Plan__c FROM Call_Report_Lead__c WHERE Call_Plan_Call_Report__c = :callreportObj.Id LIMIT 1];
		Call_Report_Lead__c resultLead2 = [SELECT Id, Call_Plan_Call_Report__c, Target_List__c, Target_List__r.In_Call_Plan__c FROM Call_Report_Lead__c WHERE Call_Plan_Call_Report__c = :callreportObj2.Id LIMIT 1];

		System.assertEquals(callreportObj.Id, resultLead.Call_Plan_Call_Report__c);
		System.assertEquals(tl.Id, resultLead.Target_List__c);
		System.assertEquals(true, resultLead.Target_List__r.In_Call_Plan__c);
	
		System.assertEquals(callreportObj2.Id, resultLead2.Call_Plan_Call_Report__c);
		System.assertEquals(tl.Id, resultLead2.Target_List__c);
		System.assertEquals(true, resultLead2.Target_List__r.In_Call_Plan__c);

		Test.startTest();
			resultLead.Target_List__c = tl2.Id;
			update resultLead;
		Test.stopTest();

		Target_List__c finalTarget = [SELECT Id, In_Call_Plan__c FROM Target_List__c WHERE CIS_ID_Prospect_Name__c = :targetAccount.Id AND Id = :tl.Id];
		Target_List__c finalTarget2 = [SELECT Id, In_Call_Plan__c FROM Target_List__c WHERE CIS_ID_Prospect_Name__c = :targetAccount.Id AND Id = :tl2.Id];

		System.assertEquals(expectedTargetListFlag, finalTarget.In_Call_Plan__c);
		System.assertEquals(expectedTargetListFlag2, finalTarget2.In_Call_Plan__c);
	}

	@isTest static void testUpdateTargetList3() {
		Boolean expectedTargetListFlag = false;
		Boolean expectedTargetListFlag2 = true;

		Account targetAccount = [SELECT Id FROM Account WHERE Name = :CallReportLead_Test.accountNameRM LIMIT 1];

		Campaign cm = new Campaign();
		cm.Lead_Campaign_Event_Code__c = 'TestCampaign';
		cm.Type__c = GlobalConstants.LEAD_FOR_SALES;
		cm.Name = 'TestCampaign';
		cm.IsActive = true;
		cm.Status = 'Active';
		cm.StartDate = System.Today() - 1;
		cm.EndDate = System.Today() + 1;
		cm.RecordTypeId = GlobalUtility.getRecordTypeCampaignIdByName('SME- Lead / Campaign');
		insert cm;

		Target_List__c tl = new Target_List__c();
		tl.CIS_ID_Prospect_Name__c = targetAccount.Id;
		tl.Lead_Campaign__c = cm.Id;
		tl.Status__c = GlobalConstants.STATUS_NEW;
		insert tl;

		Target_List__c tl2 = new Target_List__c();
		tl2.CIS_ID_Prospect_Name__c = targetAccount.Id;
		tl2.Lead_Campaign__c = cm.Id;
		tl2.Status__c = GlobalConstants.STATUS_NEW;
		insert tl2;

		Call_Report__c callreportObj;
		callreportObj = new Call_Report__c(
			RecordTypeId = GlobalUtility.getRecordTypeIdFromSObjectByDevName('Call_Report__c',GlobalConstants.NEW_CALL_PLAN_DEVNAME),
			CIS_ID__c = targetAccount.Id,
			Status__c = GlobalConstants.PLAN,
			Plan_Date__c = System.Today(),
			Offer_Credit_Product__c = true,
	        Offer_Interest__c = GlobalConstants.INTEREST_AND_CAN_APPLY,
	        Expected_Credit_Amount__c = 50000
		);

		insert callreportObj;

		Call_Report_Lead__c resultLead = new Call_Report_Lead__c();
		resultLead = [SELECT Id, Call_Plan_Call_Report__c, Target_List__c, Target_List__r.In_Call_Plan__c FROM Call_Report_Lead__c WHERE Call_Plan_Call_Report__c = :callreportObj.Id LIMIT 1];
		
		System.assertEquals(callreportObj.Id, resultLead.Call_Plan_Call_Report__c);
		System.assertEquals(tl.Id, resultLead.Target_List__c);
		System.assertEquals(true, resultLead.Target_List__r.In_Call_Plan__c);

		Test.startTest();
			resultLead.Target_List__c = tl2.Id;
			update resultLead;
		Test.stopTest();

		Target_List__c finalTarget = [SELECT Id, In_Call_Plan__c FROM Target_List__c WHERE CIS_ID_Prospect_Name__c = :targetAccount.Id AND Id = :tl.Id];
		Target_List__c finalTarget2 = [SELECT Id, In_Call_Plan__c FROM Target_List__c WHERE CIS_ID_Prospect_Name__c = :targetAccount.Id AND Id = :tl2.Id];

		System.assertEquals(expectedTargetListFlag, finalTarget.In_Call_Plan__c);
		System.assertEquals(expectedTargetListFlag2, finalTarget2.In_Call_Plan__c);
	}
}