objects/Account.object
<CustomObject>
    <fields>
        <fullName>Other_Segment__c</fullName>
        <label>Other Segment</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnerChangeExecutedByTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OwnerChangeExecutedByTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Port_Pool_Flag_Previous_Owner__c</fullName>
        <label>Port / Pool Flag (Previous Owner)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Port_Pool__c</fullName>
        <label>Port / Pool</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Previous_Owner_Emp_ID__c</fullName>
        <label>Previous Owner Emp ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Previous_Owner_Segment_Code__c</fullName>
        <label>Previous Owner Segment Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Previous_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Segment_Code__c</fullName>
        <label>Primary Segment Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_RM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service RM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Credit Status</label>
        <picklist>
            <picklistValues>
                <fullName>Good Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Temporary_Ownership_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This flag will be true when TM take temporary ownership from other TM pool by create call plan/call report or create opportunity. For other scenario that make customer value changed, this flag will turn to false</description>
        <label>Temporary Ownership Flag</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SME_Admin__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>To store the SME Admin proflle and UserID used as a default &quot;no ownership&apos; customer owner</description>
    <fields>
        <fullName>User_Record_ID__c</fullName>
        <label>User Record ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>SME Admin</label>
</CustomObject>

objects/Year_End_Assignment__c.object
<CustomObject>
    <description>This object tracks the re-assignment of customer to RM port / TM port or Pool, Refer out at the end of the year</description>
    <fields>
        <fullName>CIS_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CIS ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Assign_Port_Yearly</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Final_Assigned_RM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Final Assigned/SelectedBy</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Year_End_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Final_Port_Pool__c</fullName>
        <label>Final Port/Pool</label>
        <picklist>
            <picklistValues>
                <fullName>Port</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pool</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Final_Refer_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Final Refer Out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Final_Service_RM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Final Service RM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Year_End_Assignment1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Port_Pool__c</fullName>
        <label>Port / Pool</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Refer_Out_Reason__c</fullName>
        <label>Final Refer Out Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Reject</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wrong Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMLO List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exit Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Criminal Offense</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Segment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Refer_Out_Segment__c</fullName>
        <label>Final Refer Out Segment</label>
        <picklist>
            <picklistValues>
                <fullName>SM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Segment_Proposed__c</fullName>
        <label>Segment (Proposed)</label>
        <picklist>
            <picklistValues>
                <fullName>CB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XS</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Year-End Assignment</label>
    <nameField>
        <displayFormat>Ref-{00000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Year-End Assignment</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/YearEndAssignment_Batch.cls
/**
 * @author komsan.wi@beryl8.com
 * @16/07/2015 create new
 * @17/09/2015 update
 * @25/09/2015 remove stateful, change static variable to constants
 * @27/01/2015 Add Temporary_Ownership_Flag__c = false
 */

global class YearEndAssignment_Batch extends ApplicationLog_Service implements Database.Batchable<sObject> ,Database.AllowsCallouts{
    private List<Account> accountList;
    private SME_Admin__c sa;
    private String SUBMIT_VAL = GlobalConstants.Submitted;
    private String queryString;
    public YearEndAssignment_Batch(){
        accountList = new List<Account>();
        sa = SME_Admin__c.getOrgDefaults();
        queryString = query();
    }
    public YearEndAssignment_Batch(String yearId){
        accountList = new List<Account>();
        sa = SME_Admin__c.getOrgDefaults();
        queryString = query() + ' AND Id = \''+yearId+'\'';
    }
    public YearEndAssignment_Batch(Boolean flaging){
        accountList = new List<Account>();
        sa = SME_Admin__c.getOrgDefaults();
        queryString = query() + ' AND Final_Refer_Out__c =true';
    }
    private String query(){
        return 'SELECT Id,CIS_ID__c,CIS_ID__r.OwnerId,Final_Assigned_RM__c,Segment_Proposed__c,Final_Refer_Out__c,Final_Port_Pool__c,Final_Service_RM__c,Refer_Out_Reason__c,Refer_Out_Segment__c FROM Year_End_Assignment__c WHERE  Status__c=\'Submitted\'';
    }
    global Database.queryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(queryString);
    }
    global void execute(Database.BatchableContext BC, List<Year_End_Assignment__c> yearEnd){
        accountList = new List<Account>();
        for(Year_End_Assignment__c eachYearEnd : yearEnd){
            if (!eachYearEnd.Final_Refer_Out__c && ((eachYearEnd.Final_Port_Pool__c != null && eachYearEnd.Final_Assigned_RM__c!= sa.User_Record_ID__c) || eachYearEnd.Final_Assigned_RM__c== sa.User_Record_ID__c)) {
                if(eachYearEnd.CIS_ID__r.OwnerId!=eachYearEnd.Final_Assigned_RM__c)
                    accountList.add(new Account (
                            Id = eachYearEnd.CIS_ID__c,
                            OwnerId = eachYearEnd.Final_Assigned_RM__c,
                            Service_RM__c = eachYearEnd.Final_Service_RM__c,
                            Port_Pool__c = (eachYearEnd.Final_Assigned_RM__c!=sa.User_Record_ID__c)?eachYearEnd.Final_Port_Pool__c:null,
                            Previous_Owner__c = null,
                            OwnerChangeExecutedByTrigger__c = true,
                            Temporary_Ownership_Flag__c = false,
                            Previous_Owner_Emp_ID__c = null,
                            Previous_Owner_Segment_Code__c = null,
                            
                            Port_Pool_Flag_Previous_Owner__c = null
                        ));
            }else if (eachYearEnd.Final_Refer_Out__c && (eachYearEnd.Refer_Out_Reason__c == GlobalConstants.BAD || eachYearEnd.Refer_Out_Reason__c == GlobalConstants.DEAD || eachYearEnd.Refer_Out_Reason__c == GlobalConstants.CLOSED_BUSINESS || eachYearEnd.Refer_Out_Reason__c == GlobalConstants.AMLO_LIST || eachYearEnd.Refer_Out_Reason__c == GlobalConstants.EXIT_PLAN || eachYearEnd.Refer_Out_Reason__c == GlobalConstants.CRIMINAL_OFFENSE || eachYearEnd.Refer_Out_Reason__c == GlobalConstants.OTHER_SEGMENT)) {
                //refer out
                if(eachYearEnd.CIS_ID__r.OwnerId!=sa.User_Record_ID__c)
                accountList.add(
                    new Account(
                        Id = eachYearEnd.CIS_ID__c,
                        OwnerId = sa.User_Record_ID__c,
                        Service_RM__c = null,
                        Previous_Owner__c = null,
                        Primary_Segment_Code__c = (eachYearEnd.Refer_Out_Reason__c == GlobalConstants.OTHER_SEGMENT)?eachYearEnd.Segment_Proposed__c:null,
                        Other_Segment__c = (eachYearEnd.Refer_Out_Reason__c == GlobalConstants.OTHER_SEGMENT)?eachYearEnd.Refer_Out_Segment__c:null,
                        OwnerChangeExecutedByTrigger__c = true,
                        Temporary_Ownership_Flag__c = false,
                        Previous_Owner_Emp_ID__c = null,
                        Previous_Owner_Segment_Code__c = null,
                        Port_Pool__c = null,
                        Port_Pool_Flag_Previous_Owner__c = null
                    )
                );
            }else if(eachYearEnd.Refer_Out_Reason__c != GlobalConstants.REJECT){
                if(eachYearEnd.CIS_ID__r.OwnerId!='00528000000aAuWAAU')
                accountList.add(
                    new Account(
                        Id = eachYearEnd.CIS_ID__c,
                        OwnerId = '00528000000aAuWAAU',
                        Service_RM__c = null,
                        Previous_Owner__c = null,
                        Primary_Segment_Code__c = null,
                        Other_Segment__c = null,
                        OwnerChangeExecutedByTrigger__c = true,
                        Temporary_Ownership_Flag__c = false,
                        Previous_Owner_Emp_ID__c = null,
                        Previous_Owner_Segment_Code__c = null,
                        Port_Pool_Flag_Previous_Owner__c = null
                    )
                );
            }//else this.addLog('YearEndAssignment_Batch', 'Cannot Assign Selected YearEnd Record : ' + eachYearEnd.Id);
            
        }
        clearance();
    }
    protected override void clearance(){
        if(accountList!=null && accountList.size() > 0){
            try{
                Account_OwnerChange_Service.callingFromYearEndBatch = true;
                GlobalUtility.accounFromYearend = true;
                update accountList;
                Database.executeBatch(new SME_YearEndContactChangeOwner_Batch());
            }catch(Exception dex){
                this.addLog('YearEndAssignment_Batch',dex);
            }
        }
        super.clearance();
    }
    global void finish(Database.BatchableContext BC){}
}