objects/Account.object
<CustomObject>
    <fields>
        <fullName>CIS__c</fullName>
        <externalId>true</externalId>
        <label>CIS ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Credit Status</label>
        <picklist>
            <picklistValues>
                <fullName>Good Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>SME_Customer</fullName>
        <active>true</active>
        <label>SME-Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Lead_Campaign_Event_Code__c</fullName>
        <externalId>true</externalId>
        <label>Lead/Campaign/Event Code</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Lead For Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead To Do</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead To Inform</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Campaign_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Campaign code setup using for Target List reward calculation</description>
    <fields>
        <fullName>NewBooking_Code__c</fullName>
        <label>NewBooking Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Register_Period__c</fullName>
        <description>Register Period status campaign</description>
        <label>Register Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ThankYou_Code__c</fullName>
        <label>ThankYou Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Campaign Setting</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Actual_Application_Submit_Date__c</fullName>
        <label>Actual Application Submit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_RM_Submit_Date__c</fullName>
        <label>Actual RM Submit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Setup_Amount__c</fullName>
        <label>Setup Amount</label>
        <summarizedField>Opportunity_Product__c.Setup_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Opportunity_Product__c.Status__c</field>
            <operation>equals</operation>
            <value>Setup</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity_Product__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity_Product__c.object
<CustomObject>
    <description>This object tracks the Opportunity Product under Opportunity</description>
    <fields>
        <fullName>BA_Prosaving__c</fullName>
        <label>BA Prosaving</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BA_Protection__c</fullName>
        <label>BA Protection</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Front_End_Fee__c</fullName>
        <label>Front End Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Products</relationshipLabel>
        <relationshipName>Opportunity_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>ตั้งวงเงินทั้งหมดในครั้งแรก</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>แยกตั้งครั้งที่ 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>แยกตั้งครั้งที่ 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>แยกตั้งครั้งที่ 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>แยกตั้งครั้งที่ 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>แยกตั้งครั้งที่ 5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Setup_Amount__c</fullName>
        <label>Setup Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Setup_Date__c</fullName>
        <label>Setup Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Setup</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Opportunity Product</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Target_List__c.object
<CustomObject>
    <description>This object tracks the list of Targeted Lead and Campaign Member list</description>
    <fields>
        <fullName>CIS_ID_Prospect_Name__c</fullName>
        <label>CIS ID / Prospect Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Campaign_Members_Leads</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Campaign_Reward_Calc__c</fullName>
        <label>Campaign Reward Calc</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External_ID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Lead_Campaign__c</fullName>
        <label>Lead/Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Target Lists</relationshipLabel>
        <relationshipName>Campaign_Members_Leads</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Target Lists</relationshipLabel>
        <relationshipName>Target_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Setup_Amount__c</fullName>
        <label>Setup Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Done</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Interested This Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>App In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interested but not register</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stock Negotiation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Create Write Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Credit Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case is Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Credit Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial Loan Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Loan Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Target List</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is updated by DIH (HRIS): A = Active, I=Inactive</description>
        <label>Status Code</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TargetList_Test.cls
@isTest
private class TargetList_Test {
    
    public static String accountNameTM = 'tmCreatedAccountName';
    public static String accountNameRM = 'rmCreatedAccountName';
    public static String accountNameAH = 'ahCreatedAccountName';
    //Added By Nareerat W. 28/03/2016 CR-006 Test class TargetlistTriggerHandler
    public static string strNewBooking='NEWBOOKING';
    public static string strThankyou='THANKYOU';
    //End Added By Nareerat W. 28/03/2016 CR-006 Test class TargetlistTriggerHandler

    @testSetup static void setupAccount(){
        Mockup_Test mt = new Mockup_Test().setUpTest();

        System.runAs([SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameTM LIMIT 1][0]){
            mt.newAccount(accountNameTM,GlobalConstants.POOL,Mockup_Test.getRecordTypeAccountIdByName(GlobalConstants.SME_CUSTOMER));
        }
        System.runAs([SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameRM LIMIT 1][0]){
            mt.newAccount(accountNameRM,GlobalConstants.POOL,Mockup_Test.getRecordTypeAccountIdByName(GlobalConstants.SME_CUSTOMER));
             //Added By Nareerat W. 28/03/2016 CR-006 Test class TargetlistTriggerHandler
            TargetList_Test.setupCampaign();
            //End Added By Nareerat W. 28/03/2016 CR-006 Test class TargetlistTriggerHandler
        }
        System.runAs([SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameAH LIMIT 1][0]){
            mt.newAccount(accountNameAH,GlobalConstants.POOL,Mockup_Test.getRecordTypeAccountIdByName(GlobalConstants.SME_CUSTOMER));
        }
    }
    
    public static void setupCampaign(){
        /*
         * Created by: Nareerat W.
         * Created date: 28-Mar-2016
         * Description: Prepare Data for CR-006 Test class TargetlistTriggerHandler
        */
            Campaign_Setting__c cSetting = new Campaign_Setting__c();
            cSetting.NewBooking_Code__c= strNewBooking;
            cSetting.ThankYou_Code__c= strThankyou;
            cSetting.Register_Period__c=30;
            insert cSetting;
        
            Campaign CampaignNewBooking = new Campaign();
            CampaignNewBooking.name=strNewBooking;
            CampaignNewBooking.type__c='Campaign';
            CampaignNewBooking.Lead_Campaign_Event_Code__c=strNewBooking;
            CampaignNewBooking.StartDate=system.today();
            CampaignNewBooking.status='Active';
            CampaignNewBooking.IsActive=true;           
            insert CampaignNewBooking;
        
            Campaign CampaignThankyou = new Campaign();
            CampaignThankyou.name=strThankyou;
            CampaignThankyou.type__c='Campaign';
            CampaignThankyou.Lead_Campaign_Event_Code__c=strThankyou;
            CampaignThankyou.StartDate=system.today();
            CampaignThankyou.status='Active';
            CampaignThankyou.IsActive=true;         
            insert CampaignThankyou;
    }

   static testMethod void testUpdateTarget_To_NotRegister() {
        /*
         * Created by: Nareerat W.
         * Created date: 28-Mar-2016
         * Description:  CR-006 Test class TargetlistTriggerHandler
        */
        System.runAs([SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameAH LIMIT 1][0]) {

            Account testAcc = [SELECT Id FROM Account WHERE Name = :TargetList_Test.accountNameAH LIMIT 1];
            testAcc.OwnerId = UserInfo.getUserId();
            update testAcc;
            
            Opportunity opp1 = Mockup_Test.newOpportunity(testAcc.Id, 'TestNewOpp_3', GlobalConstants.CREATE_WRITE_UP, GlobalConstants.NON_CMAS); 
    
            Test.startTest();           
                insert opp1;
            
                Target_List__c targetNewBook =[SELECT Id, Name, Status__c FROM Target_List__c WHERE Lead_Campaign__r.Lead_Campaign_Event_Code__c= :strNewBooking and Opportunity__c= :opp1.Id LIMIT 1];
                targetNewBook.Status__c='Registered';
                update targetNewBook;

                opp1.StageName = GlobalConstants.STOCK_NEGOTIATION;         
                update opp1;  
                    
                opp1.Actual_Application_Submit_Date__c=system.today();
                opp1.Actual_RM_Submit_Date__c=system.today();
                opp1.StageName = 'Waiting for Credit Setup';
                update opp1;           
            
                Opportunity_Product__c oppProduct1=new Opportunity_Product__c();
                oppProduct1.Product__c='ตั้งวงเงินทั้งหมดในครั้งแรก';
                oppProduct1.Status__c='Setup';
                oppProduct1.Opportunity__c=opp1.Id;
                oppProduct1.Setup_Amount__c=9000000;
                oppProduct1.Setup_Date__c=system.today();
                oppProduct1.Front_End_Fee__c=1000000;
                oppProduct1.BA_Prosaving__c=900000;
                oppProduct1.BA_Protection__c=1000000;
                insert oppProduct1;
                
                opp1.StageName = GlobalConstants.ALL_LOAN_SETUP;            
                update opp1;
                
               targetNewBook.Status__c='Lead Expired';
               update targetNewBook;                    

            Test.stopTest();
            
            Target_List__c listNewBook =[SELECT Id, Name, Status__c, Campaign_Reward_Calc__c FROM Target_List__c WHERE Lead_Campaign__r.Lead_Campaign_Event_Code__c= :strNewBooking  and opportunity__c = :opp1.Id LIMIT 1];
            List<Target_List__c> listThankyou =[SELECT Id, Name, Status__c FROM Target_List__c WHERE Lead_Campaign__r.Lead_Campaign_Event_Code__c= :strThankyou and opportunity__c = :opp1.Id];
            System.assertEquals(listThankyou.size(),1);
            System.assertEquals(listNewBook.Campaign_Reward_Calc__c,'-');
            
        }
    }

    static testMethod void testConcatExternalId() {
        Account testAcc = [SELECT Id, CIS__c FROM Account WHERE Name = :TargetList_Test.accountNameAH LIMIT 1];
        Campaign targetCampaign = [SELECT Id, Lead_Campaign_Event_Code__c FROM Campaign WHERE Name = 'NEWBOOKING'];
        Test.startTest();                   
            insert new Target_List__c(
                Lead_Campaign__c = targetCampaign.Id, 
                CIS_ID_Prospect_Name__c = testAcc.Id);
        Test.stopTest();
        
        Target_List__c finalTarget =[SELECT Id, External_Id__c FROM Target_List__c WHERE Lead_Campaign__r.Lead_Campaign_Event_Code__c= :strNewBooking LIMIT 1];

        System.assertEquals(targetCampaign.Lead_Campaign_Event_Code__c + '' + testAcc.CIS__c, finalTarget.External_ID__c);
    }
    
}