objects/Account.object
<CustomObject>
    <fields>
        <fullName>OwnerChangeExecutedByTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OwnerChangeExecutedByTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ownership_Text__c</fullName>
        <label>Ownership</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ownership__c</fullName>
        <formula>CASE(Port_Pool__c, 
&quot;Port&quot;, &quot;Permanent&quot;, 
&quot;Pool&quot;,  CASE(Owner.Profile.Name,
                  &quot;SME-AH&quot;, &quot;Permanent&quot;,
                  &quot;SME-TM&quot;, IF(Temporary_Ownership_Flag__c, &quot;Temporary&quot;, &quot;Permanent&quot;),
                  &quot;SME-RM&quot;, &quot;Temporary&quot;, 
                  &quot;&quot;),                      
&quot;&quot;, IF(OR(Owner.Profile.Name = &quot;SME-RM&quot;,Owner.Profile.Name = &quot;SME-TM&quot;), &quot;Temporary&quot;, &quot;&quot;),
&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Ownership</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Permanent_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Permanent Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Permanent_Owners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Port_Pool__c</fullName>
        <label>Port / Pool</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_RM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service RM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Credit Status</label>
        <picklist>
            <picklistValues>
                <fullName>Good Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>is_from_Bulk_Reassign__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is from Bulk Reassign?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Bulk_Assignment__c.object
<CustomObject>
    <description>This object will be help to manage and stored bulk assignment history</description>
    <fields>
        <fullName>AssignmentOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>AssignmentOwner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BulkAssignmentQueue__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Bulk Assignment Queue</label>
        <referenceTo>Bulk_Assignment_Queue__c</referenceTo>
        <relationshipLabel>Bulk Assignments</relationshipLabel>
        <relationshipName>Bulk_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CIS_ID__c</fullName>
        <label>CIS / Prospect Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bulk Assignments</relationshipLabel>
        <relationshipName>Bulk_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CurrentOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CurrentOwner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ownership__c</fullName>
        <label>Ownership</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Permanent_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Permanent Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Bulk_Assignments1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Port_Pool__c</fullName>
        <label>Port/Pool</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_RM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service RM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Bulk_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Execute</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Bulk Assignment</label>
    <nameField>
        <displayFormat>BulkAssign-{0000000000}</displayFormat>
        <label>Bulk Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bulk Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Bulk_Assignment_Queue__c.object
<CustomObject>
    <fields>
        <fullName>FinishTime__c</fullName>
        <label>Finish Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Create</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Execute</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Bulk Assignment Queue</label>
    <nameField>
        <displayFormat>BulkAssignQueue-{0000000000}</displayFormat>
        <label>Bulk Assignment Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bulk Assignments Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SME_BulkAssignment_Service.cls
public without sharing class SME_BulkAssignment_Service {

	public static void bulkAssignment(List<Bulk_Assignment__c> bulkAssignList) {
		//List<Bulk_Assignment_Queue__c> bulkQueue = new List<Bulk_Assignment_Queue__c>();
		//bulkQueue = [SELECT Id FROM Bulk_Assignment_Queue__c WHERE Status__c = 'Execute' ORDER BY Name ASC];
		
		//List<Bulk_Assignment__c> bulkAssignList = new List<Bulk_Assignment__c>();
		//if(bulkQueue.size() > 0)
		//	bulkAssignList = [SELECT Id, BulkAssignmentQueue__c, CIS_ID__c, Permanent_Owner__c, AssignmentOwner__c, CurrentOwner__c, Port_Pool__c, Ownership__c, Service_RM__c FROM Bulk_Assignment__c WHERE BulkAssignmentQueue__r.Status__c = 'Execute' AND BulkAssignmentQueue__c = :bulkQueue.get(0).Id];

		List<Account> accountList = new List<Account>();
		Map<Id, Bulk_Assignment_Queue__c> updateBulkQueueMap = new Map<Id, Bulk_Assignment_Queue__c>();
		Bulk_Assignment_Queue__c queueBulk;
		Account eachAccount;
		for(Bulk_Assignment__c eachAssignment : bulkAssignList) {
			eachAccount = new Account (
	            Id = eachAssignment.CIS_ID__c,
	            OwnerChangeExecutedByTrigger__c = true,
	            OwnerId = eachAssignment.AssignmentOwner__c,
	            Permanent_Owner__c = eachAssignment.Permanent_Owner__c,
	            is_from_Bulk_Reassign__c = (eachAssignment.Ownership__c != null && eachAssignment.Ownership__c != ''),
	            Ownership_Text__c = eachAssignment.Ownership__c,
	            Service_RM__c = eachAssignment.Service_RM__c
	        );
	        if(eachAssignment.Permanent_Owner__c != null)
	        	eachAccount.Port_Pool__c = eachAssignment.Port_Pool__c;
			accountList.add(eachAccount);

	        eachAssignment.Status__c = 'Complete';
	        if(!updateBulkQueueMap.containsKey(eachAssignment.BulkAssignmentQueue__c))
	        	updateBulkQueueMap.put(eachAssignment.BulkAssignmentQueue__c, new Bulk_Assignment_Queue__c(Id = eachAssignment.BulkAssignmentQueue__c, Status__c = 'Complete', FinishTime__c = System.now()));
		}
        if(updateBulkQueueMap.size() > 0)
        	update updateBulkQueueMap.values();

        update bulkAssignList;
        update accountList;

        SME_BulkAssignment_Service.finish();
	}

	public static void finish() {
        Integer bulkQueueCount = [SELECT Count() FROM Bulk_Assignment_Queue__c WHERE Status__c = 'Execute'];
        if(bulkQueueCount > 0) {
        	SME_CalculateOwnershipAssignment_Service.executeBulkAssignmentBatch();
        }
	}
}