objects/Account.object
<CustomObject>
    <fields>
        <fullName>Birthdate_Registration_Date__c</fullName>
        <label>Birthdate / Registration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CIS__c</fullName>
        <externalId>true</externalId>
        <label>CIS ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Customer_360__c</fullName>
        <formula>IF(OR( $Profile.Name = &quot;System Administrator&quot;, RecordType.DeveloperName = &quot;SME_Customer&quot;), 
HYPERLINK(&quot;/apex/CustomerInformation?id=&quot;+Id, IMAGE(&quot;/resource/1437648590000/CustSumm&quot;, &quot;&quot; ,21, 20)), &quot;&quot;)</formula>
        <label>360°</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Status__c</fullName>
        <defaultValue>&quot;P&quot;</defaultValue>
        <label>Customer Status</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Type_Prospect__c</fullName>
        <label>Document Type</label>
        <picklist>
            <picklistValues>
                <fullName>บัตรประชาชน</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>หนังสือเดินทาง</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ใบต่างด้าว</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>เลขที่จดทะเบียนบริษัท</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SWIFT BIC CODE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>เลขที่ผู้เสียภาษี</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>เอกสารอื่นๆ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <formula>CASE(TEXT(Document_Type_Code__c),
&quot;11&quot;, &quot;บัตรประชาชน&quot;,
&quot;12&quot;, &quot;หนังสือเดินทาง&quot;,
&quot;13&quot;, &quot;ใบต่างด้าว&quot;,
&quot;21&quot;, &quot;เลขที่จดทะเบียนบริษัท&quot;,
&quot;22&quot;, &quot;SWIFT BIC CODE&quot;,
&quot;23&quot;, &quot;เลขที่ผู้เสียภาษี&quot;,
&quot;99&quot;, &quot;เอกสารอื่นๆ&quot;,
&quot; &quot;)</formula>
        <label>Document Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dual_Segment_Code__c</fullName>
        <label>Dual Segment Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Identification_No_Prospect__c</fullName>
        <inlineHelpText>Identification Number or Registration Number</inlineHelpText>
        <label>Identification No.</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_EN_Prospect__c</fullName>
        <label>Name (EN)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Permanent_Owner_Extension__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Permanent Owner Extension</label>
        <referenceTo>User_Extension__c</referenceTo>
        <relationshipLabel>Accounts (Permanent Owner Extension)</relationshipLabel>
        <relationshipName>AccountsPermanentOwnerExtension</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Port_Pool__c</fullName>
        <label>Port / Pool</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Segment_Code__c</fullName>
        <label>Primary Segment Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RC_Code__c</fullName>
        <formula>Owner.RC_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RC Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Credit Status</label>
        <picklist>
            <picklistValues>
                <fullName>Good Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Surname_EN_Prospect__c</fullName>
        <label>Surname (EN)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Surname_TH_Prospect__c</fullName>
        <label>Surname (TH)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <picklist>
            <picklistValues>
                <fullName>Co.,Ltd.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ROP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PCL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Part., Ltd.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mr.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mrs.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ms.</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Address__c.object
<CustomObject>
    <description>This object tracks the Location Address of customer, only 1 location address per customer</description>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <picklist>
            <picklistValues>
                <fullName>02</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CIS_ID__c</fullName>
        <label>CIS ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>ADR-{00000000}</displayFormat>
        <label>Address REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Call_Report__c.object
<CustomObject>
    <description>This object tracks the Call Plan and Call Report</description>
    <fields>
        <fullName>CIS_ID__c</fullName>
        <label>CIS ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call Plans / Call Reports</relationshipLabel>
        <relationshipName>Call_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>เลือกบุคคลผู้ติดต่อที่มีอยู่แล้ว</inlineHelpText>
        <label>Existing Contact Person</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.CIS_ID__c</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Call Plans / Call Reports</relationshipLabel>
        <relationshipName>Call_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Port_Pool__c</fullName>
        <label>Port / Pool</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Call Plan / Call Report</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Call Plan / Call Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Plans / Call Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CIS_ID__c</fullName>
        <formula>Account.CIS__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CIS ID</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>RC_Code__c</fullName>
        <label>RC Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is updated by DIH (HRIS): A = Active, I=Inactive</description>
        <label>Status Code</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CustomerSearch_Management.cls
public virtual class CustomerSearch_Management {
    //public String CIS;
    //public List<Account> accounts{get; set;}
    //public List<Call_Report__c> report{get; set;}
    //public List<List<SObject>> result {get; set;}

    protected Account getAccountFromId(String accountID){
        Account tempAccount = [Select Id, OwnerId, Port_Pool__c, RC_Code__c, Primary_Segment_Code__c, Permanent_Owner_Extension__c From Account Where Id =: accountID];
        return tempAccount;
    }

    protected User getUserFromId(Id userID){
        User tempUser = [Select Id, RC_Code__c, ManagerId,Profile.Name From User Where Id =: userID];
        return tempUser;
    }
    @TestVisible
    protected List<List<sObject>> searchAllValue(String inputID, String inputCIS, String inputFirstName, String inputLastName){
        String inputValue = '';
        if(inputID != null && inputID.trim() != ''){
            inputValue = inputID.trim();
            return queryAllSOSLValue(inputValue);
        }
        if(inputFirstName != null && inputFirstName.trim() != '' && inputValue != ''){
            inputValue = inputValue + ' or ' + inputFirstName.trim()+'*';
        }else if(inputFirstName != null && inputFirstName.trim() != ''){
            inputValue = inputFirstName.trim()+'*';
        }
        if(inputLastName != null && inputLastName.trim() != '' && inputValue != ''){
            inputValue = inputValue + ' or ' + inputLastName.trim()+'*';
        }else if(inputLastName != null && inputLastName.trim() != ''){
            inputValue = inputLastName.trim()+'*';
        }
        
        if(inputValue != ''){
            return queryAllSOSLValue(inputValue);
        }
        return null;
    }
  protected List<List<sObject>> sortAllValue(String inputID, String inputCIS, String inputFirstName, String inputLastName,String direction){
        String inputValue = '';
        List<List<sObject>> result = new List<List<SObject>>();
        //if(inputCIS != ''){
        //    inputValue = inputCIS;
        //    result = sortSOSLValueByName(inputValue,direction);
        //}
        if(inputID != null && inputID.trim() != ''){
            inputValue = inputID.trim();
            result = sortSOSLValueByName(inputValue,direction);
            return result;
        }
        if(inputFirstName != null && inputFirstName.trim() != '' && inputValue != ''){
            inputValue = inputValue + ' or ' + inputFirstName.trim()+'*';
        }else if(inputFirstName != null && inputFirstName.trim() != ''){
            inputValue = inputFirstName.trim()+'*';
        }
        if(inputLastName != null && inputLastName.trim() != '' && inputValue != ''){
            inputValue = inputValue + ' or ' + inputLastName.trim()+'*';
        }else if(inputLastName != null && inputLastName.trim() != ''){
            inputValue = inputLastName.trim()+'*';
        }
        
        if(inputValue != ''){
            result = sortSOSLValueByName(inputValue,direction);
        }
        return result;
    }
    @TestVisible
    protected List<List<sObject>> queryAllSOSLValue(String inputValue){

        List<List<SObject>> returnResult = new List<List<sObject>>();
        String searchQuery = 'FIND \'' + inputValue + '\' IN ALL FIELDS RETURNING Account(Id,CIS__c,Customer_360__c,Title__c,Primary_Segment_Code__c,'+
                                    'Document_Type__c,Dual_Segment_Code__c,Customer_Status__c,Status__c,RecordtypeId,OwnerId,Owner.Name,Name,'+
                                    'Name_EN_Prospect__c,Birthdate_Registration_Date__c,Port_Pool__c,'+
                                    'Surname_TH_Prospect__c,Surname_EN_Prospect__c,Identification_No_Prospect__c,Document_Type_Prospect__c order by Name ASC) LIMIT 100';
        returnResult = search.query(searchQuery);
        return returnResult;
    }
    @TestVisible
    protected List<List<sObject>> sortSOSLValueByName(String inputValue,String direction){

        List<List<SObject>> returnResult = new List<List<sObject>>();
        String searchQuery = 'FIND \'' + inputValue + '\' IN ALL FIELDS RETURNING Account(Id,CIS__c,Customer_360__c,Title__c,Primary_Segment_Code__c,'+
                                    'Document_Type__c,Dual_Segment_Code__c,Customer_Status__c,Status__c,RecordtypeId,OwnerId,Owner.Name,Name,'+
                                    'Name_EN_Prospect__c,Birthdate_Registration_Date__c,Port_Pool__c,'+
                                    'Surname_TH_Prospect__c,Surname_EN_Prospect__c,Identification_No_Prospect__c,Document_Type_Prospect__c order by Name '+direction+') LIMIT 100';
        returnResult = search.query(searchQuery);
        return returnResult;
    }

    protected Map<String,sObject> queryMapAddress(List<String> cisIdList){
        
        Map<String,sObject> mapAddress = new Map<String,sObject>();
        mapAddress = GlobalUtility.toMapLookup('CIS_ID__r','CIS__c', [SELECT Id,CIS_ID__c,CIS_ID__r.CIS__c,District__c,Province__c
                                    FROM Address__c WHERE CIS_ID__r.CIS__c IN :cisIdList AND Address_Type__c = 'Contact']);
        return mapAddress;
    }

    //public void set(){
    //    result= [find :CIS in ALL FIELDS RETURNING Account(cis__c,name, Phone),Call_Report__c(name,Contact__c)];
    //    accounts=result.remove(0);
    //    report=result.remove(0);
    //}
    /*public List<Account> SearchAccount(){
        return accounts;
    }*/
    /*public List<Call_Report__c> SearchCall(){
        return report;
    }*/
}