objects/Account.object
<CustomObject>
    <fields>
        <fullName>AH_RC_Code__c</fullName>
        <formula>Owner.AH_RC_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AH RC Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NH_RC_Code__c</fullName>
        <formula>Owner.NH_RC_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NH RC Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ownership_Text__c</fullName>
        <label>Ownership</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Permanent_Owner_Extension__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Permanent Owner Extension</label>
        <referenceTo>User_Extension__c</referenceTo>
        <relationshipLabel>Accounts (Permanent Owner Extension)</relationshipLabel>
        <relationshipName>AccountsPermanentOwnerExtension</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Port_Pool__c</fullName>
        <label>Port / Pool</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RC_Code__c</fullName>
        <formula>Owner.RC_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RC Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_RM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service RM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job_Code__c.object
<CustomObject>
    <description>This object tracks the Job Code of User</description>
    <label>Job Code</label>
    <nameField>
        <label>Job Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>AH_RC_Code__c</fullName>
        <label>AH RC Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Employee ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Job_Code__c</fullName>
        <label>Job Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NH_RC_Code__c</fullName>
        <label>NH RC Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RC_Code__c</fullName>
        <label>RC Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/User_Extension__c.object
<CustomObject>
    <description>To store user&apos;s information.</description>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <formula>User__r.Employee_ID__c</formula>
        <label>Employee ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Code__c</fullName>
        <formula>User__r.Job_Code__c</formula>
        <label>Job Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Extension</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Extension</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Extension</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SME_CalculateOwnershipAssignment_Batch.cls
global class SME_CalculateOwnershipAssignment_Batch implements Database.Batchable<sObject>, Database.Stateful {
    
    String query;

    private Set<Id> hrisDiffIds;
    private Set<Id> hrisInActiveIds;
    private Map<String, User> userMapByNewRoleRC;
    private Map<String, User_MaskModel> userMaskMapByEmpId;
    
    global SME_CalculateOwnershipAssignment_Batch(Map<String, User_MaskModel> userMaskMap, Map<String, User> userMapByNewRoleRC, Set<Id> hrisDiffSet, Set<Id> hrisInActiveSet) {
        this.userMaskMapByEmpId = userMaskMap;
        this.userMapByNewRoleRC = userMapByNewRoleRC;
        this.hrisDiffIds = hrisDiffSet;
        this.hrisInActiveIds = hrisInActiveSet;

        List<Id> queryOwnerIds = new List<Id>();
        queryOwnerIds.addAll(hrisDiffSet);
        queryOwnerIds.addAll(hrisInActiveSet);

        if(queryOwnerIds.size() > 0)
            SME_CalculateOwnershipAssignment_Service.assignUserRelatedObject(userMapByNewRoleRC, userMaskMapByEmpId, queryOwnerIds);
        this.query = 'SELECT Id, Permanent_Owner_Extension__c, Permanent_Owner_Extension__r.User__c, Ownership_Text__c, Port_Pool__c, Service_RM__c, OwnerId, Owner.Profile.Name, Owner.Employee_Id__c, Owner.RC_Code__c, Owner.AH_RC_Code__c, Owner.NH_RC_Code__c, Owner.Job_Code__c, Owner.ManagerId, Owner.Manager.ManagerId, Owner.Manager.Manager.ManagerId, Owner.Manager.IsActive, Owner.Manager.Manager.IsActive, Owner.Manager.Manager.Manager.IsActive, Owner.Manager.RC_Code__c, Owner.Manager.Manager.RC_Code__c, Owner.Manager.Manager.Manager.RC_Code__c, Owner.Manager.Job_Code__c, Owner.Manager.Manager.Job_Code__c, Owner.Manager.Manager.Manager.Job_Code__c FROM Account ORDER BY Permanent_Owner_Extension__c NULLS LAST, Service_RM__c NULLS LAST, OwnerId';
        //this.query = 'SELECT Id, Permanent_Owner_Extension__c, Permanent_Owner_Extension__r.User__c, Ownership_Text__c, Port_Pool__c, Service_RM__c, OwnerId, Owner.Profile.Name, Owner.Employee_Id__c, Owner.RC_Code__c, Owner.AH_RC_Code__c, Owner.NH_RC_Code__c, Owner.Job_Code__c, Owner.ManagerId, Owner.Manager.ManagerId, Owner.Manager.Manager.ManagerId, Owner.Manager.IsActive, Owner.Manager.Manager.IsActive, Owner.Manager.Manager.Manager.IsActive, Owner.Manager.RC_Code__c, Owner.Manager.Manager.RC_Code__c, Owner.Manager.Manager.Manager.RC_Code__c, Owner.Manager.Job_Code__c, Owner.Manager.Manager.Job_Code__c, Owner.Manager.Manager.Manager.Job_Code__c FROM Account WHERE OwnerId IN (\'' + String.join(queryOwnerIds,'\',\'') + '\')';
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Account> accountList) {
        List<Account> updateAccountList = SME_CalculateOwnershipAssignment_Service.createBulkAssignment(accountList, userMapByNewRoleRC, userMaskMapByEmpId, hrisDiffIds, hrisInActiveIds);
        update updateAccountList;
    }
    
    global void finish(Database.BatchableContext BC) {}
    
}