objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Credit Status</label>
        <picklist>
            <picklistValues>
                <fullName>Good Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>SME_Customer</fullName>
        <active>true</active>
        <label>SME-Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Credit_Model__c</fullName>
        <label>Credit Model</label>
        <picklist>
            <picklistValues>
                <fullName>DLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>อนุโลมขอใช้เลขจากทะเบียนคุม</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Setup_Amount__c</fullName>
        <label>Setup Amount</label>
        <summarizedField>Opportunity_Product__c.Setup_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Opportunity_Product__c.Status__c</field>
            <operation>equals</operation>
            <value>Setup</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity_Product__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Submission_Channel__c</fullName>
        <label>Submission Channel</label>
        <picklist>
            <controllingField>Credit_Model__c</controllingField>
            <picklistValues>
                <fullName>CMAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non CMAS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submit_Issue__c</fullName>
        <label>Submit Issue</label>
        <picklist>
            <picklistValues>
                <fullName>New Credit</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tentative_Application_Submit_Date__c</fullName>
        <label>Tentative Application Submit Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity_Product__c.object
<CustomObject>
    <description>This object tracks the Opportunity Product under Opportunity</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Products</relationshipLabel>
        <relationshipName>Opportunity_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Setup_Amount__c</fullName>
        <label>Setup Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Setup_Date__c</fullName>
        <label>Setup Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Setup</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Opportunity Product</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is updated by DIH (HRIS): A = Active, I=Inactive</description>
        <label>Status Code</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/SetupAll_Controller_Test.cls
@isTest
private class SetupAll_Controller_Test {
	public static String accountNameTM = 'tmCreatedAccountName';
	@testSetup static void setupAccount(){
        Mockup_Test mt = new Mockup_Test().setUpTest();
        System.runAs([SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameTM LIMIT 1][0]){
	        mt.newAccount(accountNameTM,GlobalConstants.POOL,Mockup_Test.getRecordTypeAccountIdByName(GlobalConstants.SME_CUSTOMER));
	    }
	}    

	static testMethod void assertTarget(){
		Integer expectedSetupAmount = 100;
		Date expectedDate = System.today()-2;
		String expectedStatus = 'Setup';

		User userTM = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameTM LIMIT 1];
		Account targetAccount = [SELECT Id FROM Account WHERE Name = :SetupAll_Controller_Test.accountNameTM LIMIT 1];
		Opportunity targetOp = new Opportunity();
		Opportunity_Product__c targetOpProduct = new Opportunity_Product__c();
		System.runAs(userTM){

			targetOp.AccountId = targetAccount.Id;
            targetOp.Name = 'TestOp';
			targetOp.StageName = 'Waiting for Credit Setup';
			targetOp.CloseDate = System.Today() + 1;
			targetOp.Submission_Channel__c   = GlobalConstants.CMAS;
            targetOp.Credit_Model__c = 'DLA';
            targetOp.Submit_Issue__c = 'New Credit';
            targetOp.Amount      = 10;
            targetOp.CloseDate   = System.today() + 1;
            targetOp.Tentative_Application_Submit_Date__c = System.today() + 7;

            insert targetOp;

            targetOpProduct.Opportunity__c = targetOp.Id;
            insert targetOpProduct;

            ApexPages.currentPage().getParameters().put('opid',targetOp.Id);

            SetupAll_Controller sc = new SetupAll_Controller();
            sc = new SetupAll_Controller(new ApexPages.StandardController(targetOpProduct));

            sc.setupall.Setup_Date__c = expectedDate;
			sc.setupall.Setup_Amount__c = expectedSetupAmount;
			sc.setupall.Status__c = expectedStatus;

            Test.startTest();
            	sc.savingSetupall();
            Test.stopTest();

            Opportunity_Product__c resultOpProduct = [SELECT Id,Setup_Date__c,Setup_Amount__c,Status__c FROM Opportunity_Product__c WHERE Opportunity__c = :targetOp.Id LIMIT 1];

            System.assertEquals(expectedDate,resultOpProduct.Setup_Date__c);
			System.assertEquals(expectedSetupAmount,resultOpProduct.Setup_Amount__c);
			System.assertEquals(expectedStatus,resultOpProduct.Status__c);
        }
	}
}