objects/Account.object
<CustomObject>
    <fields>
        <fullName>CIS__c</fullName>
        <externalId>true</externalId>
        <label>CIS ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Customer_s_Business_Code__c</fullName>
        <label>Customer&apos;s Business Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Associated_Customer__c.object
<CustomObject>
    <description>This object tracks the additional Customer and Contact for one call plan/call report</description>
    <fields>
        <fullName>Call_Plan_Call_Report__c</fullName>
        <label>Call Plan / Call Report</label>
        <referenceTo>Call_Report__c</referenceTo>
        <relationshipLabel>Associated Customers</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Secondary_Call_Plan_Call_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Call Plan / Call Report</label>
        <referenceTo>Call_Report__c</referenceTo>
        <relationshipLabel>Associated Customers (Secondary Call Plan / Call Report)</relationshipLabel>
        <relationshipName>Associated_Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Associated Customer</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Call_Report__c.object
<CustomObject>
    <description>This object tracks the Call Plan and Call Report</description>
    <fields>
        <fullName>Expected_Credit_Amount__c</fullName>
        <label>Expected Credit Amount (Baht)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Offer_Interest__c</fullName>
        <label>Offer Interest</label>
        <picklist>
            <controllingField>Offer_Credit_Product__c</controllingField>
            <picklistValues>
                <fullName>Interest and can apply</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interest with condition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cannot apply</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer not interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interested with condition</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Primary_Call_Plan_Call_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Call Plan / Call Report</label>
        <referenceTo>Call_Report__c</referenceTo>
        <relationshipLabel>Call Plans / Call Reports</relationshipLabel>
        <relationshipName>Call_Plans_Call_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Call_Report__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Primary Call Report</label>
        <type>Checkbox</type>
    </fields>
    <label>Call Plan / Call Report</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Call Plan / Call Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Plans / Call Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Call_Report_Opportunity__c.object
<CustomObject>
    <description>This object track the relationship between Call Report and Opportunity for the many to many relationship</description>
    <fields>
        <fullName>Call_Plan_Call_Report__c</fullName>
        <label>Call Plan / Call Report</label>
        <referenceTo>Call_Report__c</referenceTo>
        <relationshipName>Call_Report_Opportunity</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Offer_Interest__c</fullName>
        <formula>TEXT(Call_Plan_Call_Report__r.Offer_Interest__c) &amp; &quot; - &quot; &amp;  TEXT(Call_Plan_Call_Report__r.Reason__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Offer Interest</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.OwnerId</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Call Reports / Opportunities</relationshipLabel>
        <relationshipName>Call_Report_Opportunity</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Call_Plan_Call_Report__c</fullName>
        <formula>HYPERLINK(Call_Plan_Call_Report__r.Primary_Call_Plan_Call_Report__c, Call_Plan_Call_Report__r.Primary_Call_Plan_Call_Report__r.Name)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Call Plan / Call Report</label>
        <type>Text</type>
    </fields>
    <label>Call Report / Opportunity</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Reports / Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CallPlanCallReportField__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>AccountIdFieldId__c</fullName>
        <label>AccountIdFieldId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CallReportObjectId__c</fullName>
        <label>CallReportObjectId</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Id__c</fullName>
        <label>Entity Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewCallPlanRecordTypeId__c</fullName>
        <label>NewCallPlanRecordTypeId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>CallPlanCallReportField</label>
</CustomObject>

classes/CallReport_OverrideEdit_Controller.cls
/**
* @author komsan.wi@beryl8.com
* @07/07/2015 createddate
*/
public without sharing class CallReport_OverrideEdit_Controller {
    public CallReport_OverrideEdit_Controller(ApexPages.StandardController stdController) {
    }

    public CallReport_OverrideEdit_Controller() {
    }

    public PageReference redirectToNewPage() {
        CallPlanCallReportField__c callPlanCallReportField = CallPlanCallReportField__c.getOrgDefaults();
        //String accountIdString = ApexPages.currentPage().getParameters().get('accountId');
        //Account accountObj = [SELECT Customer_s_Business_Code__c FROM Account WHERE Id = :accountIdString LIMIT 1];
        //PageReference pageRef = new PageReference('/'+callPlanCallReportField.CallReportObjectId__c+'/e?CF00NN0000001cLxi='+accountObj.Customer_s_Business_Code__c);

        PageReference pageRef = new PageReference('/'+callPlanCallReportField.CallReportObjectId__c+'/e?');
        //pageRef.getParameters().put(callPlanCallReportField.AccountIdFieldId__c, callPlanCallReportField);
        pageRef.getParameters().put('retURL', ApexPages.currentPage().getParameters().get('retURL'));
        pageRef.getParameters().put('save_new_url', ApexPages.currentPage().getParameters().get('save_new_url'));
        pageRef.getParameters().put('scontrolCaching', ApexPages.currentPage().getParameters().get('scontrolCaching'));

        pageRef.getParameters().put('RecordType', callPlanCallReportField.NewCallPlanRecordTypeId__c);
        pageRef.getParameters().put('ent', callPlanCallReportField.Entity_Id__c);
        pageRef.getParameters().put('nooverride', '1');
       //retURL={!Account.Id}&saveURL=%2Fapex%2FCallReport_OverrideEdit%3FaccountId%3D{!Account.Id}&RecordType={!$Setup.CallPlanCallReportField__c.NewCallPlanRecordTypeId__c}&ent={!$Setup.CallPlanCallReportField__c.Entity_Id__c}
       pageRef.setRedirect(true);
        return pageRef;
    }

    public PageReference redirect(){
        String newidString = ApexPages.currentPage().getParameters().get('newid');
        String accountIdString = ApexPages.currentPage().getParameters().get('accountId');
        String primaryFlagString = ApexPages.currentPage().getParameters().get('primaryFlag');
        String primaryCallReportIdString = ApexPages.currentPage().getParameters().get('primaryCallReportId');
        String associatedIdString = ApexPages.currentPage().getParameters().get('associatedId');
        PageReference pageRef;
        System.debug('newidString::'+newidString);
        System.debug('accountIdString::'+accountIdString);
        System.debug('primaryFlagString::'+primaryFlagString);
        System.debug('primaryCallReportIdString::'+primaryCallReportIdString);
        System.debug('associatedIdString::'+associatedIdString);
        List<Call_Report__c> callReportObj = new List<Call_Report__c>();
        callReportObj = [SELECT Id,Offer_Interest__c,Expected_Credit_Amount__c,Primary_Call_Report__c FROM Call_Report__c WHERE Id = :newidString LIMIT 1];
        System.debug('callReportObj::'+callReportObj);
        if(callReportObj!=null && callReportObj.size() > 0){
            if(primaryCallReportIdString != null && primaryCallReportIdString != '' && primaryFlagString != null && primaryFlagString == '0' && callReportObj.get(0).Primary_Call_Report__c != false){
                Call_Report__c updateCallReport = new Call_Report__c(Id=callReportObj.get(0).Id);
                updateCallReport.Primary_Call_Report__c = false;
                updateCallReport.Primary_Call_Plan_Call_Report__c = Id.valueOf(primaryCallReportIdString);
                update updateCallReport;
                if(associatedIdString != null && associatedIdString != ''){
                    Associated_Customer__c tempAssociated = new Associated_Customer__c(Id=Id.valueOf(associatedIdString));
                    tempAssociated.Secondary_Call_Plan_Call_Report__c = Id.valueOf(newidString);

                    update tempAssociated;
                }

            }
            List<Call_Report_Opportunity__c> currentOpportunity = new List<Call_Report_Opportunity__c>();
            currentOpportunity = [SELECT Opportunity_Name__c FROM Call_Report_Opportunity__c WHERE Call_Plan_Call_Report__c =:newidString ORDER BY CreatedDate DESC LIMIT 1];
            System.debug('currentOpportunity::'+currentOpportunity);
            /*Account accountObj = [SELECT Id,Name,CIS__c FROM Account WHERE Id = :accountIdString LIMIT 1];
            Opportunity opObj = new Opportunity(
                Name = (accountObj.CIS__c!=null)?accountObj.CIS__c:accountObj.Name,
                AccountId = accountIdString,
                CloseDate = System.today()+45,
                StageName = GlobalConstants.STOCK_NEGOTIATION,
                Amount = callReportObj.Expected_Credit_Amount__c
            );
            insert opObj;
            insert new Call_Report_Opportunity__c(
                Call_Plan_Call_Report__c = newidString,
                Opportunity_Name__c = opObj.Id
            );*/
            if(currentOpportunity!=null && currentOpportunity.size() > 0)
                pageRef = new PageReference('/'+currentOpportunity.get(0).Opportunity_Name__c);
            else if(primaryCallReportIdString!=null)
                pageRef = new PageReference('/'+primaryCallReportIdString);
            else if(newidString!=null)
                pageRef = new PageReference('/'+newidString);
        }else if(newidString!=null){
            pageRef = new PageReference('/'+newidString);
        }
        return pageRef;
    }
    public PageReference redirectToListView(){
        Schema.DescribeSObjectResult r = Call_Report__c.sObjectType.getDescribe();
        String keyPrefix = r.getKeyPrefix();
        PageReference pageRef = new PageReference('/'+keyPrefix);
        return pageRef;
    }
}