objects/Account.object
<CustomObject>
    <fields>
        <fullName>First_Visited_Date__c</fullName>
        <label>First Visited Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Call_Report__c.object
<CustomObject>
    <description>This object tracks the Call Plan and Call Report</description>
    <fields>
        <fullName>Actual_Visit_Date__c</fullName>
        <defaultValue>IF(CONTAINS($RecordType.DeveloperName,&quot;CallReport&quot;),TODAY(),NULL)</defaultValue>
        <inlineHelpText>ห้ามเกินกว่าวันปัจจุบัน</inlineHelpText>
        <label>Actual Visit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CIS_ID__c</fullName>
        <label>CIS ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call Plans / Call Reports</relationshipLabel>
        <relationshipName>Call_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Channel__c</fullName>
        <label>Contact Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Face to Face</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone Call</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Offer_Credit_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Offer Credit Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Offer_Interest__c</fullName>
        <label>Offer Interest</label>
        <picklist>
            <controllingField>Offer_Credit_Product__c</controllingField>
            <picklistValues>
                <fullName>Interest and can apply</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interest with condition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cannot apply</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer not interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interested with condition</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <picklist>
            <controllingField>Offer_Interest__c</controllingField>
            <picklistValues>
                <fullName>2.1 รอตัดสินใจ/รอปรึกษาครอบครัว</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.2 สนใจแต่รอแก้ปัญหาเรื่องหลักประกัน</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.3 สนใจแต่มีประเด็นต่อรองเกี่ยวกับดอกเบี้ย / ค่าธรรมเนียม</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.4 สนใจแต่ไม่ใช่ในช่วงเดือนนี้</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.5 สนใจแต่มีประเด็นต่อรองเกี่ยวกับประกันชีวิต</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.6 สนใจแต่วงเงินที่เสนอไม่เพียงพอ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.7 อื่น ๆ (โปรดระบุ)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.1 Refer ให้ผู้อื่นดำเนินการ (ระบุในหมายเหตุ)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.2 ที่อยู่ และเบอร์โทรศัพท์ไม่ถูกต้อง / ไม่มีข้อมูล/ ติดต่อไม่ได้</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.3 เพิ่งขอสินเชื่อไม่ถึง 3 เดือน</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.4 ลูกค้าคุณสมบัติไม่ดี / ไม่ผ่านหลักเกณฑ์ธนาคาร (ระบุในหมายเหตุ)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.5 ลูกค้าไม่ให้เข้าพบ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.6 เสียชีวิต / เลิกกิจการ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.7 หลักประกันไม่ผ่านเกณฑ์</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.8 อื่น ๆ (โปรดระบุ)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.1 มีเงินคงเหลือในบัญชีสูงหรือวงเงินเป็นตัวดำ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.2 ติดเรื่องค่าใช้จ่ายในการดำเนินการ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.3 ยอดขายกิจการลดลง</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.4 ตัดออกจากรายชื่อ Lead (ระยะเวลา 6 เดือน)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.5 ขอในนามบุคคล/บริษัทอื่น (โปรดระบุ CIS/เลขบัตรประชาชนหรือเลขทะเบียนการค้า)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.6 อื่น ๆ (โปรดระบุ)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Call Plan / Call Report</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Call Plan / Call Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Plans / Call Reports</pluralLabel>
    <recordTypes>
        <fullName>CallReport</fullName>
        <active>true</active>
        <description>with Call Plan section</description>
        <label>Call Report</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Account_UpdateFirstVisitedDate_Test.cls
/***********************************************************************
*  Created By		: Chumphon Kaewpraphan
*  Date Created		: 21 April 2016
*
*  Description		: Test class for batch Account_UpdateFirstVisitedDate_Batch
*
*  Modification List:
*  Name         	Date            Modification Description
*  ----------		-----------		------------------------------
*  Chumphon K.		26-Apr-2016 	Initial Code Creation
*  
***********************************************************************/
@isTest
public class Account_UpdateFirstVisitedDate_Test {
    
    static testMethod void testUpdateFirstVisitedDate(){
        Account acc = new Account();
        acc.Name = 'TestAcc1';
        insert acc;

        Call_Report__c callReport = new Call_Report__c();
        callReport.CIS_ID__c = acc.Id;
        callReport.Actual_Visit_Date__c = Date.today()-1;
        callReport.Contact_Channel__c = 'Phone Call';
        callReport.Offer_Credit_Product__c = true;
        callReport.Offer_Interest__c = 'Interest with condition';
        callReport.Reason__c = '2.1 รอตัดสินใจ/รอปรึกษาครอบครัว';  
        insert callReport;
        
        Account updateAccount = [SELECT Id, First_Visited_Date__c FROM Account WHERE Id = :acc.Id LIMIT 1];
        updateAccount.First_Visited_Date__c = null;
        update updateAccount;

         Test.startTest();
             Database.executeBatch(new Account_UpdateFirstVisitedDate_Batch());
         Test.stopTest();
        
        Account result = [SELECT Id, First_Visited_Date__c FROM Account WHERE Id = :acc.Id LIMIT 1];
        System.assertEquals(Date.today()-1, result.First_Visited_Date__c);
    }
}