objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Credit Status</label>
        <picklist>
            <picklistValues>
                <fullName>Good Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>SME_Customer</fullName>
        <active>true</active>
        <label>SME-Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Call_Report__c.object
<CustomObject>
    <description>This object tracks the Call Plan and Call Report</description>
    <fields>
        <fullName>CIS_ID__c</fullName>
        <label>CIS ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call Plans / Call Reports</relationshipLabel>
        <relationshipName>Call_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Collect_Documents__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Collect Documents</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Firstname__c</fullName>
        <inlineHelpText>สำหรับสร้างบุคคลผู้ติดต่อใหม่</inlineHelpText>
        <label>Contact Firstname</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>เลือกบุคคลผู้ติดต่อที่มีอยู่แล้ว</inlineHelpText>
        <label>Existing Contact Person</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.CIS_ID__c</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Call Plans / Call Reports</relationshipLabel>
        <relationshipName>Call_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Important_Note__c</fullName>
        <label>Important Note of this Visit</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Existing Phone Number</label>
        <length>20</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Plan_Amount__c</fullName>
        <label>Plan Amount</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Plan_Date__c</fullName>
        <label>Plan Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Call Plan / Call Report</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Call Plan / Call Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Plans / Call Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Birthdate__c</fullName>
        <inlineHelpText>Birthdate format must be DD/MM/YYYY</inlineHelpText>
        <label>Birthdate</label>
        <length>10</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>CIS_ID__c</fullName>
        <formula>Account.CIS__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CIS ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Firstname__c</fullName>
        <label>Contact Firstname</label>
        <length>175</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <inlineHelpText>Phone format must be in number with 9 or 10 digits</inlineHelpText>
        <label>Phone Number</label>
        <length>20</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is updated by DIH (HRIS): A = Active, I=Inactive</description>
        <label>Status Code</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CallReport_Override_Controller_Test.cls
@isTest
private class CallReport_Override_Controller_Test {
	
	public static String accountNameTM = 'tmCreatedAccountName';
	@testSetup static void setupAccount(){
        Mockup_Test mt = new Mockup_Test().setUpTest();
        System.runAs([SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameTM LIMIT 1][0]){
	        mt.newAccount(accountNameTM,GlobalConstants.POOL,Mockup_Test.getRecordTypeAccountIdByName(GlobalConstants.SME_CUSTOMER));
	    }
	}    

	static testMethod void testRedirectToCallReport(){
		Account targetAccount = [SELECT Id FROM Account WHERE Name = :CallReport_Override_Controller_Test.accountNameTM LIMIT 1];

		System.runAs([SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameTM LIMIT 1][0]){
            Contact con = new Contact();
			con.LastName = 'lastname';
			con.Contact_Firstname__c = 'Firstname';
			con.Birthdate__c = '11/11/2550';
			con.AccountId = targetAccount.Id;
			con.Phone_Number__c = '023450789';
			insert con;

            Call_Report__c callreportObj = new Call_Report__c(
				Collect_Documents__c = true,
				CIS_ID__c = targetAccount.Id,
				Status__c = GlobalConstants.PLAN,
				Plan_Date__c = System.Today(),
				Contact__c = con.Id,
				RecordtypeId = [SELECT Id FROM RecordType WHERE SObjectType ='Call_Report__c' AND DeveloperName=:GlobalConstants.CALL_REPORT_NO_PLAN_DEVNAME][0].Id
			);

			insert callreportObj;
       		
       		CallReport_OverrideEdit_Controller controller = new CallReport_OverrideEdit_Controller(new ApexPages.StandardController(callreportObj));
        	controller.redirectToNewPage();
        	//String currentURL = ApexPages.currentPage().getUrl();
        }
    }

    static testMethod void testRedirectToCallPlan(){
		Account targetAccount = [SELECT Id FROM Account WHERE Name = :CallReport_Override_Controller_Test.accountNameTM LIMIT 1];

		System.runAs([SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameTM LIMIT 1][0]){
			Call_Report__c callPlanObj;
			callPlanObj = new Call_Report__c(
				RecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType ='Call_Report__c' AND DeveloperName=:GlobalConstants.NEW_CALL_PLAN_DEVNAME][0].Id,
				CIS_ID__c = targetAccount.Id,
				Status__c = GlobalConstants.PLAN,
				Plan_Date__c = System.Today(),
				Plan_Amount__c = 50000,
				Customer_Important_Note__c = 'expected'
			);
			insert callPlanObj;

			Test.startTest();
            	ApexPages.currentPage().getParameters().put('newid', callPlanObj.Id);
            	ApexPages.currentPage().getParameters().put('accountId', targetAccount.Id);
            	CallReport_OverrideEdit_Controller controller = new CallReport_OverrideEdit_Controller(new ApexPages.StandardController(callPlanObj));
            	controller.redirect();

            	//String currentURL = ApexPages.currentPage().getUrl();
            Test.stopTest();
        }
    }

    static testMethod void testRedirectToCallPlanListView(){
    	CallReport_OverrideEdit_Controller controller = new CallReport_OverrideEdit_Controller();
    	Test.startTest();
    	controller.redirectToListView();
    	Test.stopTest();
    }

    static testMethod void testCallPlanListViewRedirect(){
    	CallReport_OverrideListView_Controller controller = new CallReport_OverrideListView_Controller();
    	Test.startTest();
    	controller.redirectToListView();
    	Test.stopTest();
    }
	
}