objects/Account.object
<CustomObject>
    <fields>
        <fullName>CIS__c</fullName>
        <externalId>true</externalId>
        <label>CIS ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Customer_Owner_Changed_Date__c</fullName>
        <label>Customer Owner Changed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Delete_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Delete Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Port_Pool__c</fullName>
        <label>Port / Pool</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Previous_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Segment_Code__c</fullName>
        <label>Primary Segment Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_RM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service RM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Credit Status</label>
        <picklist>
            <picklistValues>
                <fullName>Good Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is updated by DIH (HRIS): A = Active, I=Inactive</description>
        <label>Status Code</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Year_End_Assignment__c.object
<CustomObject>
    <description>This object tracks the re-assignment of customer to RM port / TM port or Pool, Refer out at the end of the year</description>
    <fields>
        <fullName>CIS_ID_Unique__c</fullName>
        <externalId>true</externalId>
        <label>CIS ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CIS_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CIS ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Assign_Port_Yearly</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Final_Assigned_RM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Final Assigned/SelectedBy</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Year_End_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Final_Port_Pool__c</fullName>
        <label>Final Port/Pool</label>
        <picklist>
            <picklistValues>
                <fullName>Port</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pool</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Final_Refer_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Final Refer Out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Final_Service_RM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Final Service RM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Year_End_Assignment1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Port_Pool__c</fullName>
        <label>Port / Pool</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Refer_Out_Reason__c</fullName>
        <label>Final Refer Out Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Reject</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wrong Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMLO List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exit Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Criminal Offense</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Segment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Segment_Proposed__c</fullName>
        <label>Segment (Proposed)</label>
        <picklist>
            <picklistValues>
                <fullName>CB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XS</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Year-End Assignment</label>
    <nameField>
        <displayFormat>Ref-{00000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Year-End Assignment</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/YearEndAssignment_Batch_Test.cls
/**
* @author komsan.wi@beryl8.com
* @16/07/2015 createddate
* @17/09/2015 update
*/
@isTest
private class YearEndAssignment_Batch_Test {
    public static String accountNameTM = 'tmCreatedAccountName';
    @testSetup static void setupAccount(){
        Mockup_Test mt = new Mockup_Test().setUpTest();
        
        System.runAs([SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameTM LIMIT 1][0]){
            mt.newAccount(accountNameTM,'',Mockup_Test.getRecordTypeAccountIdByName('SME-Customer'));
        }
    }

    //static testMethod void yearEndAssignChangeAccount(){
    //  Account targetAccount = [SELECT Id,Delete_Flag__c,OwnerId,Previous_Owner__c,CIS__c,Name FROM Account WHERE Name = :YearEndAssignment_Batch_Test.accountNameTM LIMIT 1];
    //  User userRM = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameRM LIMIT 1];
 //       User userTM = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameTM LIMIT 1];
    //  insert new Year_End_Assignment__c(
            //CIS_ID_Unique__c = targetAccount.Name,
    //      CIS_ID__c = targetAccount.Id,
    //      Final_Assigned_RM__c = userRM.Id,
    //      Status__c = GlobalConstants.SUBMITTED,
    //      //Final_Refer_Out__c = false,
    //      Final_Service_RM__c = userRM.Id,
    //      Final_Port_Pool__c = GlobalConstants.POOL
    //  );
    //  Test.startTest();
 //         Database.executeBatch(new YearEndAssignment_Batch());
 //       Test.stopTest();
        
    //  Account finalAccount = [SELECT Id,OwnerId,Previous_Owner__c,Port_Pool__c,Customer_Owner_Changed_Date__c,Service_RM__c FROM Account WHERE Name = :YearEndAssignment_Batch_Test.accountNameTM LIMIT 1];

 //       System.assertEquals(userRM.Id,finalAccount.OwnerId);
 //       System.assertEquals(userRM.Id, finalAccount.Service_RM__c);
 //       System.assertEquals(userTM.Id,finalAccount.Previous_Owner__c);
 //       System.assertEquals(GlobalConstants.POOL,finalAccount.Port_Pool__c);
 //       System.assertEquals(System.Today(),finalAccount.Customer_Owner_Changed_Date__c);
    //}

    static testMethod void yearEndAssignAccount(){
        Account targetAccount = [SELECT Id,Delete_Flag__c,OwnerId,Previous_Owner__c,CIS__c,Name FROM Account WHERE Name = :YearEndAssignment_Batch_Test.accountNameTM LIMIT 1];
        User userRM = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameRM LIMIT 1];
        User userTM = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameTM LIMIT 1];
        insert new Year_End_Assignment__c(
            CIS_ID_Unique__c = targetAccount.Name,
            CIS_ID__c = targetAccount.Id,
            Final_Assigned_RM__c = userTM.Id,
            Status__c = GlobalConstants.SUBMITTED,
            Final_Refer_Out__c = false,
            Final_Service_RM__c = userRM.Id,
            Final_Port_Pool__c = GlobalConstants.POOL
        );
        Test.startTest();
            Database.executeBatch(new YearEndAssignment_Batch());
        Test.stopTest();
        
        Account finalAccount = [SELECT Id,OwnerId,Previous_Owner__c,Port_Pool__c,Customer_Owner_Changed_Date__c,Service_RM__c FROM Account WHERE Name = :YearEndAssignment_Batch_Test.accountNameTM LIMIT 1];

        //System.assertEquals(userTM.Id, finalAccount.OwnerId);
        //System.assertEquals(userRM.Id, finalAccount.Service_RM__c);
        //System.assertEquals(null, finalAccount.Previous_Owner__c);
        //System.assertEquals(GlobalConstants.POOL, finalAccount.Port_Pool__c);
        //System.assertEquals(System.Today(), finalAccount.Customer_Owner_Changed_Date__c);

    }

    static testMethod void yearEndAssignAccountDead(){
        System.runAs([SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameAdmin LIMIT 1][0]){
            Account targetAccount = [SELECT Id,Delete_Flag__c,OwnerId,Previous_Owner__c,CIS__c,Name FROM Account WHERE Name = :YearEndAssignment_Batch_Test.accountNameTM LIMIT 1];
            User userRM = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameRM LIMIT 1];
            User userAdmin = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameAdmin LIMIT 1];
            insert new Year_End_Assignment__c(
                CIS_ID_Unique__c = targetAccount.Name,
                CIS_ID__c = targetAccount.Id,               
                Final_Assigned_RM__c = userRM.Id,
                Final_Refer_Out__c = true,
                Status__c = GlobalConstants.SUBMITTED,
                Refer_Out_Reason__c = 'Exit Plan'
            );
            Test.startTest();
                Database.executeBatch(new YearEndAssignment_Batch());
            Test.stopTest();
            
            Account finalAccount = [SELECT Id, Service_RM__c ,OwnerId , Previous_Owner__c, Port_Pool__c, Customer_Owner_Changed_Date__c FROM Account WHERE Name = :YearEndAssignment_Batch_Test.accountNameTM LIMIT 1];
            
            //System.assertEquals(System.Today(),finalAccount.Customer_Owner_Changed_Date__c);
            //System.assertEquals(userAdmin.Id,finalAccount.OwnerId);
            //System.assertEquals(null, finalAccount.Service_RM__c);
            //System.assertEquals(null, finalAccount.Port_Pool__c);
            //System.assertEquals(null, finalAccount.Previous_Owner__c);
        }
        
    }

    static testMethod void yearEndAssignAccountOther(){
        Account targetAccount = [SELECT Id,Delete_Flag__c,OwnerId,Previous_Owner__c,CIS__c,Name FROM Account WHERE Name = :YearEndAssignment_Batch_Test.accountNameTM LIMIT 1];
        User userRM = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameRM LIMIT 1];
        User userAdmin = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameAdmin LIMIT 1];
        Year_End_Assignment__c yearEnd = new Year_End_Assignment__c(
            CIS_ID_Unique__c = targetAccount.Name,
            CIS_ID__c = targetAccount.Id,
            Final_Assigned_RM__c = userRM.Id,
            Status__c = GlobalConstants.SUBMITTED,
            Final_Refer_Out__c = true,
            Segment_Proposed__c = 'MB',
            Refer_Out_Reason__c = GlobalConstants.OTHER_SEGMENT
        );
        insert yearEnd;
        Test.startTest();
            Database.executeBatch(new YearEndAssignment_Batch());
        Test.stopTest();
        
        Account finalAccount = [SELECT Id,Service_RM__c,Delete_Flag__c,OwnerId,Previous_Owner__c,Port_Pool__c,Customer_Owner_Changed_Date__c,Primary_Segment_Code__c FROM Account WHERE Name = :YearEndAssignment_Batch_Test.accountNameTM LIMIT 1];
        
        //System.assertEquals(yearEnd.Segment_Proposed__c, finalAccount.Primary_Segment_Code__c);
        //System.assertEquals(System.Today(),finalAccount.Customer_Owner_Changed_Date__c);
        //System.assertEquals(userAdmin.Id,finalAccount.OwnerId);
        //System.assertEquals(null, finalAccount.Service_RM__c);
        //System.assertEquals(null, finalAccount.Port_Pool__c);
        //System.assertEquals(null, finalAccount.Previous_Owner__c);
    }

    static testMethod void yearEndAssignAccountNegativeCase(){
        Account targetAccount = [SELECT Id,Delete_Flag__c,OwnerId,Previous_Owner__c,CIS__c,Name FROM Account WHERE Name = :YearEndAssignment_Batch_Test.accountNameTM LIMIT 1];
        User userRM = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameRM LIMIT 1];
        User userTM = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameTM LIMIT 1];
        insert new Year_End_Assignment__c(
            CIS_ID_Unique__c = targetAccount.Name,
            CIS_ID__c = targetAccount.Id,
            Status__c = GlobalConstants.SUBMITTED
        );
        Test.startTest();
            Database.executeBatch(new YearEndAssignment_Batch());
        Test.stopTest();
        
        Account finalAccount = [SELECT Id,Delete_Flag__c,OwnerId,Previous_Owner__c,Port_Pool__c,Customer_Owner_Changed_Date__c FROM Account WHERE Name = :YearEndAssignment_Batch_Test.accountNameTM LIMIT 1];
        
        //System.assertEquals(null,finalAccount.Customer_Owner_Changed_Date__c);
        //System.assertEquals(userTM.Id,finalAccount.OwnerId);
        //System.assertEquals(null,finalAccount.Previous_Owner__c);
    }
}