objects/Account.object
<CustomObject>
    <fields>
        <fullName>CIS__c</fullName>
        <externalId>true</externalId>
        <label>CIS ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Count_Call_Report_RM__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Count RM Call Report</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Count_Contacted_Call_Report__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Count Contacted Call Report</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Visited__c</fullName>
        <label>Number of Visited</label>
        <summaryFilterItems>
            <field>Call_Report__c.Contact_Channel__c</field>
            <operation>equals</operation>
            <value>Face to Face</value>
        </summaryFilterItems>
        <summaryForeignKey>Call_Report__c.CIS_ID__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Ownership__c</fullName>
        <formula>CASE(Port_Pool__c, 
&quot;Port&quot;, &quot;Permanent&quot;, 
&quot;Pool&quot;,  CASE(Owner.Profile.Name,
                  &quot;SME-AH&quot;, &quot;Permanent&quot;,
                  &quot;SME-TM&quot;, IF(Temporary_Ownership_Flag__c, &quot;Temporary&quot;, &quot;Permanent&quot;),
                  &quot;SME-RM&quot;, &quot;Temporary&quot;, 
                  &quot;&quot;),                      
&quot;&quot;, IF(OR(Owner.Profile.Name = &quot;SME-RM&quot;,Owner.Profile.Name = &quot;SME-TM&quot;), &quot;Temporary&quot;, &quot;&quot;),
&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Ownership</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Port_Pool__c</fullName>
        <label>Port / Pool</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RC_Code__c</fullName>
        <formula>Owner.RC_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RC Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_RM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service RM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Call_Report__c.object
<CustomObject>
    <description>This object tracks the Call Plan and Call Report</description>
    <fields>
        <fullName>Ownership__c</fullName>
        <label>Ownership</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Port_Pool__c</fullName>
        <label>Port / Pool</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Call Plan / Call Report</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Call Plan / Call Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Plans / Call Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Monthly_Performance__c.object
<CustomObject>
    <description>To store user and team&apos;s monthly performance.</description>
    <fields>
        <fullName>Call_Report_Customer_Others__c</fullName>
        <label># Call Report Customer Others</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report_Customer_Pool__c</fullName>
        <label># Call Report Customer Pool</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report_Customer_Port__c</fullName>
        <label># Call Report Customer Port</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report__c</fullName>
        <label># Call Report</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report_for_Relationship__c</fullName>
        <label># Call Report for Relationship</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contacted_Customer_Other__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Contacted Customer in Other</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contacted_Customer_Pool__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Contacted Customer in Pool</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contacted_Customer_Port__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Contacted Customer in Port</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer_Other__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Customer in Others</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer_Pool__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Customer in Pool</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer_Port__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Customer in Port</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Face_to_Face__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Face to Face</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Months__c</fullName>
        <label># Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phone_Call__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Phone Call</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User_Extension__c</referenceTo>
        <relationshipLabel>Monthly Performance</relationshipLabel>
        <relationshipName>Monthly_Performance</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Monthly Performance</label>
    <nameField>
        <label>Month</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Performance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Team_Structure__c.object
<CustomObject>
    <fields>
        <fullName>Call_Report_Customer_Others__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Call Report Customer Others</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report_Customer_Pool__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Call Report Customer Pool</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report_Customer_Port__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Call Report Customer Port</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Call Report</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report_for_Relationship__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Call Report for Relationship</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contacted_Customer_Other__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Contacted Customer in Other</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contacted_Customer_Pool__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Contacted Customer in Pool</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contacted_Customer_Port__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Contacted Customer in Port</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer_Other__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Customer in Other</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer_Pool__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Customer in Pool</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer_Port__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Customer in Port</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Face_to_Face__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Face to Face</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Months__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phone_Call__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Phone Call</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RC_Code__c</fullName>
        <label>RC Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Team Structure</label>
    <nameField>
        <label>Team Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Structure</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>RC_Code__c</fullName>
        <label>RC Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/User_Extension__c.object
<CustomObject>
    <description>To store user&apos;s information.</description>
    <fields>
        <fullName>Call_Report_Customer_Others__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Call Report Customer Others</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report_Customer_Pool__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Call Report Customer Pool</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report_Customer_Port__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Call Report Customer Port</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Call Report</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report_for_Relationship__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Call Report for Relationship</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contacted_Customer_Other__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Contacted Customer in Other</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contacted_Customer_Pool__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Contacted Customer in Pool</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contacted_Customer_Port__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Contacted Customer in Port</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer_Other__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Customer in Other</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer_Pool__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Customer in Pool</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer_Port__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Customer in Port</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Face_to_Face__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Face to Face</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Months__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phone_Call__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Phone Call</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Team_Structure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>User Extension</relationshipLabel>
        <relationshipName>User_Extension</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Extension</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Extension</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SME_Performance_All_Batch.cls
global class SME_Performance_All_Batch implements Database.Batchable<sObject>, Database.Stateful{
    private String query;
    private Map<String,User_Extension__c> userMapExt;//user,ext
    private Set<String> userMapExtKeySet{get{return userMapExt.keySet();}}//user,ext
    private Map<String,Team_Structure__c> teamMap;

    private Boolean runMontly = false;
    private Boolean shouldRunMontly = true;
    private Boolean resetStatement = false;
    private Boolean initialMonthly = false;
    private Map<String,Monthly_Performance__c> monthlyMap;

    private Map<String,User_Extension__c> userExMap;
	private Map<String,List<String>> userExIdMapTeam;
	private Date todayDateFromNow;
    private Integer currentYear;
    private Map<String,String> callReportMapOwner;


    private SME_Performance_Util util;
    //global SME_Performance_All_Batch runMontlyAlso(){
    //	runMontly = true;
    //	monthlyMap = new Map<String,Monthly_Performance__c>();
    //	return this.runMontly();
    //}
    global SME_Performance_All_Batch() {
    	this.query = 'SELECT Id,CIS__c,Port_Pool__c,Ownership__c,OwnerId,Count_Call_Report_RM__c,Count_Contacted_Call_Report__c,Owner.ProfileId,Owner.Profile.Name,Service_RM__c,Service_RM__r.RC_Code__c,Service_RM__r.ProfileId,Service_RM__r.Profile.Name,Owner.RC_Code__c,Number_of_Visited__c FROM Account WHERE OwnerId IN :userMapExtKeySet';
    	// AND Owner.isActive=true
    	userExMap = new Map<String,User_Extension__c>([SELECT Id,Call_Report__c,Call_Report_Customer_Others__c,Call_Report_Customer_Pool__c,Call_Report_Customer_Port__c,Call_Report_for_Relationship__c,Contacted_Customer_Other__c,Contacted_Customer_Pool__c,Contacted_Customer_Port__c,Customer_Other__c,Customer_Pool__c,Customer_Port__c,Face_to_Face__c,Months__c,Phone_Call__c,Team_Structure__c,User__c,User__r.ProfileId,User__r.Profile.Name,User__r.RC_Code__c,User__r.Employee_Id__c,User__r.ManagerId,Total_visited_Customer__c,Contacted_Customer_Other_My_Penetrate__c,Contacted_Customer_Pool_My_Penetrate__c,Contacted_Customer_Port_My_Penetrate__c FROM User_Extension__c WHERE Team_Structure__c!=null]);

        teamMap = new Map<String,Team_Structure__c>([SELECT Id,Call_Report__c,Call_Report_Customer_Others__c,Call_Report_Customer_Pool__c,Call_Report_Customer_Port__c,Call_Report_for_Relationship__c,Call_Report_for_Sales__c,Contacted_Customer_Other__c,Contacted_Customer_Pool__c,Contacted_Customer_Port__c,Customer_Other__c,Customer_Pool__c,Customer_Port__c,Face_to_Face__c,Months__c,Phone_Call__c,Name,AH_Name__c,NH_Name__c,RC_Code__c,AH_RC_Code__c,NH_RC_Code__c,Total_visited_Customer__c,Contacted_Customer_Other_My_Penetrate__c,Contacted_Customer_Pool_My_Penetrate__c,Contacted_Customer_Port_My_Penetrate__c FROM Team_Structure__c]);

        util = new SME_Performance_Util(userExMap,teamMap);
        userMapExt = util.getUserExt();
    }
    global SME_Performance_All_Batch(Map<String,User_Extension__c> userExMap,Map<String,Team_Structure__c> teamMap) {
    	this.query = 'SELECT Id,CIS__c,Port_Pool__c,Ownership__c,OwnerId,Count_Call_Report_RM__c,Count_Contacted_Call_Report__c,Owner.ProfileId,Owner.Profile.Name,Service_RM__c,Service_RM__r.RC_Code__c,Service_RM__r.ProfileId,Service_RM__r.Profile.Name,Owner.RC_Code__c,Number_of_Visited__c FROM Account WHERE OwnerId IN :userMapExtKeySet AND Owner.isActive=true';
    	this.userExMap = userExMap;
		this.teamMap = teamMap;
        util = new SME_Performance_Util(userExMap,teamMap);
        userMapExt = util.getUserExt();
    }
    global SME_Performance_All_Batch noMontly(){
        shouldRunMontly = false;
        return this;
    }
    global SME_Performance_All_Batch runMontly(Map<String,Monthly_Performance__c> monthlyMap,Boolean resetStatement,Boolean initialMonthly){
    	runMontly = true;
        this.resetStatement = resetStatement;
        this.initialMonthly = initialMonthly;
    	util.setMonthlyMap(monthlyMap);

    	return this;
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
    	return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, list<Account> accountList) {
        List<Call_Report__c> callReportList = new List<Call_Report__c>();
        //owner+account
        callReportList = [SELECT Id,Current_Owner_Extension__c,Current_Owner_Extension__r.User__c,CIS_ID__c,CIS_ID__r.OwnerId FROM Call_Report__c WHERE CIS_ID__c IN :accountList AND Status__c='Contacted'];// AND Primary_Call_Report__c=true
       
        util.setCallReportList(callReportList);

    	for(Account eachAccount : accountList){
    		util.executeAccount(eachAccount,runMontly);
    	}
    }
    
    global void finish(Database.BatchableContext BC) {
    	update util.getFinalUserExt();
        util.finalTeamTask();
    	if(runMontly) {
            GlobalUtility.resetStatement = resetStatement;
    		//upsert monthlyMap.values() External_ID__c;
    		Database.executeBatch(new SME_Monthly_DML_Batch(util.getMonthly()),2000);

            //if(!initialMonthly)
    	}
    	
    	//Database.executeBatch(new SME_DML_Batch(util.getFinalTeam()),2000);
    	update util.getFinalTeam();
    }
}