objects/Account.object
<CustomObject>
    <fields>
        <fullName>AH_Name__c</fullName>
        <formula>Owner.AH_Name__c</formula>
        <label>AH Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Owner_Extension__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Owner Extension</label>
        <referenceTo>User_Extension__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>AccountsCurrentOwnerExtension</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Team_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Team Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Accounts (Current Team Name)</relationshipLabel>
        <relationshipName>AccountsCurrentTeamName</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delete_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Delete Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Port_Pool__c</fullName>
        <label>Port / Pool</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Previous_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Segment_Code__c</fullName>
        <label>Primary Segment Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <formula>CASE( Primary_Segment_Code__c,
&quot;UM&quot;, IMAGE(&quot;/resource/SMESegment&quot;,&quot;SME&quot;),
&quot;UR&quot;, IMAGE(&quot;/resource/SMESegment&quot;,&quot;SME&quot;),
&quot;SM&quot;, IMAGE(&quot;/resource/SMESegment&quot;,&quot;SME&quot;),
&quot;SR&quot;, IMAGE(&quot;/resource/SMESegment&quot;,&quot;SME&quot;),
&quot;LM&quot;, IMAGE(&quot;/resource/SMESegment&quot;,&quot;SME&quot;),
&quot;LR&quot;, IMAGE(&quot;/resource/SMESegment&quot;,&quot;SME&quot;),
IMAGE(&quot;/resource/Non_SME_Segment&quot;,&quot;Non-SME&quot;,60,90))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Segment</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Credit Status</label>
        <picklist>
            <picklistValues>
                <fullName>Good Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>SME_Customer</fullName>
        <active>true</active>
        <label>SME-Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Customer_Ownership_Request__c.object
<CustomObject>
    <description>This object tracks the on-going request for customer assignment via salesforce approval process</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approval In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CIS_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CIS ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Ownership Requests</relationshipLabel>
        <relationshipName>Customer_Ownership_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Not_SME_Segment_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Not SME Segment Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Port_Pool__c</fullName>
        <formula>CIS_ID__r.Port_Pool__c</formula>
        <label>CIS Port / Pool</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Refer_Out_Reason__c</fullName>
        <label>Refer Out Reason</label>
        <picklist>
            <controllingField>Request_Type__c</controllingField>
            <picklistValues>
                <fullName>TM Pool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wrong Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMLO List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exit Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Criminal Offense</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not SME Segment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Refer_Out_Segment__c</fullName>
        <label>Refer Out Segment</label>
        <picklist>
            <controllingField>Refer_Out_Reason__c</controllingField>
            <picklistValues>
                <fullName>CB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XS</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <label>Request Type</label>
        <picklist>
            <picklistValues>
                <fullName>Request Ownership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Release Ownership</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Want_to_request_for_ownership__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Want to request for ownership ?</label>
        <type>Checkbox</type>
    </fields>
    <label>Customer Ownership Request</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Ownership Requests</pluralLabel>
    <recordTypes>
        <fullName>Release_Ownership</fullName>
        <active>true</active>
        <description>Release Ownership - Before request for approval</description>
        <label>Release Ownership</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Master_Map__c.object
<CustomObject>
    <description>This object tracks Thailand&apos;s Province, District and Sub District. Being used by Year-end assignment and On-going customer request.</description>
    <fields>
        <fullName>Code__c</fullName>
        <externalId>true</externalId>
        <label>Code</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Master Map</label>
    <nameField>
        <label>Province Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Maps</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Team_Structure__c.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <picklist>
            <picklistValues>
                <fullName>Small</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Team Structure</label>
    <nameField>
        <label>Team Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Structure</pluralLabel>
    <recordTypes>
        <fullName>Area</fullName>
        <active>true</active>
        <label>Area</label>
    </recordTypes>
    <recordTypes>
        <fullName>Network</fullName>
        <active>true</active>
        <label>Network</label>
    </recordTypes>
    <recordTypes>
        <fullName>Team</fullName>
        <active>true</active>
        <label>Team</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is updated by DIH (HRIS): A = Active, I=Inactive</description>
        <label>Status Code</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/User_Extension__c.object
<CustomObject>
    <description>To store user&apos;s information.</description>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <formula>User__r.Segment__c</formula>
        <label>Segment</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team_Structure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>User Extension</relationshipLabel>
        <relationshipName>User_Extension</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Extension</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Extension</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Year_End_Assignment__c.object
<CustomObject>
    <description>This object tracks the re-assignment of customer to RM port / TM port or Pool, Refer out at the end of the year</description>
    <fields>
        <fullName>CIS_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CIS ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Assign_Port_Yearly</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Port_Pool__c</fullName>
        <label>Port / Pool</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Refer_Out_Reason__c</fullName>
        <label>Final Refer Out Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Reject</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wrong Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMLO List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exit Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Criminal Offense</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Segment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Refer_Out_Segment__c</fullName>
        <label>Final Refer Out Segment</label>
        <picklist>
            <picklistValues>
                <fullName>SM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Year-End Assignment</label>
    <nameField>
        <displayFormat>Ref-{00000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Year-End Assignment</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CustomerOwnershipRequest_Test.cls
/**
* @author komsan.wi@beryl8.com
* @16/07/2015 createddate
*/
@isTest
private class CustomerOwnershipRequest_Test {
	public static String accountNameTM = 'tmCreatedAccountName';
	public static String accountNameTMPer = 'tmCreatedAccountPer';
	public static String accountNameRMPer = 'accountNameRMPer';
	public static String accountNameRMPer1 = 'accountNameRMPer1';
	public static String accountNameRMPer2 = 'accountNameRMPer2';
	public static String userRcCode1 = '52215';
	public static String userRcCode2 = '52216';
	public static String targetFirstName1 = 'manualNhUserFirstName1';
	public static String targetLastName1 = 'manualNhUserLastName1';
	public static String targetFirstName2 = 'manualNhUserFirstName2';
	public static String targetLastName2 = 'manualNhUserLastName2';

	@testSetup static void setupAccount(){
        Mockup_Test mt = new Mockup_Test().setUpTestWithRCCode();
        System.runAs([SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameRM LIMIT 1][0]){
            mt.newAccount(accountNameRMPer,GlobalConstants.PORT,GlobalConstants.OWNERSHIP_PERMANENT,Mockup_Test.getRecordTypeAccountIdByName(GlobalConstants.SME_CUSTOMER));
            mt.newAccount(accountNameRMPer1,GlobalConstants.PORT,GlobalConstants.OWNERSHIP_PERMANENT,Mockup_Test.getRecordTypeAccountIdByName(GlobalConstants.SME_CUSTOMER));
            mt.newAccount(accountNameRMPer2,GlobalConstants.POOL,GlobalConstants.OWNERSHIP_PERMANENT,Mockup_Test.getRecordTypeAccountIdByName(GlobalConstants.SME_CUSTOMER));
        }
        System.runAs([SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameTM LIMIT 1][0]){
        	mt.newAccount(accountNameTMPer,GlobalConstants.POOL,GlobalConstants.OWNERSHIP_PERMANENT,Mockup_Test.getRecordTypeAccountIdByName(GlobalConstants.SME_CUSTOMER));
            mt.newAccount(accountNameTM,GlobalConstants.POOL,Mockup_Test.getRecordTypeAccountIdByName(GlobalConstants.SME_CUSTOMER));
            Mockup_Test.newAccountShare(
            	[SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameRM LIMIT 1][0].Id,
				[SELECT Id,Delete_Flag__c FROM Account WHERE Name = :CustomerOwnershipRequest_Test.accountNameTM LIMIT 1][0].Id,
				'edit',
				'edit'
            );
        }

        setupDataForTestReleaseOtherSegment();
	}

	private static void setupDataForTestReleaseOtherSegment(){
		User userRM = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameRM LIMIT 1];
		Account targetAccount = [SELECT Id FROM Account WHERE Name = :CustomerOwnershipRequest_Test.accountNameRMPer1 LIMIT 1];
		System.runAs(userRM){
			Customer_Ownership_Request__c customerRequestNew = new Customer_Ownership_Request__c(
				CIS_ID__c = targetAccount.Id,
				Request_Type__c = GlobalConstants.RELEASE_OWNERSHIP,
				Refer_Out_Reason__c = GlobalConstants.REASON_NOT_SME,
				Not_SME_Segment_Flag__c = false,
				Refer_Out_Segment__c = 'MB',
				Reason__c = 'reason'
			);
			insert customerRequestNew;
		}
		Customer_Ownership_Request__c customerRequest = [SELECT Id FROM Customer_Ownership_Request__c WHERE CIS_ID__c=:targetAccount.Id LIMIT 1];
		customerRequest.Approval_Status__c = GlobalConstants.APPROVED;
		update customerRequest;
	}
	/*@isTest static void sendRequestApprovalFromAction(){
		User userTM = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameTM LIMIT 1];
		User userRM = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameRM LIMIT 1];
		Account targetAccount = [SELECT Id,Delete_Flag__c FROM Account WHERE Name = :CustomerOwnershipRequest_Test.accountNameTM LIMIT 1];
		System.runAs(userRM){
			//insert new Customer_Ownership_Request__c(
			//		CIS_ID__c = targetAccount.Id,
			//		Request_Type__c = GlobalConstants.REQUEST_OWNERSHIP,
			//		Want_to_request_for_ownership__c = true
			//	);
			Mockup_Test.newCustomerRequest(targetAccount.Id,'Pending',userRM.Id,GlobalConstants.REQUEST_OWNERSHIP, GlobalConstants.PORT);
			Customer_Ownership_Request__c customerRequest = [SELECT Id FROM Customer_Ownership_Request__c WHERE CIS_ID__c=:targetAccount.Id LIMIT 1];
			Test.startTest();
				customerRequest.Approval_Status__c = GlobalConstants.APPROVED;
				update customerRequest;
			Test.stopTest();
		}
        Account finalAccount = [SELECT Id,OwnerId,Previous_Owner__c,Port_Pool__c FROM Account WHERE Name = :CustomerOwnershipRequest_Test.accountNameTM LIMIT 1];
        System.assertEquals(GlobalConstants.PORT,finalAccount.Port_Pool__c);
        System.assertEquals(userRM.Id,finalAccount.OwnerId);
        System.assertEquals(userTM.Id,finalAccount.Previous_Owner__c);
	}

	@isTest static void sendReleaseApprovalFromAction(){
		User userTM = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameTM LIMIT 1];
		User userRM = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameRM LIMIT 1];
		Account targetAccount = [SELECT Id,Delete_Flag__c FROM Account WHERE Name = :CustomerOwnershipRequest_Test.accountNameTM LIMIT 1];
		System.runAs(userTM){
			insert new Customer_Ownership_Request__c(
					CIS_ID__c = targetAccount.Id,
					Request_Type__c = GlobalConstants.RELEASE_OWNERSHIP,
					Want_to_request_for_ownership__c = true
				);
			Mockup_Test.newCustomerRequest(targetAccount.Id,'Pending',userRM.Id,GlobalConstants.RELEASE_OWNERSHIP, GlobalConstants.PORT);
			Customer_Ownership_Request__c customerRequest = [SELECT Id FROM Customer_Ownership_Request__c WHERE CIS_ID__c=:targetAccount.Id LIMIT 1];
			Test.startTest();
				customerRequest.Approval_Status__c = GlobalConstants.APPROVED;
				update customerRequest;
			Test.stopTest();
		}
	}
	@isTest static void changeOwnerWhenApproved(){
		User userTM = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameTM LIMIT 1];
		User userRM = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameRM LIMIT 1];
		Account targetAccount = [SELECT Id,Delete_Flag__c FROM Account WHERE Name = :CustomerOwnershipRequest_Test.accountNameTM LIMIT 1];
		System.runAs(userRM){
			Mockup_Test.newCustomerRequest(targetAccount.Id,'Pending',userRM.Id,GlobalConstants.REQUEST_OWNERSHIP, GlobalConstants.PORT);
			Customer_Ownership_Request__c customerRequest = [SELECT Id FROM Customer_Ownership_Request__c WHERE CIS_ID__c=:targetAccount.Id LIMIT 1];
			Test.startTest();
				customerRequest.Approval_Status__c = GlobalConstants.APPROVED;
				update customerRequest;
			Test.stopTest();
		}
        Account finalAccount = [SELECT Id,Delete_Flag__c,OwnerId,Previous_Owner__c,Port_Pool__c FROM Account WHERE Name = :CustomerOwnershipRequest_Test.accountNameTM LIMIT 1];
        System.assertEquals(GlobalConstants.PORT,finalAccount.Port_Pool__c);
        System.assertEquals(userRM.Id,finalAccount.OwnerId);
        System.assertEquals(userTM.Id,finalAccount.Previous_Owner__c);
	}*/

	@isTest static void releaseOtherSegment(){
		Account accountPer = [SELECT Id,Primary_Segment_Code__c FROM Account WHERE Name = :CustomerOwnershipRequest_Test.accountNameRMPer1 LIMIT 1];
        accountPer.Primary_Segment_Code__c = 'MB';
        update accountPer;

        Account finalAccount = [SELECT Id, Owner.Profile.Name FROM Account WHERE Name = :CustomerOwnershipRequest_Test.accountNameRMPer1 LIMIT 1];
        System.assertEquals('SME-Admin',finalAccount.Owner.Profile.Name);
	}

	@isTest static void releaseWrongAreaWithNH(){
		String expectedOwnerNameResult = targetFirstName1 + ' ' + targetLastName1;
		User userRM = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameRM LIMIT 1];
		Account releaseAccount = [SELECT Id ,Current_Owner_Extension__r.Name,Current_Team_Name__r.External_ID__c FROM Account WHERE Name = :CustomerOwnershipRequest_Test.accountNameRMPer LIMIT 1];
		
		System.assertEquals(null,releaseAccount.Current_Owner_Extension__r.Name);
		System.assertNotEquals(userRcCode1,releaseAccount.Current_Team_Name__r.External_ID__c);

		Test.startTest();
			Profile nhProfile = [SELECT Id, Name FROM Profile WHERE Name = :GlobalConstants.SME_NH LIMIT 1];

			Team_Structure__c tsNh = new Team_Structure__c(
				AH_Name__c = null,
				RC_Code__c = Mockup_Test.NH_RC_CODE,
				External_ID__c = userRcCode1
			);
			insert tsNh;

			User manualNhUser = Mockup_Test.newUser(
		            targetFirstName1,
			    	targetLastName1,
		            true,
		            targetFirstName1 +'@mail.com',
		            targetFirstName1 +'@mail.com',
		            targetFirstName1.substring(0, 4),
		            nhProfile.Id,
		            null,
		            null,
		            'MANUAL_MOCK001'
		    );
		    manualNhUser.RC_Code__c = userRcCode1;
		    manualNhUser.NH_RC_Code__c = Mockup_Test.NH_RC_CODE;
		    manualNhUser.Job_Code__c = 'ME1A';
		    manualNhUser.Status__c = 'A';
		    insert manualNhUser;
		Test.stopTest();

		Team_Structure__c tempTs = [SELECT Id,Name FROM Team_Structure__c WHERE External_ID__c =:userRcCode1];
		Master_Map__c mapObject = new Master_Map__c(
			Code__c = '77667',
			Type__c = 'test type'
		);
		insert mapObject;
		
		System.runAs(userRM){
			Customer_Ownership_Request__c customerRequestNew = new Customer_Ownership_Request__c(
				CIS_ID__c = releaseAccount.Id,
				Request_Type__c = GlobalConstants.RELEASE_OWNERSHIP,
				Refer_Out_Reason__c = GlobalConstants.REASON_WRONG_AREA,
				Not_SME_Segment_Flag__c = false,
				Refer_Out_Segment__c = 'ME',
				Reason__c = 'reason',
				Refer_Out_Team__c = tempTs.Name,
				Refer_Out_Area__c = mapObject.Id
			);
			insert customerRequestNew;
		}

		Customer_Ownership_Request__c customerRequest = [SELECT Id,Current_Owner__r.Name FROM Customer_Ownership_Request__c WHERE CIS_ID__c=:releaseAccount.Id LIMIT 1];
		customerRequest.Approval_Status__c = GlobalConstants.APPROVED;
		update customerRequest;		

        Account finalAccount = [SELECT Id, Name, Current_Owner_Extension__r.Name,Current_Team_Name__r.External_ID__c FROM Account WHERE Name = :CustomerOwnershipRequest_Test.accountNameRMPer LIMIT 1];
        
        System.assertEquals(expectedOwnerNameResult,finalAccount.Current_Owner_Extension__r.Name);
        System.assertEquals(userRcCode1,finalAccount.Current_Team_Name__r.External_ID__c);
	}

	@isTest static void releaseTmPool(){
		User userTM = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameTM LIMIT 1];
		User userRM = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameRM LIMIT 1];
		Account releaseAccount = [SELECT Id,OwnerId FROM Account WHERE Name = :CustomerOwnershipRequest_Test.accountNameRMPer LIMIT 1];
		
		System.assertEquals(userRM.Id,releaseAccount.OwnerId);

		System.runAs(userRM){
			Customer_Ownership_Request__c customerRequestNew = new Customer_Ownership_Request__c(
				CIS_ID__c = releaseAccount.Id,
				Request_Type__c = GlobalConstants.RELEASE_OWNERSHIP,
				Refer_Out_Reason__c = 'TM Pool',
				Not_SME_Segment_Flag__c = false,
				Reason__c = 'reason'
			);
			insert customerRequestNew;

			Customer_Ownership_Request__c customerRequest = [SELECT Id,Current_Owner__r.Name FROM Customer_Ownership_Request__c WHERE CIS_ID__c=:releaseAccount.Id LIMIT 1];
			customerRequest.Approval_Status__c = GlobalConstants.APPROVED;
			update customerRequest;
		}

        Account finalAccount = [SELECT Id, Name, OwnerId FROM Account WHERE Name = :CustomerOwnershipRequest_Test.accountNameRMPer LIMIT 1];
        
        System.assertEquals(userTM.Id,finalAccount.OwnerId);
	}

	@isTest static void requestTmPoolAccountPool(){
		User userTM = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameTM LIMIT 1];
		User userRM = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameRM LIMIT 1];
		Account releaseAccount = [SELECT Id,OwnerId FROM Account WHERE Name = :CustomerOwnershipRequest_Test.accountNameRMPer2 LIMIT 1];
		
		System.assertEquals(userRM.Id,releaseAccount.OwnerId);

		System.runAs(userRM){
			Customer_Ownership_Request__c customerRequestNew = new Customer_Ownership_Request__c(
				CIS_ID__c = releaseAccount.Id,
				Request_Type__c = GlobalConstants.REQUEST_OWNERSHIP,
				Request_Ownership_Type__c = GlobalConstants.POOL,
				Not_SME_Segment_Flag__c = false,
				Reason__c = 'reason'
			);
			insert customerRequestNew;

			Customer_Ownership_Request__c customerRequest = [SELECT Id,Current_Owner__r.Name FROM Customer_Ownership_Request__c WHERE CIS_ID__c=:releaseAccount.Id LIMIT 1];
			customerRequest.Approval_Status__c = GlobalConstants.APPROVED;
			update customerRequest;
		}

        Account finalAccount = [SELECT Id, Name, OwnerId, Permanent_Owner__c,Port_Pool__c FROM Account WHERE Name = :CustomerOwnershipRequest_Test.accountNameRMPer2 LIMIT 1];
        
        System.assertEquals(userRM.Id,finalAccount.OwnerId);
        System.assertEquals(GlobalConstants.POOL,finalAccount.Port_Pool__c);
	}
	@isTest static void releaseWrongAreaStatusApprovalInProgress(){
		//TriggerHandler.bypass('TeamStructureTriggerHandler');
		String expectedOwnerNameResult = targetFirstName1 + ' ' + targetLastName1;

		User userRM = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameRM LIMIT 1];
		Account releaseAccount = [SELECT Id ,Current_Owner_Extension__r.Name,Current_Team_Name__r.External_ID__c FROM Account WHERE Name = :CustomerOwnershipRequest_Test.accountNameRMPer LIMIT 1];
		
		System.assertEquals(null,releaseAccount.Current_Owner_Extension__r.Name);
		System.assertNotEquals(userRcCode1,releaseAccount.Current_Team_Name__r.External_ID__c);

		Test.startTest();
			Profile ahProfile = [SELECT Id, Name FROM Profile WHERE Name = :GlobalConstants.SME_AH LIMIT 1];
			Profile rmProfile = [SELECT Id, Name FROM Profile WHERE Name = :GlobalConstants.SME_RM LIMIT 1];

			Team_Structure__c tsAh = new Team_Structure__c(
				AH_Name__c = null,
				RC_Code__c = Mockup_Test.AH_RC_CODE,
				External_ID__c = userRcCode1,
				Name = 'Ah Team 1',
                Segment__c = GlobalConstants.SEGMENT_SE,
                Type__c = 'Area'
			);
			insert tsAh;

			Team_Structure__c tsNh = new Team_Structure__c(
				AH_Name__c = null,
				RC_Code__c = Mockup_Test.NH_RC_CODE,
				External_ID__c = userRcCode2,
				Name = 'เครือข่ายลูกค้าผู้ประกอบการ 2 Team 1',
                Segment__c = GlobalConstants.SEGMENT_SE,
                Type__c = 'Network'
			);
			insert tsNh;

			User manualAhUser = Mockup_Test.newUser(
		            targetFirstName1,
			    	targetLastName1,
		            true,
		            targetFirstName1 +'@mail.com',
		            targetFirstName1 +'@mail.com',
		            targetFirstName1.substring(0, 4),
		            ahProfile.Id,
		            null,
		            null,
		            'MANUAL_MOCK001'
		    );
		    manualAhUser.RC_Code__c = userRcCode1;
		    manualAhUser.AH_RC_Code__c = Mockup_Test.AH_RC_CODE;
		    manualAhUser.Job_Code__c = 'ME1A';
		    manualAhUser.Status__c = 'A';
		    insert manualAhUser;

		    User manualRmUser2 = Mockup_Test.newUser(
		            targetFirstName2,
			    	targetLastName2,
		            true,
		            targetFirstName2 +'@mail.com',
		            targetFirstName2 +'@mail.com',
		            targetFirstName2.substring(0, 4),
		            rmProfile.Id,
		            null,
		            manualAhUser.Id,
		            'MANUAL_MOCK002'
		    );
		    manualRmUser2.RC_Code__c = userRcCode2;
		    manualRmUser2.AH_RC_Code__c = Mockup_Test.AH_RC_CODE;
		    manualRmUser2.Job_Code__c = 'ME1A';
		    manualRmUser2.Status__c = 'A';
		    insert manualRmUser2;

		Test.stopTest();

		Team_Structure__c tempTs = [SELECT Id,Name FROM Team_Structure__c WHERE External_ID__c =:userRcCode1];

		System.runAs(userRM){	
			Master_Map__c mapObject = new Master_Map__c(
				Code__c = '77667',
				Type__c = 'test type'
			);
			insert mapObject;
			Customer_Ownership_Request__c customerRequestNew = new Customer_Ownership_Request__c(
				CIS_ID__c = releaseAccount.Id,
				Request_Type__c = GlobalConstants.RELEASE_OWNERSHIP,
				Refer_Out_Reason__c = GlobalConstants.REASON_WRONG_AREA,
				Not_SME_Segment_Flag__c = false,
				Refer_Out_Segment__c = 'ME',
				Reason__c = 'reason',
				Refer_Out_Team__c = tempTs.Name,
				Refer_Out_Area__c = mapObject.Id
			);
			insert customerRequestNew;
		}
		Team_Structure__c defaultTs = [SELECT Id,Name FROM Team_Structure__c WHERE External_ID__c =:userRcCode2];
				
		Customer_Ownership_Request__c customerRequest = [SELECT Id,Current_Owner__r.Name FROM Customer_Ownership_Request__c WHERE CIS_ID__c=:releaseAccount.Id LIMIT 1];
		
		customerRequest.Approval_Status__c = 'Approval In Progress';
		customerRequest.Refer_Out_Team__c = defaultTs.Name;
		update customerRequest;		

        Customer_Ownership_Request__c customerRequestResult = [SELECT Id,Current_Owner__r.Name,Current_Owner_TM__r.Name,Current_Owner_AH__r.Name,Current_Owner_NH__r.Name FROM Customer_Ownership_Request__c WHERE CIS_ID__c=:releaseAccount.Id LIMIT 1];
		
        System.assertEquals(expectedOwnerNameResult,customerRequestResult.Current_Owner__r.Name);
        System.assertEquals(expectedOwnerNameResult,customerRequestResult.Current_Owner_TM__r.Name);
        System.assertEquals(null,customerRequestResult.Current_Owner_AH__r.Name);
        System.assertEquals(null,customerRequestResult.Current_Owner_NH__r.Name);
	}

	//@isTest static void changeOwnerWhenApproved2(){
	//	User userTM = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameTM LIMIT 1];
	//	User userRM = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameRM LIMIT 1];
	//	User userAH = [SELECT Id FROM User WHERE Firstname=:Mockup_Test.userFirstNameAH LIMIT 1];
	//	Account targetAccount = [SELECT Id,Delete_Flag__c FROM Account WHERE Name = :CustomerOwnershipRequest_Test.accountNameTM LIMIT 1];
	//	System.runAs(userAH){
	//		Mockup_Test.newCustomerRequest(targetAccount.Id,'Pending',userRM.Id,GlobalConstants.REQUEST_OWNERSHIP, GlobalConstants.PORT);
	//		Customer_Ownership_Request__c customerRequest = [SELECT Id FROM Customer_Ownership_Request__c WHERE CIS_ID__c=:targetAccount.Id LIMIT 1];
	//		Year_End_Assignment__c yearEnd = new Year_End_Assignment__c();
	//		yearEnd.CIS_ID_Unique__c = [SELECT Id,Name FROM Account WHERE Name=:accountNameTM][0].Name;
 //   		yearEnd.CIS_ID__c = [SELECT Id FROM Account WHERE Name=:accountNameTM][0].Id;
	//		insert yearEnd;

	//		Test.startTest();
	//			customerRequest.Approval_Status__c = GlobalConstants.APPROVED;
	//			customerRequest.Year_End_Assignment__c = yearEnd.Id;
	//			customerRequest.Requestor_AH__c = userAH.Id;
	//			update customerRequest;
	//		Test.stopTest();
		
	//		Customer_Ownership_Request__c customerOwnerReq = [SELECT Requestor_AH__c FROM Customer_Ownership_Request__c WHERE Year_End_Assignment__c = :yearEnd.Id LIMIT 1];
	//		Year_End_Assignment__c finalYE = [SELECT Id, OwnerId FROM Year_End_Assignment__c LIMIT 1][0];
	//        Account finalAccount = [SELECT Id,Delete_Flag__c,OwnerId,Previous_Owner__c,Port_Pool__c FROM Account WHERE Name = :CustomerOwnershipRequest_Test.accountNameTM LIMIT 1];
	//        //System.assertEquals(userRM.Id,finalAccount.OwnerId);
	//        //System.assertEquals(userTM.Id,finalAccount.Previous_Owner__c);
	//        System.assertEquals(finalYE.OwnerId, customerOwnerReq.Requestor_AH__c);
	//	}
	//}
}