objects/Account.object
<CustomObject>
    <fields>
        <fullName>Birthdate_Registration_Date__c</fullName>
        <label>Birthdate / Registration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CIS__c</fullName>
        <externalId>true</externalId>
        <label>CIS ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Identification_No_Prospect__c</fullName>
        <inlineHelpText>Identification Number or Registration Number</inlineHelpText>
        <label>Identification No.</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Reschedule__c</fullName>
        <label>Number of Reschedule</label>
        <summarizedField>Call_Report__c.Number_of_Reschedule__c</summarizedField>
        <summaryForeignKey>Call_Report__c.CIS_ID__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Call_Report__c.object
<CustomObject>
    <description>This object tracks the Call Plan and Call Report</description>
    <fields>
        <fullName>Actual_Visit_Date__c</fullName>
        <defaultValue>IF(CONTAINS($RecordType.DeveloperName,&quot;CallReport&quot;),TODAY(),NULL)</defaultValue>
        <inlineHelpText>ห้ามเกินกว่าวันปัจจุบัน</inlineHelpText>
        <label>Actual Visit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CIS_ID__c</fullName>
        <label>CIS ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call Plans / Call Reports</relationshipLabel>
        <relationshipName>Call_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Channel__c</fullName>
        <label>Contact Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Face to Face</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone Call</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>เลือกบุคคลผู้ติดต่อที่มีอยู่แล้ว</inlineHelpText>
        <label>Existing Contact Person</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.CIS_ID__c</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Call Plans / Call Reports</relationshipLabel>
        <relationshipName>Call_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expected_Credit_Amount__c</fullName>
        <label>Expected Credit Amount (Baht)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Number_of_Reschedule__c</fullName>
        <label>Number of Reschedule</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Offer_Credit_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Offer Credit Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Offer_Interest__c</fullName>
        <label>Offer Interest</label>
        <picklist>
            <controllingField>Offer_Credit_Product__c</controllingField>
            <picklistValues>
                <fullName>Interest and can apply</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interest with condition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cannot apply</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer not interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interested with condition</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Existing Phone Number</label>
        <length>20</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Plan_Date__c</fullName>
        <label>Plan Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <picklist>
            <controllingField>Offer_Interest__c</controllingField>
            <picklistValues>
                <fullName>2.1 รอตัดสินใจ/รอปรึกษาครอบครัว</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.2 สนใจแต่รอแก้ปัญหาเรื่องหลักประกัน</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.3 สนใจแต่มีประเด็นต่อรองเกี่ยวกับดอกเบี้ย / ค่าธรรมเนียม</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.4 สนใจแต่ไม่ใช่ในช่วงเดือนนี้</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.5 สนใจแต่มีประเด็นต่อรองเกี่ยวกับประกันชีวิต</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.6 สนใจแต่วงเงินที่เสนอไม่เพียงพอ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.7 อื่น ๆ (โปรดระบุ)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.1 Refer ให้ผู้อื่นดำเนินการ (ระบุในหมายเหตุ)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.2 ที่อยู่ และเบอร์โทรศัพท์ไม่ถูกต้อง / ไม่มีข้อมูล/ ติดต่อไม่ได้</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.3 เพิ่งขอสินเชื่อไม่ถึง 3 เดือน</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.4 ลูกค้าคุณสมบัติไม่ดี / ไม่ผ่านหลักเกณฑ์ธนาคาร (ระบุในหมายเหตุ)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.5 ลูกค้าไม่ให้เข้าพบ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.6 เสียชีวิต / เลิกกิจการ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.7 หลักประกันไม่ผ่านเกณฑ์</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.8 อื่น ๆ (โปรดระบุ)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.1 มีเงินคงเหลือในบัญชีสูงหรือวงเงินเป็นตัวดำ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.2 ติดเรื่องค่าใช้จ่ายในการดำเนินการ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.3 ยอดขายกิจการลดลง</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.4 ตัดออกจากรายชื่อ Lead (ระยะเวลา 6 เดือน)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.5 ขอในนามบุคคล/บริษัทอื่น (โปรดระบุ CIS/เลขบัตรประชาชนหรือเลขทะเบียนการค้า)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.6 อื่น ๆ (โปรดระบุ)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Call Plan / Call Report</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Call Plan / Call Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Plans / Call Reports</pluralLabel>
    <recordTypes>
        <fullName>CallReport</fullName>
        <active>true</active>
        <description>with Call Plan section</description>
        <label>Call Report</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CallReport_Task_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Reminder Task setting for Call report , field Offer Interest equal Interest with condition.</description>
    <fields>
        <fullName>ReminderTask_NumOfDays__c</fullName>
        <description>for set duedate of reminder task from create call report plus this value</description>
        <label>ReminderTask_NumOfDays</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ReminderTask_Subject__c</fullName>
        <label>ReminderTask_Subject</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReminderTask_TimeReminder__c</fullName>
        <description>Time to Reminder Task when create Call Report</description>
        <inlineHelpText>Please use format HH:MM Ex. 08:00</inlineHelpText>
        <label>ReminderTask_TimeReminder</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>CallReport_Task_Setting</label>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CIS_ID__c</fullName>
        <formula>Account.CIS__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CIS ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <inlineHelpText>Phone format must be in number with 9 or 10 digits</inlineHelpText>
        <label>Phone Number</label>
        <length>20</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CallReportTrigger_Test.cls
@isTest
//@08/04/2016 Nareerat.wo@kbtg.tech   Add test code for Test method insertingTask_InterestWithCondition at class CallReportTriggerHandler .
private class CallReportTrigger_Test {
    
    @isTest static void testFirstReschedule() {
        Integer expectedNumOfReschedule = 1;
        // Implement test code
        Account acc = new Account();
        //acc.RecordTypeId = CustomerRecordTypeId;
        acc.Name = 'TestName';
        insert acc;

        Call_Report__c callReport = new Call_Report__c();
        callReport.CIS_ID__c = acc.Id;
        insert callReport;

        Test.startTest();
        callReport.Plan_Date__c = Date.today();
        update callReport;
        Test.stopTest();

        Call_Report__c actualQueryReport = [SELECT Id,Number_of_Reschedule__c FROM Call_Report__c WHERE Id = :callReport.Id];
        System.assertEquals(expectedNumOfReschedule,actualQueryReport.Number_of_Reschedule__c);
    }    

    @isTest static void testSecondReschedule() {
        Integer expectedNumOfReschedule = 2;
        // Implement test code
        Account acc = new Account();
        //acc.RecordTypeId = CustomerRecordTypeId;
        acc.Name = 'TestName';
        insert acc;

        Call_Report__c callReport = new Call_Report__c();
        callReport.CIS_ID__c = acc.Id;
        callReport.Number_of_Reschedule__c = 1;
        insert callReport;

        Test.startTest();
        callReport.Plan_Date__c = Date.today();
        update callReport;
        Test.stopTest();

        Call_Report__c actualQueryReport = [SELECT Id,Number_of_Reschedule__c FROM Call_Report__c WHERE Id = :callReport.Id];
        System.assertEquals(expectedNumOfReschedule,actualQueryReport.Number_of_Reschedule__c);
    }

    @isTest static void testRescheduleResetDate() {
        Integer expectedNumOfReschedule = 3;
        // Implement test code
        Account acc = new Account();
        //acc.RecordTypeId = CustomerRecordTypeId;
        acc.Name = 'TestName';
        insert acc;

        Call_Report__c callReport = new Call_Report__c();
        callReport.CIS_ID__c = acc.Id;
        callReport.Number_of_Reschedule__c = 2;
        callReport.Plan_Date__c = Date.today();
        insert callReport;

        Test.startTest();
        callReport.Plan_Date__c = null;
        update callReport;
        Test.stopTest();

        Call_Report__c actualQueryReport = [SELECT Id,Number_of_Reschedule__c FROM Call_Report__c WHERE Id = :callReport.Id];
        System.assertEquals(expectedNumOfReschedule,actualQueryReport.Number_of_Reschedule__c);
    }
    
    
    //@isTest static void testInsertCallReport_CreateReminderTask() {
    //    /*
    //     * Created by: nareerat.wo@kbtg.tech
    //     * Created date: 08-Apr-2016
    //     * Description: Test code for Test method insertingTask_InterestWithCondition at class CallReportTriggerHandler when insert call report.
    //    */
    //    //Setup custom setting
    //    CallReport_Task_Setting__c cSetting = new CallReport_Task_Setting__c();
    //    cSetting.ReminderTask_NumOfDays__c= 30;
    //    cSetting.ReminderTask_Subject__c='Please takecare customer';
    //    cSetting.ReminderTask_TimeReminder__c='08:30';
    //    insert cSetting;
        
    //    Account acc = new Account();
    //    acc.Name = 'TestAcc1';
    //    insert acc;

    //    Call_Report__c callReport = new Call_Report__c();
    //    callReport.CIS_ID__c = acc.Id;
    //    callReport.Actual_Visit_Date__c = Date.today();
    //    callReport.Contact_Channel__c = 'Phone Call';
    //    callReport.Offer_Credit_Product__c = true;
    //    callReport.Offer_Interest__c = 'Interest with condition';
    //    callReport.Reason__c = '2.1 รอตัดสินใจ/รอปรึกษาครอบครัว';           

    //    Test.startTest();
    //        insert callReport;
    //    Test.stopTest();

    //    task reminderTask = [SELECT Id, WhatId, Subject, OwnerId FROM Task WHERE WhatId = :callReport.Id];
    //    list<task> listreminderTask = [SELECT Id, WhatId, Subject, OwnerId FROM Task WHERE WhatId = :callReport.Id];
    //    System.assertEquals(listreminderTask.size(), 1);
    //    System.assertEquals(reminderTask.Subject, 'Please takecare customer');
        
    //}
    
    //@isTest static void testUpdateCallReport_CreateReminderTask() {
    //     /*
    //     * Created by: nareerat.wo@kbtg.tech
    //     * Created date: 08-Apr-2016
    //     * Description: Test code for Test method insertingTask_InterestWithCondition at class CallReportTriggerHandler when update call report.
    //    */
    //    //Setup custom setting
    //    CallReport_Task_Setting__c cSetting = new CallReport_Task_Setting__c();
    //    cSetting.ReminderTask_NumOfDays__c= 30;
    //    cSetting.ReminderTask_Subject__c='Please takecare customer';
    //    insert cSetting;
        
    //    Account acc = new Account();
    //    acc.Name = 'TestAcc1';
    //    acc.CIS__c = '1111';
    //    acc.Birthdate_Registration_Date__c = system.today() - 9000;
    //    acc.Identification_No_Prospect__c='1234567890123';
        
        
    //    insert acc;
        
    //    Contact contact1 = new Contact();
    //    contact1.Accountid = acc.id;
    //    contact1.Phone_Number__c = '1234567890';
    //    contact1.lastname='BB';
    //    insert contact1;

    //    Call_Report__c callReport = new Call_Report__c();
    //    callReport.CIS_ID__c = acc.Id;
    //    callReport.Actual_Visit_Date__c = Date.today();
    //    callReport.Contact_Channel__c = 'Phone Call';
    //    callReport.Offer_Credit_Product__c = true;
    //    callReport.Offer_Interest__c = 'Interest and can apply';       
    //    callReport.Expected_Credit_Amount__c = 100000;
    //    insert callReport;
                
    //    Test.startTest();
    //        callReport.Contact__c=contact1.id;
    //        callReport.Offer_Interest__c = 'Interest with condition';
    //        callReport.Reason__c = '2.1 รอตัดสินใจ/รอปรึกษาครอบครัว';  
    //        update callReport;
            
    //    Test.stopTest();

    //    task reminderTask = [SELECT Id, WhatId, Subject, OwnerId FROM Task WHERE WhatId = :callReport.Id];
    //    list<task> listreminderTask = [SELECT Id, WhatId, Subject, OwnerId FROM Task WHERE WhatId = :callReport.Id];
    //    System.assertEquals(listreminderTask.size(), 1);
    //    System.assertEquals(reminderTask.Subject, 'Please takecare customer');
        
    //}
    
    
    
}