objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Credit Status</label>
        <picklist>
            <picklistValues>
                <fullName>Good Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Call_Report__c.object
<CustomObject>
    <description>This object tracks the Call Plan and Call Report</description>
    <fields>
        <fullName>CIS_ID__c</fullName>
        <label>CIS ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call Plans / Call Reports</relationshipLabel>
        <relationshipName>Call_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Collect_Documents__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Collect Documents</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Negotiation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Negotiation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Offer_Credit_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Offer Credit Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Offer_Interest__c</fullName>
        <label>Offer Interest</label>
        <picklist>
            <controllingField>Offer_Credit_Product__c</controllingField>
            <picklistValues>
                <fullName>Interest and can apply</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interest with condition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cannot apply</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer not interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interested with condition</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Call Plan / Call Report</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Call Plan / Call Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Plans / Call Reports</pluralLabel>
    <recordTypes>
        <fullName>CallReport</fullName>
        <active>true</active>
        <description>with Call Plan section</description>
        <label>Call Report</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Call_Report_Lead__c.object
<CustomObject>
    <description>This object tracks the Lead associated to Call Plan/Call Report</description>
    <fields>
        <fullName>Call_Plan_Call_Report__c</fullName>
        <label>Call Plan / Call Report</label>
        <referenceTo>Call_Report__c</referenceTo>
        <relationshipName>Leads</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT(Target_List__r.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target List</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Target_List__c.Lead_Campaign__r.Status</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>Target_List__c.Lead_Campaign__r.Sub_Type__c</field>
                <operation>notEqual</operation>
                <value>Value Chain</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Target_List__c</referenceTo>
        <relationshipLabel>Call Reports / Leads</relationshipLabel>
        <relationshipName>Associated_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Call Report / Lead</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Reports / Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Call_Report_Opportunity__c.object
<CustomObject>
    <description>This object track the relationship between Call Report and Opportunity for the many to many relationship</description>
    <fields>
        <fullName>Call_Plan_Call_Report__c</fullName>
        <label>Call Plan / Call Report</label>
        <referenceTo>Call_Report__c</referenceTo>
        <relationshipName>Call_Report_Opportunity</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Offer_Interest__c</fullName>
        <formula>TEXT(Call_Plan_Call_Report__r.Offer_Interest__c) &amp; &quot; - &quot; &amp;  TEXT(Call_Plan_Call_Report__r.Reason__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Offer Interest</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.OwnerId</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Call Reports / Opportunities</relationshipLabel>
        <relationshipName>Call_Report_Opportunity</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT( Call_Plan_Call_Report__r.Status__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Call Report / Opportunity</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Reports / Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CIS_ID__c</fullName>
        <formula>Account.Name</formula>
        <label>CIS ID</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity_Lead__c.object
<CustomObject>
    <description>This object tracks the Lead associated to Opportunity</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities / Leads</relationshipLabel>
        <relationshipName>Opportunities_Leads</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT(Target_List__r.Status__c)</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_List__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Target List</label>
        <referenceTo>Target_List__c</referenceTo>
        <relationshipLabel>Opportunities / Leads</relationshipLabel>
        <relationshipName>Opportunities_Leads</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Opportunity / Lead</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities / Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Target_List__c.object
<CustomObject>
    <description>This object tracks the list of Targeted Lead and Campaign Member list</description>
    <fields>
        <fullName>CIS_ID_Prospect_Name__c</fullName>
        <label>CIS ID / Prospect Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Campaign_Members_Leads</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Lead_Campaign__c</fullName>
        <label>Lead/Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Target Lists</relationshipLabel>
        <relationshipName>Campaign_Members_Leads</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Target Lists</relationshipLabel>
        <relationshipName>Target_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Done</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Interested This Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>App In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interested but not register</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stock Negotiation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Create Write Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Credit Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case is Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Credit Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial Loan Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Loan Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Target List</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CampaignLead_Service.cls
public class CampaignLead_Service {
	public static void updateTargetlistStatusFromLatestOpp(List<Target_List__c> updateTargetList) {
        Set<String> recordTypeSet = new Set<String>{
            GlobalConstants.CALL_REPORT_NO_PLAN_DEVNAME,
            GlobalConstants.CALL_REPORT_DEVNAME,
            GlobalConstants.SECONDARY_CALL_REPORT_MAIN_BORROWER_NO_PLAN_DEVNAME,
            GlobalConstants.SECONDARY_CALL_REPORT_NO_PLAN_DEVNAME
        };
        Set<Id> accountIds = new Set<Id>();
        for(Target_List__c eachTarget : updateTargetList) {
            if(eachTarget.CIS_ID_Prospect_Name__c != null)
                accountIds.add(eachTarget.CIS_ID_Prospect_Name__c);
        }
        Set<Id> oppIds = new Set<Id>();
        Map<Id, Account> targetAccountMap = new Map<Id, Account>([SELECT Id, (SELECT Id, StageName, CreatedDate FROM Opportunities ORDER BY CreatedDate DESC LIMIT 1) FROM Account WHERE Id IN:accountIds]);        
        for(Account eachAccount : targetAccountMap.values()) {
            if(eachAccount.Opportunities != null && eachAccount.Opportunities.size() > 0) {
                oppIds.add(eachAccount.Opportunities[0].Id);
            }
        }

        List<Call_Report_Opportunity__c> callReportOppList = new List<Call_Report_Opportunity__c>();
        callReportOppList = [SELECT Call_Plan_Call_Report__c, Opportunity_Name__c FROM Call_Report_Opportunity__c WHERE Opportunity_Name__c IN :oppIds];
        Set<Id> callReportIds = new Set<Id>();
        Map<Id, Id> callReportMapByOpp = new Map<Id, Id>();
        for(Call_Report_Opportunity__c eachCallOpp : callReportOppList) {
            if(eachCallOpp.Call_Plan_Call_Report__c != null)
                callReportIds.add(eachCallOpp.Call_Plan_Call_Report__c);
            if(eachCallOpp.Opportunity_Name__c != null)
                callReportMapByOpp.put(eachCallOpp.Opportunity_Name__c, eachCallOpp.Call_Plan_Call_Report__c);
        }

        Map<Id, Call_Report__c> callReportMap = new Map<Id, Call_Report__c>([SELECT Id, Status__c, Offer_Interest__c, Offer_Credit_Product__c, Collect_Documents__c, Negotiation__c, CreatedDate FROM Call_Report__c WHERE Id IN:callReportIds AND RecordType.DeveloperName IN :recordTypeSet]);

        Account eachAccount;
        Opportunity eachOpportunity;
        Call_Report__c eachCallReport;

        for(Target_List__c eachTarget : updateTargetList) {
            if(eachTarget.CIS_ID_Prospect_Name__c != null && targetAccountMap.containsKey(eachTarget.CIS_ID_Prospect_Name__c)) {
                eachAccount = targetAccountMap.get(eachTarget.CIS_ID_Prospect_Name__c);
                if(eachAccount.Opportunities != null && eachAccount.Opportunities.size() > 0) {
                    eachOpportunity = eachAccount.Opportunities[0];
                    if(eachOpportunity.StageName == GlobalConstants.AUTO_CLOSED || eachOpportunity.StageName == GlobalConstants.CLOSE_LOST) {
                        if(callReportMapByOpp.containsKey(eachOpportunity.Id)) {
                            eachCallReport = callReportMap.get(callReportMapByOpp.get(eachOpportunity.Id));
                        } else { // Not found Call Report
                            eachTarget.Status__c = eachOpportunity.StageName;
                        }
                    } else { // Opportunity StageName != Auto Closed OR Close Lost
                        eachTarget.Status__c = eachOpportunity.StageName;
                    }
                }
            }
        }
    }

    public static void getLatestLeadFromTargetList(Set<Id> targetListIds, List<Call_Report__c> callReportList) {
        List<Call_Report_Lead__c> callReportLeadList = new List<Call_Report_Lead__c>();
        Opportunity_Lead__c eachExistOpportunityLead;
        Call_Report_Lead__c eachExistCallReportLead;
        Map<Id, List<Target_List__c>> targetListsMapByAccountId = new Map<Id, List<Target_List__c>>();
        List<Target_List__c> targetLists = [SELECT Id, CIS_ID_Prospect_Name__c, 
                                            (SELECT Id, Opportunity__r.StageName FROM Opportunities_Leads__r ORDER BY CreatedDate DESC LIMIT 1), 
                                            (SELECT Id, Call_Plan_Call_Report__c, Call_Plan_Call_Report__r.RecordTypeId FROM Call_Reports_Leads__r ORDER BY CreatedDate DESC LIMIT 1) 
                                                FROM Target_List__c WHERE Id IN :targetListIds AND Lead_Campaign__r.Status = :GlobalConstants.ACTIVE];
        for(Target_List__c eachTarget : targetLists) {
            //Dont need to check null for Master Detail
            //if(eachTarget.CIS_ID_Prospect_Name__c != null)
            if(!targetListsMapByAccountId.containsKey(eachTarget.CIS_ID_Prospect_Name__c))
                targetListsMapByAccountId.put(eachTarget.CIS_ID_Prospect_Name__c, new List<Target_List__c>());
            
            targetListsMapByAccountId.get(eachTarget.CIS_ID_Prospect_Name__c).add(eachTarget);
        }

        for(Call_Report__c eachNewCallReport : callReportList) {
            if(targetListsMapByAccountId.containsKey(eachNewCallReport.CIS_ID__c)) {
                targetLists = targetListsMapByAccountId.get(eachNewCallReport.CIS_ID__c);
                for(Target_List__c eachTarget : targetLists) {
                    if(eachTarget.Opportunities_Leads__r != null && eachTarget.Opportunities_Leads__r.size() > 0) { // Have Existing Opportunity Lead
                        eachExistOpportunityLead = eachTarget.Opportunities_Leads__r.get(0);
                        if(eachExistOpportunityLead.Opportunity__r.StageName == GlobalConstants.CLOSE_WON) {
                            // Not Create
                        } else if(eachExistOpportunityLead.Opportunity__r.StageName == GlobalConstants.AUTO_CLOSED || eachExistOpportunityLead.Opportunity__r.StageName == GlobalConstants.CLOSE_LOST) {
                            // Create 
                        } else {
                            // Create Not Update Status
                        }
                    } else if(eachTarget.Call_Reports_Leads__r != null && eachTarget.Call_Reports_Leads__r.size() > 0) { // Have Existing CallReport Lead
                        eachExistCallReportLead = eachTarget.Call_Reports_Leads__r.get(0);
                        if(eachExistCallReportLead.Call_Plan_Call_Report__r.RecordTypeId == 'Call Plan') {

                        } else if(eachExistCallReportLead.Call_Plan_Call_Report__r.RecordTypeId == 'Call Report') {

                        }
                    } else { // No existing Call Plan / Call Report / Opportunity => Create and Update Status
                        callReportLeadList.add(new Call_Report_Lead__c(
                            Call_Plan_Call_Report__c = eachNewCallReport.Id,
                            Target_List__c = eachTarget.Id
                        ));
                    }
                }
            }
        }
    }

    public static void checkCallReportExistingLead(Set<Id> targetListIds) {
        Map<Id, Call_Report_Lead__c> callReportLeadMapByTargetList = new Map<Id, Call_Report_Lead__c>();
        List<Call_Report_Lead__c> callReportLeadList = [SELECT Id, Call_Plan_Call_Report__c, Target_List__c FROM Call_Report_Lead__c WHERE Target_List__c IN:targetListIds];
        for(Call_Report_Lead__c eachCallReportLead : callReportLeadList) {
            if(eachCallReportLead.Target_List__c != null) 
                callReportLeadMapByTargetList.put(eachCallReportLead.Target_List__c, eachCallReportLead);
        }
    }
}