objects/Application_Log__c.object
<CustomObject>
    <description>Object to hold custom exception messages in Apex Code, Apex Batch, Apex trigger, and etc.</description>
    <fields>
        <fullName>Message__c</fullName>
        <description>Message to log</description>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Source_Function__c</fullName>
        <description>The originating function in the class (e.g. UpdateDivision() )</description>
        <label>Source Function</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Exception Log</label>
    <nameField>
        <label>Application Log</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/System_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Log_Purge_Days__c</fullName>
        <description>The number of days of logs to keep</description>
        <label>Log Purge (Days)</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>System Settings</label>
</CustomObject>

classes/SME_PurgeApplicationLog_Batch_Test.cls
/*------------------------------------------------------------
Author: Charnun Thaweethamwitthaya
Company : Beryl8
Description:   A test class for SME_PurgeApplicationLog_Batch

History : 
<Date>      <Authors Name>     <Brief Description of Change> 
03/08/2015  Charnun.t           First Create
------------------------------------------------------------*/
@isTest
private class SME_PurgeApplicationLog_Batch_Test {

    static testmethod void testPurgeApplicationLogBatch() {

       Application_Log__c[] multiAppLog = new List<Application_Log__c>();
       for (Integer i=0;i<10;i++) {
           Application_Log__c appLog = new Application_Log__c(
               Name = 'Application_Log__c ' + i,
               Message__c = 'Some description' + i,
               Source_Function__c = 'SFDC');
           multiAppLog.add(appLog);
       }
       insert multiAppLog;

       //System_Settings__c systemSetting = [SELECT Id, Log_Purge_Days__c FROM System_Settings__c];
       //systemSetting.Log_Purge_Days__c = 0;
       //update systemSetting;

       Test.startTest();
       SME_PurgeApplicationLog_Batch purgeBatch = new SME_PurgeApplicationLog_Batch();
       Database.executeBatch(purgeBatch);
       Test.stopTest();

       Integer i = [SELECT COUNT() FROM Application_Log__c];
       System.assertEquals(i,10);
    }
}