objects/Application_Log__c.object
<CustomObject>
    <description>Object to hold custom exception messages in Apex Code, Apex Batch, Apex trigger, and etc.</description>
    <fields>
        <fullName>Debug_Level__c</fullName>
        <description>Error, Info, Warning, Debug</description>
        <label>Debug Level</label>
        <picklist>
            <picklistValues>
                <fullName>Debug</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Info</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warning</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Exception_Type__c</fullName>
        <label>Exception Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>Message to log</description>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Source_Function__c</fullName>
        <description>The originating function in the class (e.g. UpdateDivision() )</description>
        <label>Source Function</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>The originating class (e.g. CustomerManagement)</description>
        <label>Source</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <description>Raw exception stack trace for unhandled errors</description>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Exception Log</label>
    <nameField>
        <label>Application Log</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ApplicationLog_Service_Test.cls
/**
* @author komsan.wi@beryl8.com
* @17/07/2015 createddate
*/
@isTest
private class ApplicationLog_Service_Test {
  private static ApplicationLog_Service_Test.TestLog logging;
  static {
    logging = new ApplicationLog_Service_Test.TestLog();
  }
  @isTest static void addLogWithNoException() {
      String expectedClass = 'classTest';
      String expectedMessage = 'messageTest';
      logging.addLog(expectedClass,expectedMessage);
      Test.startTest();
        logging.clearance();
      Test.stopTest();

      List<Application_Log__c> result = [SELECT Id,Debug_Level__c,Message__c,Source__c,Source_Function__c,Stack_Trace__c,Exception_Type__c FROM Application_Log__c];
      System.assertEquals(1,result.size());
    }

    @isTest static void addLogWithException() {
      String expectedClass = 'classTest';
      String expectedMessage = 'messageTest';

      Test.startTest();
      try {
        Integer newInt = 10;
        Integer newInt2 = 0;

        newInt = newInt/newInt2;
      } catch(Exception e) {
        System.assertNotEquals(null, e);
        logging.addLog(expectedClass, e);
        logging.addLog(expectedClass, e,expectedMessage);
      }

        logging.clearance();
      Test.stopTest();

    }

  private class TestLog extends ApplicationLog_Service {
  }
}