objects/Associated_Customer__c.object
<CustomObject>
    <description>This object tracks the additional Customer and Contact for one call plan/call report</description>
    <fields>
        <fullName>Borrower_Type__c</fullName>
        <label>Borrower Type</label>
        <picklist>
            <picklistValues>
                <fullName>Main Borrower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Co Borrower</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Call_Plan_Call_Report__c</fullName>
        <label>Call Plan / Call Report</label>
        <referenceTo>Call_Report__c</referenceTo>
        <relationshipLabel>Associated Customers</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CIS</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Associated Customers</relationshipLabel>
        <relationshipName>Customer_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Associated Customer</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Call_Report__c.object
<CustomObject>
    <description>This object tracks the Call Plan and Call Report</description>
    <label>Call Plan / Call Report</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Call Plan / Call Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Plans / Call Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CallPlanCallReportField__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>ActualVisitDateFieldId__c</fullName>
        <label>ActualVisitDateFieldId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CISFieldId__c</fullName>
        <label>CISFieldId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CallReportObjectId__c</fullName>
        <label>CallReportObjectId</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactChannelFieldId__c</fullName>
        <label>ContactChannelFieldId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Id__c</fullName>
        <label>Entity Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OfferCreditProductFieldId__c</fullName>
        <label>OfferCreditProductFieldId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OfferInterestFieldId__c</fullName>
        <label>OfferInterestFieldId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SecondaryCallReportRecordTypeId__c</fullName>
        <label>SecondaryCallReportRecordTypeId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>CallPlanCallReportField</label>
</CustomObject>

classes/SME_Associated_OverrideEdit_Controller.cls
/**
* @author charnun.t@beryl8.com
* @08/04/2016 createddate
*/
public without sharing class SME_Associated_OverrideEdit_Controller {

    public SME_Associated_OverrideEdit_Controller(ApexPages.StandardController stdController) {
    }

    public PageReference redirectToNewCallReportPage() {
        CallPlanCallReportField__c callPlanCallReportField = CallPlanCallReportField__c.getOrgDefaults();
        PageReference pageRef;
        
        String callReportIdString = ApexPages.currentPage().getParameters().get('callReportId');
        String callReportCISIDString = '';
        String callReportActualVisitDateString = ApexPages.currentPage().getParameters().get('callReportActualVisitDate');

        Associated_Customer__c getAssociatedDetails = new Associated_Customer__c();
        
        try{
            // Get data from call report
            getAssociatedDetails = [SELECT Id, Borrower_Type__c, Call_Plan_Call_Report__c, Call_Plan_Call_Report__r.Name, Customer__r.Name, Customer__c FROM Associated_Customer__c where Call_Plan_Call_Report__c =:callReportIdString ORDER BY CreatedDate DESC limit 1];
            // Add more feature to create duplicate call reports without plan on this scenario
            System.debug('getAssociatedDetails:'+ getAssociatedDetails);
            if(getAssociatedDetails.Borrower_Type__c == 'Main Borrower'){
                // Main borrower Pass value to create new call report
                System.debug('In Main:');
                callReportCISIDString = getAssociatedDetails.Customer__r.Name;
                pageRef = new PageReference('/'+CallPlanCallReportField.CallReportObjectId__c+'/e?');//+'apex/CallReport_OverrideEdit?accountId=/'+getAssociatedDetails.Customer__c);//callPlanCallReportField.CallReportObjectId__c+'/e?');
                pageRef.getParameters().put(callPlanCallReportField.OfferInterestFieldId__c, 'Interest and can apply');
                pageRef.getParameters().put(callPlanCallReportField.ContactChannelFieldId__c, 'Face to Face');
                pageRef.getParameters().put(callPlanCallReportField.CISFieldId__c, callReportCISIDString);
                pageRef.getParameters().put(callPlanCallReportField.ActualVisitDateFieldId__c, callReportActualVisitDateString);
                pageRef.getParameters().put(callPlanCallReportField.OfferCreditProductFieldId__c, '1');
                //pageRef.getParameters().put(callPlanCallReportField.PrimaryCallPlanCallReportFieldId__c,getAssociatedDetails.Call_Plan_Call_Report__r.Name);
                //pageRef.getParameters().put(callPlanCallReportField.PrimaryCallReportFieldId__c,'0');

                pageRef.getParameters().put('RecordType', callPlanCallReportField.SecondaryCallReportRecordTypeId__c);
                pageRef.getParameters().put('ent', callPlanCallReportField.Entity_Id__c);
                pageRef.getParameters().put('nooverride', '1');
                pageRef.getParameters().put('saveURL','/apex/CallReport_OverrideEdit?accountId='+getAssociatedDetails.Customer__c+'&primaryFlag=0&primaryCallReportId='+getAssociatedDetails.Call_Plan_Call_Report__c+'&associatedId='+getAssociatedDetails.Id);
                pageRef.setRedirect(true);
                return pageRef;
            }else{
                // Co borrower
                System.debug('In Co:'+callReportIdString);
                pageRef = new PageReference('/'+callReportIdString);
                pageRef.getParameters().put('nooverride', '1');
                pageRef.setRedirect(true);
                return pageRef;
            }
        }catch(Exception e){
            System.debug('Exception:'+callReportIdString+e);
        }
        System.debug('In Co:'+callReportIdString);
        pageRef = new PageReference('/'+callReportIdString);
        pageRef.getParameters().put('nooverride', '1');
        pageRef.setRedirect(true);
        return pageRef;
    }
}