objects/Associated_Customer__c.object
<CustomObject>
    <description>This object tracks the additional Customer and Contact for one call plan/call report</description>
    <fields>
        <fullName>Borrower_Type__c</fullName>
        <label>Borrower Type</label>
        <picklist>
            <picklistValues>
                <fullName>Main Borrower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Co Borrower</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Call_Plan_Call_Report__c</fullName>
        <label>Call Plan / Call Report</label>
        <referenceTo>Call_Report__c</referenceTo>
        <relationshipLabel>Associated Customers</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CIS</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Associated Customers</relationshipLabel>
        <relationshipName>Customer_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Secondary_Call_Plan_Call_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Call Plan / Call Report</label>
        <referenceTo>Call_Report__c</referenceTo>
        <relationshipLabel>Associated Customers (Secondary Call Plan / Call Report)</relationshipLabel>
        <relationshipName>Associated_Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Associated Customer</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Customers</pluralLabel>
    <recordTypes>
        <fullName>Interested</fullName>
        <active>true</active>
        <description>Associate Customer is interested.</description>
        <label>Interested</label>
    </recordTypes>
    <recordTypes>
        <fullName>Not_Interested</fullName>
        <active>true</active>
        <description>Associate Customer is not interested.</description>
        <label>Not Interested</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Call_Report__c.object
<CustomObject>
    <description>This object tracks the Call Plan and Call Report</description>
    <fields>
        <fullName>Actual_Visit_Date__c</fullName>
        <defaultValue>IF(CONTAINS($RecordType.DeveloperName,&quot;CallReport&quot;),TODAY(),NULL)</defaultValue>
        <inlineHelpText>ห้ามเกินกว่าวันปัจจุบัน</inlineHelpText>
        <label>Actual Visit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CIS_ID__c</fullName>
        <label>CIS ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call Plans / Call Reports</relationshipLabel>
        <relationshipName>Call_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Co_Borrower__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Co Borrower</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Channel__c</fullName>
        <label>Contact Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Face to Face</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone Call</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Memo__c</fullName>
        <label>Memo</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Offer_Credit_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Offer Credit Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Offer_Interest__c</fullName>
        <label>Offer Interest</label>
        <picklist>
            <controllingField>Offer_Credit_Product__c</controllingField>
            <picklistValues>
                <fullName>Interest and can apply</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interest with condition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cannot apply</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer not interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interested with condition</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Primary_Call_Plan_Call_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Call Plan / Call Report</label>
        <referenceTo>Call_Report__c</referenceTo>
        <relationshipLabel>Call Plans / Call Reports</relationshipLabel>
        <relationshipName>Call_Plans_Call_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Call_Report__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Primary Call Report</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <picklist>
            <controllingField>Offer_Interest__c</controllingField>
            <picklistValues>
                <fullName>2.1 รอตัดสินใจ/รอปรึกษาครอบครัว</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.2 สนใจแต่รอแก้ปัญหาเรื่องหลักประกัน</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.3 สนใจแต่มีประเด็นต่อรองเกี่ยวกับดอกเบี้ย / ค่าธรรมเนียม</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.4 สนใจแต่ไม่ใช่ในช่วงเดือนนี้</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.5 สนใจแต่มีประเด็นต่อรองเกี่ยวกับประกันชีวิต</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.6 สนใจแต่วงเงินที่เสนอไม่เพียงพอ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.7 อื่น ๆ (โปรดระบุ)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.1 Refer ให้ผู้อื่นดำเนินการ (ระบุในหมายเหตุ)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.2 ที่อยู่ และเบอร์โทรศัพท์ไม่ถูกต้อง / ไม่มีข้อมูล/ ติดต่อไม่ได้</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.3 เพิ่งขอสินเชื่อไม่ถึง 3 เดือน</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.4 ลูกค้าคุณสมบัติไม่ดี / ไม่ผ่านหลักเกณฑ์ธนาคาร (ระบุในหมายเหตุ)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.5 ลูกค้าไม่ให้เข้าพบ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.6 เสียชีวิต / เลิกกิจการ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.7 หลักประกันไม่ผ่านเกณฑ์</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.8 อื่น ๆ (โปรดระบุ)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.1 มีเงินคงเหลือในบัญชีสูงหรือวงเงินเป็นตัวดำ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.2 ติดเรื่องค่าใช้จ่ายในการดำเนินการ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.3 ยอดขายกิจการลดลง</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.4 ตัดออกจากรายชื่อ Lead (ระยะเวลา 6 เดือน)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.5 ขอในนามบุคคล/บริษัทอื่น (โปรดระบุ CIS/เลขบัตรประชาชนหรือเลขทะเบียนการค้า)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.6 อื่น ๆ (โปรดระบุ)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Call Plan / Call Report</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Call Plan / Call Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Plans / Call Reports</pluralLabel>
    <recordTypes>
        <fullName>Secondary_Call_Report_No_plan</fullName>
        <active>true</active>
        <description>For Associated Customer, without Call Plan section</description>
        <label>Secondary Call Report (No plan)</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Co_Borrower__c.object
<CustomObject>
    <description>This object tracks the Co-Borrower Customer that associated with the Opportunity</description>
    <label>Co-Borrower</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Co-Borrowers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AssociatedCustomerTriggerHandler.cls
/**
* @author charnun.t@beryl8.com
* @08/04/2016 createddate
*/
public without sharing class AssociatedCustomerTriggerHandler extends TriggerHandler{
	public override void afterInsert() {
        List<Associated_Customer__c> associatedCustomerList = Trigger.new;

        if(associatedCustomerList.size() == 1){
            // Get data from call report
            Call_Report__c newCallReport;
            Call_Report__c getCallReportDetails = [SELECT Actual_Visit_Date__c,Id FROM Call_Report__c where Id =:associatedCustomerList.get(0).Call_Plan_Call_Report__c];
            if(associatedCustomerList.get(0).RecordTypeId == GlobalUtility.getRecordTypeIdFromSObjectByDevName('Associated_Customer__c','Interested')){
            	
            	// Add more feature to create duplicate call reports without plan on this scenario
            	System.debug('AssociatedCustomerTriggerHandler:'+ Trigger.new);
            	if(associatedCustomerList.get(0).Borrower_Type__c == 'Co Borrower'){
            		// Co borrower
                    System.debug('getCallReportDetails:'+ getCallReportDetails);
                    newCallReport = new Call_Report__c();

                    newCallReport.Offer_Interest__c = 'Interest and can apply';
                    newCallReport.Contact_Channel__c = 'Face to Face';
                    newCallReport.CIS_ID__c = associatedCustomerList.get(0).Customer__c;
                    newCallReport.Actual_Visit_Date__c = getCallReportDetails.Actual_Visit_Date__c;
                    newCallReport.Offer_Credit_Product__c = true;
                    newCallReport.Co_Borrower__c = true;
                    newCallReport.Status__c = 'Contacted';
                    newCallReport.Primary_Call_Report__c = false;
                    newCallReport.RecordTypeId = GlobalUtility.getRecordTypeIdFromSObjectByDevName('Call_Report__c','Secondary_Call_Report_No_plan');
                    newCallReport.Primary_Call_Plan_Call_Report__c = getCallReportDetails.Id;

                    System.debug('newCallReport::'+newCallReport);
                    try{
                        insert newCallReport;
                    }catch(Exception e){
                        System.debug('System Error when try to insert Second Call Plan/Call Report from Associated Customer');
                    }
            	}
            }else if(associatedCustomerList.get(0).RecordTypeId == GlobalUtility.getRecordTypeIdFromSObjectByDevName('Associated_Customer__c','Not_Interested')){
                newCallReport = new Call_Report__c();

                newCallReport.Offer_Interest__c = 'Not Interest';
                newCallReport.Contact_Channel__c = 'Face to Face';
                newCallReport.CIS_ID__c = associatedCustomerList.get(0).Customer__c;
                newCallReport.Actual_Visit_Date__c = getCallReportDetails.Actual_Visit_Date__c;
                newCallReport.Offer_Credit_Product__c = true;
                newCallReport.Status__c = 'Contacted';
                newCallReport.Reason__c = '4.5 อื่น ๆ (โปรดระบุ)';
                newCallReport.Memo__c = 'Associated Customer ลูกค้าไม่สนใจ';
                newCallReport.Primary_Call_Report__c = false;
                newCallReport.RecordTypeId = GlobalUtility.getRecordTypeIdFromSObjectByDevName('Call_Report__c','Secondary_Call_Report_No_plan');
                newCallReport.Primary_Call_Plan_Call_Report__c = getCallReportDetails.Id;

                System.debug('newCallReport::'+newCallReport);
                try{
                    insert newCallReport;
                }catch(Exception e){
                    System.debug('System Error when try to insert Second Call Plan/Call Report from Associated Customer');
                }
            }
            if(newCallReport != null){
                // Add Second Call Report to Associated Customer
                Associated_Customer__c tempAssociated = new Associated_Customer__c(Id=associatedCustomerList.get(0).Id);
                tempAssociated.Secondary_Call_Plan_Call_Report__c = newCallReport.Id;
                try{
                    update tempAssociated;
                }catch(Exception e){
                    System.debug('System Error when try to update Second Call Plan/Call Report in Associated Customer');
                }
            }
        }
    }
}