objects/Bulk_Assignment__c.object
<CustomObject>
    <description>This object will be help to manage and stored bulk assignment history</description>
    <fields>
        <fullName>AssignmentOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>AssignmentOwner</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bulk Assignment</label>
    <nameField>
        <displayFormat>BulkAssign-{0000000000}</displayFormat>
        <label>Bulk Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bulk Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Team_Structure__c.object
<CustomObject>
    <fields>
        <fullName>RC_Code__c</fullName>
        <label>RC Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Team Structure</label>
    <nameField>
        <label>Team Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Structure</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>RC_Code__c</fullName>
        <label>RC Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TeamStructure_Service.cls
public without sharing class TeamStructure_Service {
    public static Map<String, User> userMapByRCCode;
    public static Map<String, Team_Structure__c> teamMapByRCCode;

    public static Map<String, User> getUserMapByRCCode() {
        Set<String> profileSet = new Set<String>{GlobalConstants.SME_NH, GlobalConstants.SME_AH, GlobalConstants.SME_TM};
        List<User> allUser = [SELECT Id, RC_Code__c, IsActive, ManagerId, Manager.ManagerId, Manager.IsActive, Manager.Manager.IsActive, Manager.Manager.Manager.IsActive FROM User WHERE Profile.Name IN :profileSet ORDER BY Isactive DESC, LastModifiedDate DESC];
        Map<String, User> userMapByRC = new Map<String, User>();
        for(User eachUser : allUser) {
            if(!userMapByRC.containsKey(eachUser.RC_Code__c) && eachUser.RC_Code__c != null)
                userMapByRC.put(eachUser.RC_Code__c, eachUser);
        }

        return userMapByRC;
    }

	public static void reassignOwner(Map<Id, Bulk_Assignment__c> assignMapByCurrentUser, Map<Id, User> newUserMap) {
        List<Team_Structure__c> updateTeamList = new List<Team_Structure__c>();
        updateTeamList = [SELECT Id, OwnerId, RC_Code__c FROM Team_Structure__c WHERE OwnerId IN:assignMapByCurrentUser.keyset()];
        User eachNewUser;
        for(Team_Structure__c eachTeam : updateTeamList) {
            if(newUserMap.containsKey(eachTeam.OwnerId)) {
                eachNewUser = newUserMap.get(eachTeam.OwnerId);
            }
            if(eachNewUser != null && assignMapByCurrentUser.containsKey(eachTeam.OwnerId) && (eachNewUser.Isactive == false || eachNewUser.RC_Code__c != eachTeam.RC_Code__c)) {
                eachTeam.OwnerId = assignMapByCurrentUser.get(eachTeam.OwnerId).AssignmentOwner__c;
            }
        }
        if(updateTeamList.size() > 0)
            update updateTeamList;
    }

    @future
    public static void updateTeamStructure(String teamStringList) {
        List<Team_Structure__c> teamList = (List<Team_Structure__c>) JSON.deserialize(teamStringList, List<Team_Structure__c>.class);
        update teamList;
    }
}