objects/Bulk_Assignment__c.object
<CustomObject>
    <description>This object will be help to manage and stored bulk assignment history</description>
    <fields>
        <fullName>BulkAssignmentQueue__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Bulk Assignment Queue</label>
        <referenceTo>Bulk_Assignment_Queue__c</referenceTo>
        <relationshipLabel>Bulk Assignments</relationshipLabel>
        <relationshipName>Bulk_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Execute</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Bulk Assignment</label>
    <nameField>
        <displayFormat>BulkAssign-{0000000000}</displayFormat>
        <label>Bulk Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bulk Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Bulk_Assignment_Queue__c.object
<CustomObject>
    <fields>
        <fullName>StartTime__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Create</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Execute</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Bulk Assignment Queue</label>
    <nameField>
        <displayFormat>BulkAssignQueue-{0000000000}</displayFormat>
        <label>Bulk Assignment Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bulk Assignments Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CalculateOwnershipAssignment_Queue.cls
public class CalculateOwnershipAssignment_Queue implements Queueable {
	public List<Bulk_Assignment__c> bulkAssignList;
	public boolean needToCreateQueue;

	public CalculateOwnershipAssignment_Queue(List<Bulk_Assignment__c> bulkAssignList) {
		this.bulkAssignList = bulkAssignList;
	}

	public CalculateOwnershipAssignment_Queue(List<Bulk_Assignment__c> bulkAssignList, Boolean needToCreateQueue) {
		this.bulkAssignList = bulkAssignList;
		this.needToCreateQueue = needToCreateQueue;
	}

	public void execute(QueueableContext context) {
		if(bulkAssignList != null && !bulkAssignList.isEmpty()) {
			if(needToCreateQueue != null && needToCreateQueue) {
				Bulk_Assignment_Queue__c bulkQueue = new Bulk_Assignment_Queue__c();
		        bulkQueue.Status__c = 'Create';
		        bulkQueue.StartTime__c = System.now();
		        insert bulkQueue;

				for(Bulk_Assignment__c eachAssign : bulkAssignList) {
					eachAssign.BulkAssignmentQueue__c = bulkQueue.Id;
				}

				insert bulkAssignList;
			}
			SME_BulkAssignment_Service.bulkAssignment(bulkAssignList);
		}
	}
}