objects/Bulk_Assignment__c.object
<CustomObject>
    <description>This object will be help to manage and stored bulk assignment history</description>
    <fields>
        <fullName>AssignmentOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>AssignmentOwner</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bulk Assignment</label>
    <nameField>
        <displayFormat>BulkAssign-{0000000000}</displayFormat>
        <label>Bulk Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bulk Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Task_Service.cls
public class Task_Service {
    public static void reassignTask(Map<Id, Bulk_Assignment__c> assignMapByCurrentUser) {
    	List<Task> taskList = new List<Task>();
    	taskList = [SELECT Id, OwnerId, WhoId, WhatId, Status FROM Task WHERE Status IN ('Not Started','In Progress','Waiting on someone else','Deferred') AND OwnerId IN:assignMapByCurrentUser.keyset() AND WhatId != null];
    	for(Task eachTask : taskList) {
    		if(assignMapByCurrentUser.containsKey(eachTask.OwnerId)) {
    			eachTask.Status = GlobalConstants.CLOSED_BY_SYSTEM;
    			//eachTask.OwnerId = assignMapByCurrentUser.get(eachTask.OwnerId).AssignmentOwner__c;
    		}
    	}
    	if(taskList.size() > 0)
    		update taskList;
    }
}