objects/Call_Report_Lead__c.object
<CustomObject>
    <description>This object tracks the Lead associated to Call Plan/Call Report</description>
    <fields>
        <fullName>Target_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target List</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Target_List__c.Lead_Campaign__r.Status</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>Target_List__c.Lead_Campaign__r.Sub_Type__c</field>
                <operation>notEqual</operation>
                <value>Value Chain</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Target_List__c</referenceTo>
        <relationshipLabel>Call Reports / Leads</relationshipLabel>
        <relationshipName>Associated_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Call Report / Lead</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Reports / Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Target_List__c.object
<CustomObject>
    <description>This object tracks the list of Targeted Lead and Campaign Member list</description>
    <fields>
        <fullName>In_Call_Plan__c</fullName>
        <defaultValue>false</defaultValue>
        <label>In Call Plan</label>
        <type>Checkbox</type>
    </fields>
    <label>Target List</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CallReportLeadTriggerHandler.cls
public with sharing class CallReportLeadTriggerHandler extends TriggerHandler {

	Map<Id, Target_List__c> updateTargetList;
	Target_List__c updateTarget;

	public override void init() {
		updateTargetList = new Map<Id, Target_List__c>();
	}

	public override void afterInsert() {
		for (Call_Report_Lead__c eachCallReportLead : ((List<Call_Report_Lead__c>)Trigger.new)) {
			if (eachCallReportLead.Target_List__c != null) {
				updateTarget = new Target_List__c(
					Id = eachCallReportLead.Target_List__c,
					In_Call_Plan__c = true
				);
				if(!updateTargetList.containsKey(eachCallReportLead.Target_List__c))
					updateTargetList.put(eachCallReportLead.Target_List__c, updateTarget);
			}
		}
	}

	public override void afterUpdate() {
		Set<Id> oldTargetIds = new Set<Id>();

		for (Call_Report_Lead__c eachCallLead : ((List<Call_Report_Lead__c>)Trigger.new)) {
			Call_Report_Lead__c oldCallLead = (Call_Report_Lead__c)Trigger.oldMap.get(eachCallLead.Id);
            if(eachCallLead.Target_List__c != null && oldCallLead.Target_List__c != null && eachCallLead.Target_List__c != oldCallLead.Target_List__c) {
                updateTarget = new Target_List__c(
					Id = eachCallLead.Target_List__c,
					In_Call_Plan__c = true
				);
				if(!updateTargetList.containsKey(eachCallLead.Target_List__c))
					updateTargetList.put(eachCallLead.Target_List__c, updateTarget);

				oldTargetIds.add(oldCallLead.Target_List__c);
            } else if(eachCallLead.Target_List__c == null || oldCallLead.Target_List__c == null) {
            	eachCallLead.addError('Target_List__c can not be null');
            }
        }

    	List<Call_Report_Lead__c> callReportLeadList = new List<Call_Report_Lead__c>();
        callReportLeadList = [SELECT Id, Target_List__c FROM Call_Report_Lead__c WHERE Target_List__c IN :oldTargetIds];
        
        addUpdatedTargetList(callReportLeadList, oldTargetIds);
	}

	public override void afterDelete() {
		Set<Id> existTargetIds = new Set<Id>();
		Set<Id> existCallLeadIds = new Set<Id>();

		for (Call_Report_Lead__c eachCallLead : (List<Call_Report_Lead__c>)Trigger.old) {
            if(eachCallLead.Target_List__c != null) {
                existTargetIds.add(eachCallLead.Target_List__c);
                existCallLeadIds.add(eachCallLead.Id);
            }
        }

        List<Call_Report_Lead__c> callReportLeadList = new List<Call_Report_Lead__c>();
        callReportLeadList = [SELECT Id, Target_List__c FROM Call_Report_Lead__c WHERE Id NOT IN :existCallLeadIds AND Target_List__c IN :existTargetIds];
        
        addUpdatedTargetList(callReportLeadList, existTargetIds);
	}

	void addUpdatedTargetList(List<Call_Report_Lead__c> callReportLeadList, Set<Id> existTargetIds) {
		Set<Id> newTargetIds = new Set<Id>();

        for (Call_Report_Lead__c eachCallReportLead : callReportLeadList) {
        	newTargetIds.add(eachCallReportLead.Target_List__c);
        }

        for (Id eachTargetId : existTargetIds) {
            if(!newTargetIds.contains(eachTargetId)) {
                updateTarget = new Target_List__c(
					Id = eachTargetId,
					In_Call_Plan__c = false
				);
				if(!updateTargetList.containsKey(eachTargetId))
					updateTargetList.put(eachTargetId, updateTarget);
            }
        }
	}

	public override void allFinally() {
		if (!updateTargetList.isEmpty()) 
			update updateTargetList.values();
	}

}