objects/Call_Report_Lead__c.object
<CustomObject>
    <description>This object tracks the Lead associated to Call Plan/Call Report</description>
    <fields>
        <fullName>Call_Plan_Call_Report__c</fullName>
        <label>Call Plan / Call Report</label>
        <referenceTo>Call_Report__c</referenceTo>
        <relationshipName>Leads</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Target_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target List</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Target_List__c.Lead_Campaign__r.Status</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>Target_List__c.Lead_Campaign__r.Sub_Type__c</field>
                <operation>notEqual</operation>
                <value>Value Chain</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Target_List__c</referenceTo>
        <relationshipLabel>Call Reports / Leads</relationshipLabel>
        <relationshipName>Associated_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Call Report / Lead</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Reports / Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Call_Report_Opportunity__c.object
<CustomObject>
    <description>This object track the relationship between Call Report and Opportunity for the many to many relationship</description>
    <fields>
        <fullName>Call_Plan_Call_Report__c</fullName>
        <label>Call Plan / Call Report</label>
        <referenceTo>Call_Report__c</referenceTo>
        <relationshipName>Call_Report_Opportunity</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.OwnerId</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Call Reports / Opportunities</relationshipLabel>
        <relationshipName>Call_Report_Opportunity</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Call Report / Opportunity</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Reports / Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Lead__c.object
<CustomObject>
    <description>This object tracks the Lead associated to Opportunity</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities / Leads</relationshipLabel>
        <relationshipName>Opportunities_Leads</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Target_List__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Target List</label>
        <referenceTo>Target_List__c</referenceTo>
        <relationshipLabel>Opportunities / Leads</relationshipLabel>
        <relationshipName>Opportunities_Leads</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Opportunity / Lead</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities / Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Target_List__c.object
<CustomObject>
    <description>This object tracks the list of Targeted Lead and Campaign Member list</description>
    <fields>
        <fullName>CIS_ID_Prospect_Name__c</fullName>
        <label>CIS ID / Prospect Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Campaign_Members_Leads</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Lead_Type__c</fullName>
        <formula>TEXT( Lead_Campaign__r.Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lead Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Target Lists</relationshipLabel>
        <relationshipName>Target_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Target List</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CallReportOpportunityTriggerHandler.cls
/**
* @author komsan.wi@beryl8.com
* @30/09/2015 created new
*/
public with sharing class CallReportOpportunityTriggerHandler extends TriggerHandler{

    public override void afterDelete() {
        Set<Id> oppIdSet = new Set<Id>();
        for(Call_Report_Opportunity__c callReportOpp : (List<Call_Report_Opportunity__c>)Trigger.old) {
            oppIdSet.add(callReportOpp.Opportunity_Name__c);
        }
        CallReport_Service.updateActualVisitDateOfOpp(oppIdSet);
    }

    public override void afterInsert() {
    	Set<Id> callReportSet = new Set<Id>();
        Set<Id> opportunitySet = new Set<Id>();

    	List<Call_Report_Lead__c> callreportLeadList = new List<Call_Report_Lead__c>();
    	List<Opportunity_Lead__c> opportunityLeadList = new List<Opportunity_Lead__c>();
        Map<Id,Id> targetListMap = new Map<Id,Id>();
        Map<Id,Opportunity> opportunityMap = new Map<Id,Opportunity>();

    	Map<String,List<String>> leadMapByCallReport = new Map<String,List<String>>();
    	for(Call_Report_Opportunity__c eachCallOpp : (List<Call_Report_Opportunity__c>)Trigger.new){
    		if(eachCallOpp.Call_Plan_Call_Report__c!=null) callReportSet.add(eachCallOpp.Call_Plan_Call_Report__c);
            if(eachCallOpp.Opportunity_Name__c!=null) opportunitySet.add(eachCallOpp.Opportunity_Name__c);
    	}
    	callreportLeadList = [SELECT Id,Call_Plan_Call_Report__c,Target_List__c,Target_List__r.CIS_ID_Prospect_Name__c FROM Call_Report_Lead__c WHERE Target_List__r.Lead_Type__c =: GlobalConstants.LEAD_FOR_SALES AND Call_Plan_Call_Report__c in :callReportSet];

    	for(Call_Report_Lead__c eachCallReportLead : callreportLeadList){
    		if(eachCallReportLead.Call_Plan_Call_Report__c!=null && eachCallReportLead.Target_List__c!=null && eachCallReportLead.Target_List__r.CIS_ID_Prospect_Name__c!=null){
	    		if(!leadMapByCallReport.containsKey(eachCallReportLead.Call_Plan_Call_Report__c))
	    			leadMapByCallReport.put(eachCallReportLead.Call_Plan_Call_Report__c,new List<String>{eachCallReportLead.Target_List__c});
	    		else leadMapByCallReport.get(eachCallReportLead.Call_Plan_Call_Report__c).add(eachCallReportLead.Target_List__c);
                
                targetListMap.put(eachCallReportLead.Target_List__c,eachCallReportLead.Target_List__r.CIS_ID_Prospect_Name__c);
	    	}
    	}
        if(opportunitySet.size() > 0){
            opportunityMap = new Map<Id,Opportunity>([SELECT Id, AccountId FROM Opportunity WHERE Id IN:opportunitySet]);
            CallReport_Service.updateActualVisitDateOfOpp(opportunityMap.keySet());
        }

    	for(Call_Report_Opportunity__c eachCallOpp : (List<Call_Report_Opportunity__c>)Trigger.new){
    		if(leadMapByCallReport.containsKey(eachCallOpp.Call_Plan_Call_Report__c)){
    			List<String> targetIdList = leadMapByCallReport.get(eachCallOpp.Call_Plan_Call_Report__c);
    			for(String eachTargetId : targetIdList){
                    if(opportunityMap.get(eachCallOpp.Opportunity_Name__c).AccountId ==targetListMap.get(eachTargetId))
    		    		opportunityLeadList.add(new Opportunity_Lead__c(
    		    			Opportunity__c = eachCallOpp.Opportunity_Name__c,
    						Target_List__c = eachTargetId
    		    		));
		    	}

	    	}
    	}

    	if(opportunityLeadList.size() > 0) insert opportunityLeadList;
    }
}