objects/Call_Report__c.object
<CustomObject>
    <description>This object tracks the Call Plan and Call Report</description>
    <fields>
        <fullName>CIS_ID__c</fullName>
        <label>CIS ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call Plans / Call Reports</relationshipLabel>
        <relationshipName>Call_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <formula>CIS_ID__r.Name_Surname_TH__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Name</label>
        <type>Text</type>
    </fields>
    <label>Call Plan / Call Report</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Call Plan / Call Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Plans / Call Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CustomDashboard_Controller.cls
public with sharing class CustomDashboard_Controller {
	public List<Account> accountList;
	public List<Call_Report__c> callReportList;
	//public String accountName {get;set;}

	public CustomDashboard_Controller() {
		accountList = new List<Account>();
		callReportList = new List<Call_Report__c>();
	}

	public List<Account> getAllAccount() {
		accountList = [SELECT Id, Name FROM Account WHERE CreatedDate > LAST_WEEK];
		return accountList;
	}

	public List<Call_Report__c> getAllCallReport() {
		callReportList = [SELECT Id, CIS_ID__c, Customer_Name__c FROM Call_Report__c WHERE CreatedDate > LAST_WEEK];
		return callReportList;
	}
}