objects/Call_Report__c.object
<CustomObject>
    <description>This object tracks the Call Plan and Call Report</description>
    <label>Call Plan / Call Report</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Call Plan / Call Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Plans / Call Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Monthly_Performance__c.object
<CustomObject>
    <description>To store user and team&apos;s monthly performance.</description>
    <fields>
        <fullName>Call_Report_Customer_Others__c</fullName>
        <label># Call Report Customer Others</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report_Customer_Pool__c</fullName>
        <label># Call Report Customer Pool</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report_Customer_Port__c</fullName>
        <label># Call Report Customer Port</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report__c</fullName>
        <label># Call Report</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report_for_Relationship__c</fullName>
        <label># Call Report for Relationship</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report_for_Sales__c</fullName>
        <label># Call Report for Sales</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contacted_Customer_Other__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Contacted Customer in Other</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contacted_Customer_Pool__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Contacted Customer in Pool</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contacted_Customer_Port__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Contacted Customer in Port</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer_Other__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Customer in Others</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer_Pool__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Customer in Pool</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer_Port__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Customer in Port</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Face_to_Face__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Face to Face</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phone_Call__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Phone Call</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_visited_Customer__c</fullName>
        <label>Total visited Customer</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Monthly Performance</label>
    <nameField>
        <label>Month</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Performance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MonthlyPerformanceTriggerHandler.cls
/**
* @author komsan.wi@beryl8.com
* @11/04/2015 created new
*/
public class MonthlyPerformanceTriggerHandler extends TriggerHandler{
	public Decimal calculate(Decimal val1,Decimal val2){
		Decimal x1 = (val1!=null)?val1:0;
		Decimal x2 = (val2!=null)?val2:0;
		return x1+x2;
	}
	public override void beforeUpdate(){
		if(!GlobalUtility.resetStatement){
			Monthly_Performance__c eachOldMonthly;
			for(Monthly_Performance__c eachMonthly : (List<Monthly_Performance__c>)Trigger.new){
				eachOldMonthly = (Monthly_Performance__c)Trigger.oldMap.get(eachMonthly.Id);
				eachMonthly.Call_Report__c = calculate(eachMonthly.Call_Report__c,eachOldMonthly.Call_Report__c);
				eachMonthly.Call_Report_Customer_Port__c = calculate(eachMonthly.Call_Report_Customer_Port__c,eachOldMonthly.Call_Report_Customer_Port__c);
				eachMonthly.Call_Report_Customer_Pool__c = calculate(eachMonthly.Call_Report_Customer_Pool__c,eachOldMonthly.Call_Report_Customer_Pool__c);
				eachMonthly.Call_Report_Customer_Others__c = calculate(eachMonthly.Call_Report_Customer_Others__c,eachOldMonthly.Call_Report_Customer_Others__c);
				eachMonthly.Call_Report_for_Sales__c = calculate(eachMonthly.Call_Report_for_Sales__c,eachOldMonthly.Call_Report_for_Sales__c);
				eachMonthly.Call_Report_for_Relationship__c = calculate(eachMonthly.Call_Report_for_Relationship__c,eachOldMonthly.Call_Report_for_Relationship__c);
				eachMonthly.Face_to_Face__c = calculate(eachMonthly.Face_to_Face__c,eachOldMonthly.Face_to_Face__c);
				eachMonthly.Phone_Call__c = calculate(eachMonthly.Phone_Call__c,eachOldMonthly.Phone_Call__c);
				//eachMonthly.Total_visited_Customer__c = calculate(eachMonthly.Total_visited_Customer__c,eachOldMonthly.Total_visited_Customer__c);
				//eachMonthly.Contacted_Customer_Other__c = calculate(eachMonthly.Contacted_Customer_Other__c,eachOldMonthly.Contacted_Customer_Other__c);
				//eachMonthly.Contacted_Customer_Pool__c = calculate(eachMonthly.Contacted_Customer_Pool__c,eachOldMonthly.Contacted_Customer_Pool__c);
				//eachMonthly.Contacted_Customer_Port__c = calculate(eachMonthly.Contacted_Customer_Port__c,eachOldMonthly.Contacted_Customer_Port__c);
				//eachMonthly.Customer_Other__c = calculate(eachMonthly.Customer_Other__c,eachOldMonthly.Customer_Other__c);
				//eachMonthly.Customer_Pool__c = calculate(eachMonthly.Customer_Pool__c,eachOldMonthly.Customer_Pool__c);
				//eachMonthly.Customer_Port__c = calculate(eachMonthly.Customer_Port__c,eachOldMonthly.Customer_Port__c);
			}
		}
	}
}