objects/Call_Report__c.object
<CustomObject>
    <description>This object tracks the Call Plan and Call Report</description>
    <fields>
        <fullName>Primary_Call_Report__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Primary Call Report</label>
        <type>Checkbox</type>
    </fields>
    <label>Call Plan / Call Report</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Call Plan / Call Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Plans / Call Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SME_CallReport_Initial_Batch.cls
global class SME_CallReport_Initial_Batch implements Database.Batchable<sObject> {
    public String query;

    global SME_CallReport_Initial_Batch() {
        this.query = 'select id,Primary_Call_Report__c from call_report__c where Primary_Call_Report__c=false';
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, list<call_report__c> scope) {
        for(call_report__c each : scope){
            each.Primary_Call_Report__c = true;
        }
        TriggerHandler.bypass('CallReportTriggerHandler');
        update scope;
    }

    global void finish(Database.BatchableContext BC) {

    }
}