objects/Call_Report__c.object
<CustomObject>
    <description>This object tracks the Call Plan and Call Report</description>
    <fields>
        <fullName>CIS_ID__c</fullName>
        <label>CIS ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call Plans / Call Reports</relationshipLabel>
        <relationshipName>Call_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Call Plan / Call Report</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Call Plan / Call Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Plans / Call Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Call_Report_Lead__c.object
<CustomObject>
    <description>This object tracks the Lead associated to Call Plan/Call Report</description>
    <fields>
        <fullName>Call_Plan_Call_Report__c</fullName>
        <label>Call Plan / Call Report</label>
        <referenceTo>Call_Report__c</referenceTo>
        <relationshipName>Leads</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Target_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target List</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Target_List__c.Lead_Campaign__r.Status</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>Target_List__c.Lead_Campaign__r.Sub_Type__c</field>
                <operation>notEqual</operation>
                <value>Value Chain</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Target_List__c</referenceTo>
        <relationshipLabel>Call Reports / Leads</relationshipLabel>
        <relationshipName>Associated_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Call Report / Lead</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Reports / Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Call_Report_Opportunity__c.object
<CustomObject>
    <description>This object track the relationship between Call Report and Opportunity for the many to many relationship</description>
    <fields>
        <fullName>Call_Plan_Call_Report__c</fullName>
        <label>Call Plan / Call Report</label>
        <referenceTo>Call_Report__c</referenceTo>
        <relationshipName>Call_Report_Opportunity</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.OwnerId</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Call Reports / Opportunities</relationshipLabel>
        <relationshipName>Call_Report_Opportunity</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Call Report / Opportunity</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Reports / Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CIS_ID__c</fullName>
        <formula>Account.Name</formula>
        <label>CIS ID</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity_Lead__c.object
<CustomObject>
    <description>This object tracks the Lead associated to Opportunity</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities / Leads</relationshipLabel>
        <relationshipName>Opportunities_Leads</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Target_List__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Target List</label>
        <referenceTo>Target_List__c</referenceTo>
        <relationshipLabel>Opportunities / Leads</relationshipLabel>
        <relationshipName>Opportunities_Leads</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Opportunity / Lead</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities / Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Target_List__c.object
<CustomObject>
    <description>This object tracks the list of Targeted Lead and Campaign Member list</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Target Lists</relationshipLabel>
        <relationshipName>Target_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Target List</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OpportunityLeadTriggerHandler.cls
public class OpportunityLeadTriggerHandler extends TriggerHandler {

	public override void allBefore() {

		/*Set<Id> oppIds = new Set<Id>();
		Set<Id> targetIds = new Set<Id>();

		for (Opportunity_Lead__c oppLead : (List<Opportunity_Lead__c>) Trigger.new) {
			if (oppLead.Opportunity__c != null) {
				oppIds.add(oppLead.Opportunity__c);
			}
		}

		List<Call_Report_Opportunity__c > callReportOppList = new List<Call_Report_Opportunity__c >();
		callReportOppList = [SELECT Opportunity_Name__c FROM Call_Report_Opportunity__c WHERE Opportunity_Name__c IN :oppIds];
        Set<Id> oppInCallReportIds = new Set<Id>();
        for (Call_Report_Opportunity__c callOpp : callReportOppList) {
        	if (callOpp.Opportunity_Name__c != null)
            oppInCallReportIds.add(callOpp.Opportunity_Name__c);
        }


		List<Opportunity> filteredOppList = new List<Opportunity>();
		filteredOppList = [SELECT AccountId FROM Opportunity WHERE Id IN :oppInCallReportIds];
		
		if(!filteredOppList.isEmpty()) {
			Set<Id> accountIds = new Set<Id>();
			for (Opportunity eachOpp : filteredOppList) {
				if (eachOpp.AccountId != null) {
					accountIds.add(eachOpp.AccountId);
				}
			}

			List<Call_Report_Lead__c> callReportLeadList = new List<Call_Report_Lead__c>();
			callReportLeadList = [SELECT Id, Target_List__c, Target_List__r.Name FROM Call_Report_Lead__c WHERE Call_Plan_Call_Report__r.CIS_ID__c IN :accountIds];

			Set<Id> callReportTargetList = new Set<Id>();
			for (Call_Report_Lead__c callReportLead : callReportLeadList) {
				callReportTargetList.add(callReportLead.Target_List__c);
			}

			for (Opportunity_Lead__c oppLead : (List<Opportunity_Lead__c>) Trigger.new) {
				if (oppLead.Target_List__c != null) {
					if (!callReportTargetList.contains(oppLead.Target_List__c)) {
						oppLead.addError('Opportunity Lead need to be the same name as Call Report Lead');
					}
				}
			}
		}*/
		
	}
}