objects/Call_Report__c.object
<CustomObject>
    <description>This object tracks the Call Plan and Call Report</description>
    <label>Call Plan / Call Report</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Call Plan / Call Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Plans / Call Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Monthly_Performance__c.object
<CustomObject>
    <description>To store user and team&apos;s monthly performance.</description>
    <fields>
        <fullName>AVG_Call_Report_RM__c</fullName>
        <label>AVG Call Report/RM</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report__c</fullName>
        <label># Call Report</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Months__c</fullName>
        <label># Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_RM_under_Team__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of RM under Team</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Monthly Performance</relationshipLabel>
        <relationshipName>Monthly_Performance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User_Extension__c</referenceTo>
        <relationshipLabel>Monthly Performance</relationshipLabel>
        <relationshipName>Monthly_Performance</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Monthly Performance</label>
    <nameField>
        <label>Month</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Performance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Team_Structure__c.object
<CustomObject>
    <fields>
        <fullName>AVG_Call_Report_RM_Month__c</fullName>
        <defaultValue>0</defaultValue>
        <label>AVG Call Report / RM / Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Call Report</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Months__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_RM_under_Team__c</fullName>
        <label>Number of RM under Team</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Team Structure</label>
    <nameField>
        <label>Team Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Structure</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User_Extension__c.object
<CustomObject>
    <description>To store user&apos;s information.</description>
    <fields>
        <fullName>AVG_Call_Report_RM_Month__c</fullName>
        <formula>Team_Structure__r.AVG_Call_Report_RM_Month__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AVG Call Report/RM/Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Call Report</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Months__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_RM_under_Team__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of RM under Team</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Team_Structure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>User Extension</relationshipLabel>
        <relationshipName>User_Extension</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Extension</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Extension</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Extension</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SME_MonthlyReorder_Batch.cls
/**
 * @author komsan.wi@beryl8.com
 * @12/04/2016 create new
 */
global class SME_MonthlyReorder_Batch implements Database.Batchable<sObject>, Database.Stateful {
    private String query;
    private Map<String,Integer> countMonthlyByUser;
    private Map<String,Decimal> sumMonthlyDevideRMByTeam;
    //private List<Monthly_Performance__c> updateList;
    global SME_MonthlyReorder_Batch() {// AND Team__c=null
        this.query = 'select Id,User__c,Months__c,AVG_Call_Report_RM__c,Number_of_RM_under_Team__c,Call_Report__c,Team__c FROM Monthly_Performance__c WHERE Date__c = THIS_YEAR ORDER BY Date__c ASC';
        countMonthlyByUser = new Map<String,Integer>();
        sumMonthlyDevideRMByTeam = new Map<String,Decimal>();
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, list<Monthly_Performance__c> scope) {
        List<Monthly_Performance__c> updateList = new List<Monthly_Performance__c>();
        for(Monthly_Performance__c eachMonthly : scope){
            if(eachMonthly.User__c!=null){
                if(!countMonthlyByUser.containsKey(eachMonthly.User__c))
                    countMonthlyByUser.put(eachMonthly.User__c,0);
                if(eachMonthly.Months__c != countMonthlyByUser.get(eachMonthly.User__c)+1){
                    eachMonthly.Months__c = countMonthlyByUser.get(eachMonthly.User__c)+1;
                    updateList.add(eachMonthly);
                }
                countMonthlyByUser.put(eachMonthly.User__c,Integer.valueOf(eachMonthly.Months__c));
            }else if(eachMonthly.Team__c!=null){
                if(!sumMonthlyDevideRMByTeam.containsKey(eachMonthly.Team__c))
                    sumMonthlyDevideRMByTeam.put(eachMonthly.Team__c,0);

                if(eachMonthly.Number_of_RM_under_Team__c!=null && eachMonthly.Number_of_RM_under_Team__c!=0){
                    eachMonthly.AVG_Call_Report_RM__c = eachMonthly.Call_Report__c/eachMonthly.Number_of_RM_under_Team__c;
                    sumMonthlyDevideRMByTeam.put(eachMonthly.Team__c,sumMonthlyDevideRMByTeam.get(eachMonthly.Team__c) + eachMonthly.AVG_Call_Report_RM__c);
                    updateList.add(eachMonthly);
                }
            }
        }

        TriggerHandler.bypass('MonthlyPerformanceTriggerHandler');
        update updateList;
    }

    global void finish(Database.BatchableContext BC) {
        //List<User_Extension__c> userExtList = new List<User_Extension__c>();
        //Map<String,User_Extension__c> extMap = new Map<String,User_Extension__c>([SELECT Id,Team_Structure__c,Months__c,AVG_Call_Report_RM_Month__c FROM User_Extension__c]);

        Map<String,Team_Structure__c> teamMap = new Map<String,Team_Structure__c>([SELECT Id,Months__c,AVG_Call_Report_RM_Month__c FROM Team_Structure__c]);
        system.debug('rrt'+teamMap);
        for(Team_Structure__c teamObj : teamMap.values()){
            if(sumMonthlyDevideRMByTeam.containsKey(teamObj.Id) && teamObj.Months__c!=0)
                teamObj.AVG_Call_Report_RM_Month__c = sumMonthlyDevideRMByTeam.get(teamObj.Id)/teamObj.Months__c; 
        }
        
        //Database.executeBatch(new SME_DML_Batch(teamMap.values()),2000);
        update teamMap.values();

        //for(User_Extension__c eachUserExt : extMap.values()){
        //    //userExtList.add(new User_Extension__c(Id=userExtId,Months__c=countMonthlyByUser.get(userExtId)));
        //    eachUserExt.Months__c = countMonthlyByUser.get(eachUserExt.Id);
        //    //eachUserExt.AVG_Call_Report_RM_Month__c = teamMap.get(eachUserExt.Team_Structure__c).AVG_Call_Report_RM_Month__c;
        //}
        //for(String userExtId : countMonthlyByUser.keySet()){
        //    userExtList.add(new User_Extension__c(Id=userExtId,Months__c=countMonthlyByUser.get(userExtId)));
        //}
        //update userExtList;
    }
}