objects/Call_Report__c.object
<CustomObject>
    <description>This object tracks the Call Plan and Call Report</description>
    <fields>
        <fullName>CIS_ID__c</fullName>
        <label>CIS ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call Plans / Call Reports</relationshipLabel>
        <relationshipName>Call_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Call Plan / Call Report</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Call Plan / Call Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Plans / Call Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Contact_Override_Controller.cls
public with sharing class Contact_Override_Controller {
	public String callReportId{get;set;}
	public String cisId{get;set;}
	public Contact_Override_Controller(ApexPages.StandardController stdController) {
		callReportId = ApexPages.currentPage().getParameters().get('id');
		Call_Report__c callReportObj = [SELECT Id,CIS_ID__c FROM Call_Report__c WHERE Id=:callReportId];
		cisId = callReportObj.CIS_ID__c;
	}
    /*public PageReference redirect(){
    	Call_Report__c callReportObj = [SELECT Id,CIS_ID__c FROM Call_Report__c WHERE Id=:callReportId];
        PageReference pageRef = new PageReference('/003/e?accid='+callReportObj.CIS_ID__c);
        pageRef.getParameters().put('retURL', callReportId);
        pageRef.getParameters().put('saveURL', callReportId);
        pageRef.getParameters().put('cancelURL', callReportId);
        
        //pageRef.setRedirect(true);
        return pageRef;
    }
    public void redirectMobile() {
        Call_Report__c callReportObj = [SELECT Id,CIS_ID__c FROM Call_Report__c WHERE Id=:callReportId];
        cisId = callReportObj.CIS_ID__c;
    }*/
}