objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Lead_Campaign_Event_Code__c</fullName>
        <externalId>true</externalId>
        <label>Lead/Campaign/Event Code</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Campaign_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Campaign code setup using for Target List reward calculation</description>
    <fields>
        <fullName>NewBooking_Code__c</fullName>
        <label>NewBooking Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Campaign Setting</label>
</CustomObject>

objects/Target_List__c.object
<CustomObject>
    <description>This object tracks the list of Targeted Lead and Campaign Member list</description>
    <fields>
        <fullName>Lead_Campaign__c</fullName>
        <label>Lead/Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Target Lists</relationshipLabel>
        <relationshipName>Campaign_Members_Leads</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Mobile_No__c</fullName>
        <label>Mobile No.</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Option__c</fullName>
        <label>Reward New Booking Option</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Registered_DateTime__c</fullName>
        <label>Registered DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Reward__c</fullName>
        <label>Reward</label>
        <picklist>
            <picklistValues>
                <fullName>Cashback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>บัตรเติมน้ำมัน ปตท</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>บัตรเงินสด Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voucher ห้างทอง Aurora</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Done</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Interested This Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>App In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interested but not register</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stock Negotiation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Create Write Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Credit Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case is Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Credit Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial Loan Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Loan Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Target List</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ValueChain_Controller.cls
/**
* @author komsan.wi@beryl8.com
* @28/09/2015 created new
*/
public without sharing class ValueChain_Controller {
    public Target_List__c target {get;set;}
    public Boolean shouldReload {get;set;}
    public String optionType {get;set;}
    public String rewardType {get;set;}
    public Boolean isNewBooking {get;set;}
    private String[] targetIdArray;
    public static final Id campaignNewBookingID;

    static{
        String campaignNewBookingCode = Campaign_Setting__c.getOrgDefaults().NewBooking_Code__c;
        List<Campaign> campaignNewBooking = [SELECT Id FROM Campaign Where Lead_Campaign_Event_Code__c = :campaignNewBookingCode And IsActive = true];
        if(campaignNewBooking!=null && campaignNewBooking.Size() > 0){
            campaignNewBookingID = campaignNewBooking[0].Id;
        }
    }

    public ValueChain_Controller(ApexPages.StandardController stdController) {
        String valuelist = ApexPages.currentPage().getParameters().get('valuelist');
        String targetid = ApexPages.currentPage().getParameters().get('id');        
        shouldReload = false;
        //optionType = 'A';
        optionType = '';
        if(valuelist!=null){
            targetIdArray = valuelist.split(',');
        }else {
            targetIdArray = new String[]{targetid};
        }
        CheckNewBooking();
        target = new Target_List__c();
    }

    public ValueChain_Controller() {                
        String valuelist = ApexPages.currentPage().getParameters().get('valuelist');
        targetIdArray = valuelist.split(',');
        //optionType = 'A';
        optionType = '';
        shouldReload = false;
        CheckNewBooking();
        target = new Target_List__c();
    }

    private void CheckNewBooking(){
        List<Target_List__c> targetListNewBooking = [Select Id FROM Target_List__c WHERE Lead_Campaign__c = :campaignNewBookingID and Id in :targetIdArray];
        isNewBooking = (targetListNewBooking !=null && targetListNewBooking.size() > 0) ? true : false;
    }

    public void savingtarget(){
        shouldReload = true;
        List<Target_List__c> targetUpdateList = new List<Target_List__c>();
        for(Target_List__c tmpTarget : [Select Id,Lead_Campaign__c FROM Target_List__c WHERE Id IN : targetIdArray]){
            tmpTarget.Status__c = 'Registered';
            tmpTarget.Mobile_No__c = target.Mobile_No__c;
            tmpTarget.Registered_DateTime__c = System.Now(); // Add by Chumphon K., CR018 12-May-2016
            if(tmpTarget.Lead_Campaign__c == campaignNewBookingID){
                tmpTarget.Reward__c = rewardType;
                tmpTarget.Option__c = optionType;
            }
            targetUpdateList.add(tmpTarget);
        }
        try{
            System.debug('targetUpdateList='+targetUpdateList);
            update targetUpdateList;    
        }catch(Exception ex){
            shouldReload = false;
        }
    }

    public List<SelectOption> getOptionTypeItems() {        
        return getTypeItems(Target_List__c.Option__c.getDescribe(),false);
    }

    public List<SelectOption> getRewardTypeItems() {         
        return getTypeItems(Target_List__c.Reward__c.getDescribe(),true);
    }

    private List<SelectOption> getTypeItems(Schema.DescribeFieldResult fieldResult,boolean isCombobox) {
        List<SelectOption> options = new List<SelectOption>();        
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        if(isCombobox){
            options.add(new SelectOption('','Please Select'));   
        }
        for( Schema.PicklistEntry f : ple){
            options.add(new SelectOption(f.getValue(),f.getLabel()));
        }       
        return options;
    }
}