objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Contact_Phone_Number__c</fullName>
        <label>Contact Phone Number</label>
        <length>20</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <formula>Contact.Account.Name_Surname_TH__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Name</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <formula>Account.Name_Surname_TH__c</formula>
        <label>Customer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <inlineHelpText>Phone format must be in number with 9 or 10 digits</inlineHelpText>
        <label>Phone Number</label>
        <length>20</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Event_Target_List__c.object
<CustomObject>
    <description>This object tracks the list of Event Target Member in Event</description>
    <fields>
        <fullName>CIS_ID_Prospect_Name__c</fullName>
        <label>CIS ID/Prospect Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Event Target Lists</relationshipLabel>
        <relationshipName>Event_Target_Lists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <formula>CIS_ID_Prospect_Name__r.Name_Surname_TH__c</formula>
        <label>Customer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Event Name</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Event Target Lists</relationshipLabel>
        <relationshipName>Event_Target_Lists</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Event Target List</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Target Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CampaignMemberTriggerHandler.cls
public with sharing class CampaignMemberTriggerHandler extends TriggerHandler {
	public override void beforeInsert() {
		Set<Id> contactIds = new Set<Id>();
		Set<Id> campaignIds = new Set<Id>();
		for (CampaignMember campMember : (List<CampaignMember>) Trigger.new) {
			if(campMember.CampaignId!=null){
				contactIds.add(campMember.ContactId);
				campaignIds.add(campMember.CampaignId);
			}
		}

		// Map Campaign Member Contact Id by Customer Name 
		Map<Id, Id> mapMemberContactByAccId = new Map<Id, Id>();
		List<Id> accountIds = new List<Id>();
		Map<Id, Contact> mapContacts = new Map<Id, Contact>([SELECT Id, Customer_Name__c, AccountId, Phone_Number__c FROM Contact WHERE Id IN :contactIds]);
		for (Contact eachContact : mapContacts.values()) {
			accountIds.add(eachContact.AccountId);
			mapMemberContactByAccId.put(eachContact.Id, eachContact.AccountId);
		}

		Set<String> etsAccountAndCampaignString = new Set<String>();
		for (Event_Target_List__c ets : [SELECT Id,CIS_ID_Prospect_Name__c,Event_Name__c FROM Event_Target_List__c WHERE CIS_ID_Prospect_Name__c IN :accountIds AND Event_Name__c IN :campaignIds]) {
			if(ets.CIS_ID_Prospect_Name__c!=null && ets.Event_Name__c!=null) {
				etsAccountAndCampaignString.add(ets.CIS_ID_Prospect_Name__c+' '+ets.Event_Name__c);
			}
		}

		for (CampaignMember campMember : (List<CampaignMember>) Trigger.new) {
			if (!(campMember.ContactId!=null && campMember.CampaignId!=null && etsAccountAndCampaignString.contains(mapMemberContactByAccId.get(campMember.ContactId)+' '+campMember.CampaignId))) {
				campMember.addError(GlobalConstants.CANNOT_INSERT_CAMMEM);
			}
			if(campMember.ContactId != null && mapContacts.containsKey(campMember.ContactId)){
				campMember.Contact_Phone_Number__c = mapContacts.get(campMember.ContactId).Phone_Number__c;
			}
		}

	}
}