objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Lead For Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead To Do</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead To Inform</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Target_List__c.object
<CustomObject>
    <description>This object tracks the list of Targeted Lead and Campaign Member list</description>
    <fields>
        <fullName>CIS_ID_Prospect_Name__c</fullName>
        <label>CIS ID / Prospect Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Campaign_Members_Leads</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>In_Call_Plan__c</fullName>
        <defaultValue>false</defaultValue>
        <label>In Call Plan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead_Campaign__c</fullName>
        <label>Lead/Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Target Lists</relationshipLabel>
        <relationshipName>Campaign_Members_Leads</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Done</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Interested This Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>App In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interested but not register</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stock Negotiation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Create Write Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Credit Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case is Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Credit Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial Loan Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Loan Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Target List</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CampaignChangeStatus_Batch.cls
global class CampaignChangeStatus_Batch implements Database.Batchable<sObject>, Database.Stateful {
	
	global Set<Id> setCampaignIds;
	//global Set<Id> allAccountIds;
	String query;
	
	global CampaignChangeStatus_Batch(Set<Id> setCampaignIds) {
		//allAccountIds = new Set<Id>();
		if(this.setCampaignIds == null) {
			this.setCampaignIds = new Set<Id>();
		}
		this.setCampaignIds.addAll(setCampaignIds);
		List<Id> campaignIds = new List<Id>(setCampaignIds);
		this.query = 'SELECT CIS_ID_Prospect_Name__c, Lead_Campaign__r.Status, Lead_Campaign__r.Type__c FROM Target_List__c WHERE In_Call_Plan__c = false AND Lead_Campaign__c IN (\'' + String.join(campaignIds,'\',\'') + '\') AND (Lead_Campaign__r.Status = \'' + GlobalConstants.CANCEL_PROCESS + '\' OR Lead_Campaign__r.Status = \'' + GlobalConstants.EXPIRE_PROCESS + '\') AND Status__c = \'' + GlobalConstants.STATUS_NEW + '\' ORDER BY CIS_ID_Prospect_Name__c';
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<Target_List__c> targetList) {
		List<Target_List__c> updateTargetList = new List<Target_List__c>();
		Map<Id, List<Target_List__c>> mapTargetsByAccount = new Map<Id, List<Target_List__c>>();

		for (Target_List__c target : targetList) {
            if(target.Lead_Campaign__r.Status == GlobalConstants.CANCEL_PROCESS) {
                if (target.Lead_Campaign__r.Type__c != null) {
                    if (target.Lead_Campaign__r.Type__c == GlobalConstants.CAMPAIGN) {
                        target.Status__c = GlobalConstants.CANCEL_CAMPAIGN;
                    } else {
                        target.Status__c = GlobalConstants.CANCEL_LEAD;
                    }
                }
            } else if(target.Lead_Campaign__r.Status == GlobalConstants.EXPIRE_PROCESS) {
                target.Status__c = GlobalConstants.LEAD_EXPIRED;    
            } else {
            	continue;
            }

            updateTargetList.add(target);
            //allAccountIds.add(target.CIS_ID_Prospect_Name__c);
        }
        if (!updateTargetList.isEmpty()) {
        	TriggerHandler.bypass('TargetListTriggerHandler');
            update updateTargetList;
        }
	}
	
	global void finish(Database.BatchableContext BC) {
		List<Campaign> updateCampaigns = new List<Campaign>();
		List<Campaign> newCampaigns = new List<Campaign>();
		newCampaigns = [SELECT Id, Status FROM Campaign WHERE Id IN :setCampaignIds];
		for (Campaign eachCamp : newCampaigns) {
			if(eachCamp.Status == GlobalConstants.CANCEL_PROCESS) {
				eachCamp.Status = GlobalConstants.CANCEL;
			} else if (eachCamp.Status == GlobalConstants.EXPIRE_PROCESS) {
				eachCamp.Status = GlobalConstants.EXPIRED;
			} else {
				continue;
			}

			updateCampaigns.add(eachCamp);
		}
		if (!updateCampaigns.isEmpty()) update updateCampaigns;

		//Database.executeBatch(new AccountLeadUpdate_Batch(allAccountIds), 2000);
	}
	
}