objects/ConnectionAttribute__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>AttributeValue__c</fullName>
        <label>AttributeValue</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>ConnectionAttribute</label>
</CustomObject>

objects/Kbank_Endpoint__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Endpoint__c</fullName>
        <label>Endpoint</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Kbank Endpoint</label>
</CustomObject>

objects/System_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Log_Purge_Days__c</fullName>
        <description>The number of days of logs to keep</description>
        <label>Log Purge (Days)</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Search_Results__c</fullName>
        <defaultValue>30</defaultValue>
        <description>Custom Search Results</description>
        <label>Search Results (Number)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>System Settings</label>
</CustomObject>

classes/CustomSettingUtil.cls
/*------------------------------------------------------------
Author: Charnun Thaweethamwitthaya
Company : Beryl8
Description:

History : 
<Date>      <Authors Name>     <Brief Description of Change> 
07/27/2015  Charnun.T       First Create
------------------------------------------------------------*/
public class CustomSettingUtil {

	public static Map<String,String> endPointMap;
	public static Map<String,String> connAttributeMap;
	public static final String TIMEOUT_KEY = 'CITimeout';
	public static final String HTTP_USERNAME_KEY = 'httpUsername';
	public static final String HTTP_PASSWORD_KEY = 'httpPassword';

	public static void readEndpointCustomSettingMap() {
		Map<String,Kbank_Endpoint__c> customSettingMap = Kbank_Endpoint__c.getAll();
		endPointMap = new Map<String,String>();
		System.debug('customSettingMap:'+customSettingMap);
        for (Kbank_Endpoint__c eachEndpoint : customSettingMap.values()) {
       		endPointMap.put(eachEndpoint.Name__c,eachEndpoint.Endpoint__c);
        }
	}

	public static String getEndpointByName(String endPointName) {
		if (endPointMap == null){
			readEndpointCustomSettingMap();
		}
		return endPointMap.get(endPointName);
	}

	public static String getConnectionAttributeByName(String attrKey) {
		if (connAttributeMap == null){
			readConnectionAttributeValue();
		} 
		return connAttributeMap.get(attrKey);
	}


	public static Integer getTimeout() {
		Integer timeout = 5000;
		try{
			System.debug('ConnAttributeMap:'+connAttributeMap);
			timeout = Integer.valueOf(getConnectionAttributeByName(TIMEOUT_KEY));
		} catch(Exception e){
			System.debug(e.getStackTraceString());
		}

		return timeout;
	}

	public static String getHttpUsername() {
		return getConnectionAttributeByName(HTTP_USERNAME_KEY);
	}

	public static String getHttpPassword() {
		return getConnectionAttributeByName(HTTP_PASSWORD_KEY);
	}

	public static void readConnectionAttributeValue() {
		Map<String,ConnectionAttribute__c> customSettingMap = ConnectionAttribute__c.getAll();
		connAttributeMap = new Map<String,String>();
        for (ConnectionAttribute__c eachAttr : customSettingMap.values()) {
       		connAttributeMap.put(eachAttr.Name__c,eachAttr.AttributeValue__c);
		}
		System.debug(connAttributeMap);
	}

	public static String getPurgeTime() {
		return getCustomSettingPurgeDays();
	}

	public static String getCustomSettingPurgeDays() {
		String purgeDays = '30';
		System_Settings__c systemSetting = System_Settings__c.getInstance();
		if(systemSetting.Log_Purge_Days__c != null && systemSetting.Log_Purge_Days__c != 0){
			purgeDays = String.valueOf(Integer.valueOf(systemSetting.Log_Purge_Days__c));
		}

		return purgeDays;
	}

	public static Integer getSearchResults() {
		return getCustomSettingNumberOfSearchResults();
	}

	public static Integer getCustomSettingNumberOfSearchResults() {
		Integer numberOfSearchResults = 30;
		System_Settings__c systemSetting = System_Settings__c.getInstance();
		if(systemSetting.Search_Results__c != null && systemSetting.Search_Results__c != 0){
			numberOfSearchResults = Integer.valueOf(systemSetting.Search_Results__c);
		}

		return numberOfSearchResults;
	}
}