objects/Job_Code__c.object
<CustomObject>
    <description>This object tracks the Job Code of User</description>
    <label>Job Code</label>
    <nameField>
        <label>Job Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>AH_RC_Code__c</fullName>
        <label>AH RC Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Acting_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Acting Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Employee ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Job_Code__c</fullName>
        <label>Job Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NH_RC_Code__c</fullName>
        <label>NH RC Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RC_Code__c</fullName>
        <label>RC Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is updated by DIH (HRIS): A = Active, I=Inactive</description>
        <label>Status Code</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team_Name__c</fullName>
        <label>Team Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/User_Structure__c.object
<CustomObject>
    <description>This object serves as a staging object to store all the sales user from HRIS.</description>
    <fields>
        <fullName>AH_RC_Code__c</fullName>
        <label>AH RC Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Code__c</fullName>
        <label>Job Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NH_RC_Code__c</fullName>
        <label>NH RC Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RC_Code__c</fullName>
        <label>RC Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status Code</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team_Name__c</fullName>
        <label>Team Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>User Structure</label>
    <nameField>
        <label>Employee ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Structure</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/SME_PrepareOwnershipAssignment_Batch.cls
global class SME_PrepareOwnershipAssignment_Batch extends ApplicationLog_Service implements Database.Batchable<sObject>, Database.Stateful {
    
    private static final String CLASS_NAME = 'SME_PrepareOwnershipAssignment_Batch';
    private Set<Id> hrisDiffIds;
    private Set<Id> hrisInActiveIds;
    private Map<String, User> userMapByEmpId;
    private Map<String, User> userMapByNewRoleRC;
    private Map<String, User_MaskModel> userMaskMapByEmpId;

    String query;
    
    global SME_PrepareOwnershipAssignment_Batch() {
        initialBatch();
    }

    private void initialBatch() {
        userMapByEmpId = new Map<String, User>();

        for(User eachUser : [SELECT Id, Name, IsActive, Acting_Flag__c, Employee_ID__c, RC_Code__c, AH_RC_Code__c, NH_RC_Code__c, Job_Code__c, UserRole.DeveloperName, Profile.Name, Email, Username, FirstName, LastName, Segment__c, Status__c, Effective_Date__c, Team_Name__c,
                            ManagerId,
                            Manager.ManagerId,
                            Manager.Manager.ManagerId,
                            Manager.IsActive, 
                            Manager.Manager.IsActive, 
                            Manager.Manager.Manager.IsActive,
                            Manager.RC_Code__c, 
                            Manager.Manager.RC_Code__c, 
                            Manager.Manager.Manager.RC_Code__c,
                            Manager.Job_Code__c, 
                            Manager.Manager.Job_Code__c, 
                            Manager.Manager.Manager.Job_Code__c  FROM User]) {
            if (eachUser.Employee_ID__c != null) {
                userMapByEmpId.put(formatEmployeeId(eachUser.Employee_ID__c), eachUser);
            }
        }

        this.query = 'SELECT Id, Name, Team_Name__c, Email__c, First_Name__c, Last_Name__c, Segment__c, RC_Code__c, Job_Code__c, Status__c, AH_RC_Code__c, NH_RC_Code__c, Effective_Date__c, Username__c FROM User_Structure__c';
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<User_Structure__c> scope) {
        hrisDiffIds = new Set<Id>();
        hrisInActiveIds = new Set<Id>();
        userMapByNewRoleRC = new Map<String, User>();
        userMaskMapByEmpId = new Map<String, User_MaskModel>();
        for (User_Structure__c eachHRISUser : scope) {
            if (userMapByEmpId.containsKey(formatEmployeeId(eachHRISUser.Name))) {
                User eachUser = userMapByEmpId.get(formatEmployeeId(eachHRISUser.Name));
                
                // Check acting flag
                if (eachUser.Acting_Flag__c == true && 
                    eachHRISUser.Job_Code__c != null && eachUser.RC_Code__c != null && (eachUser.Job_Code__c != eachHRISUser.Job_Code__c || eachUser.RC_Code__c != eachHRISUser.RC_Code__c)) {
                    continue;
                }

                User_MaskModel userMask = new User_MaskModel(eachUser);
                userMask.setUserStructure(eachHRISUser);

                if(eachHRISUser.Status__c == 'I' && (eachUser.Status__c != eachHRISUser.Status__c || eachUser.IsActive)) {
                    hrisInActiveIds.add(eachUser.Id);
                    userMaskMapByEmpId.put(eachUser.Employee_ID__c,userMask);
                } else if (eachUser.Job_Code__c != eachHRISUser.Job_Code__c || eachUser.RC_Code__c != eachHRISUser.RC_Code__c) {
                    hrisDiffIds.add(eachUser.Id);
                    userMapByNewRoleRC.put(eachHRISUser.Job_Code__c + '-' + eachHRISUser.RC_Code__c, eachUser);
                    userMaskMapByEmpId.put(eachUser.Employee_ID__c,userMask);
                }
            }
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        Database.executeBatch(new UserStructureUpdateUser_Batch(userMaskMapByEmpId, userMapByNewRoleRC, hrisDiffIds, hrisInActiveIds));
    }

    private String formatEmployeeId(String employeeId) {
        employeeId = '00000' + employeeId;
        return employeeId.substring(employeeId.length() - 6, employeeId.length());
    }
    
}