objects/Monthly_Performance__c.object
<CustomObject>
    <description>To store user and team&apos;s monthly performance.</description>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Monthly Performance</label>
    <nameField>
        <label>Month</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Performance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SME_Monthly_DML_Batch.cls
global class SME_Monthly_DML_Batch implements Database.Batchable<Monthly_Performance__c> ,Database.Stateful{
    private List<Monthly_Performance__c> dmlList;
    global SME_Monthly_DML_Batch(List<Monthly_Performance__c> dmlList) {
    	this.dmlList = dmlList;
    }
    global List<Monthly_Performance__c> start(Database.BatchableContext bc) {
    	return dmlList;
    }
    
    global void execute(Database.BatchableContext BC, list<Monthly_Performance__c> partialList) {
    	upsert partialList External_ID__c;
    }

    global void finish(Database.BatchableContext BC) {
    	Database.executeBatch(new SME_MonthlyReorder_Batch());
    }
}