objects/Monthly_Performance__c.object
<CustomObject>
    <description>To store user and team&apos;s monthly performance.</description>
    <fields>
        <fullName>Call_Report_Customer_Others__c</fullName>
        <label># Call Report Customer Others</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report_Customer_Pool__c</fullName>
        <label># Call Report Customer Pool</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report_Customer_Port__c</fullName>
        <label># Call Report Customer Port</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report__c</fullName>
        <label># Call Report</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report_for_Relationship__c</fullName>
        <label># Call Report for Relationship</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report_for_Sales__c</fullName>
        <label># Call Report for Sales</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contacted_Customer_Other_My_Penetrate__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Contacted Customer Other(My Penetrate)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contacted_Customer_Pool_My_Penetrate__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Contacted Customer Pool(My Penetrate)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contacted_Customer_Port_My_Penetrate__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Contacted Customer Port(My Penetrate)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Face_to_Face__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Face to Face</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Months__c</fullName>
        <label># Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_RM_under_Team__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of RM under Team</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phone_Call__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Phone Call</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Monthly Performance</relationshipLabel>
        <relationshipName>Monthly_Performance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User_Extension__c</referenceTo>
        <relationshipLabel>Monthly Performance</relationshipLabel>
        <relationshipName>Monthly_Performance</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Monthly Performance</label>
    <nameField>
        <label>Month</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Performance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Team_Structure__c.object
<CustomObject>
    <fields>
        <fullName>AH_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AH Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Team Structure</relationshipLabel>
        <relationshipName>Team_Structure</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AH_RC_Code__c</fullName>
        <label>AH RC Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Call_Report_Customer_Others__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Call Report Customer Others</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report_Customer_Pool__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Call Report Customer Pool</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report_Customer_Port__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Call Report Customer Port</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Call Report</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report_for_Relationship__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Call Report for Relationship</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report_for_Sales__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Call Report for Sales</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contacted_Customer_Other_My_Penetrate__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Contacted Customer Other(My Penetrate)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contacted_Customer_Pool_My_Penetrate__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Contacted Customer Pool(My Penetrate)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contacted_Customer_Port_My_Penetrate__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Contacted Customer Port(My Penetrate)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Face_to_Face__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Face to Face</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Months__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NH_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NH Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Team Structure (NH Name)</relationshipLabel>
        <relationshipName>Team_Structure1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NH_RC_Code__c</fullName>
        <label>NH RC Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_RM_under_Team__c</fullName>
        <label>Number of RM under Team</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phone_Call__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Phone Call</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RC_Code__c</fullName>
        <label>RC Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Team Structure</label>
    <nameField>
        <label>Team Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Structure</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>AH_Name__c</fullName>
        <label>AH Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AH_RC_Code__c</fullName>
        <label>AH RC Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Employee ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NH_Name__c</fullName>
        <label>NH Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NH_RC_Code__c</fullName>
        <label>NH RC Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RC_Code__c</fullName>
        <label>RC Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/User_Extension__c.object
<CustomObject>
    <description>To store user&apos;s information.</description>
    <fields>
        <fullName>Call_Report_Customer_Others__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Call Report Customer Others</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report_Customer_Pool__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Call Report Customer Pool</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report_Customer_Port__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Call Report Customer Port</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Call Report</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report_for_Relationship__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Call Report for Relationship</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Report_for_Sales__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Call Report for Sales</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contacted_Customer_Other_My_Penetrate__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Contacted Customer Other(My Penetrate)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contacted_Customer_Pool_My_Penetrate__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Contacted Customer Pool(My Penetrate)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <formula>User__r.Employee_ID__c</formula>
        <label>Employee ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Face_to_Face__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Face to Face</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_Month_Stamp__c</fullName>
        <label>Last Month Stamp</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Months__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_RM_under_Team__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of RM under Team</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phone_Call__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Phone Call</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Team_Structure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>User Extension</relationshipLabel>
        <relationshipName>User_Extension</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Extension</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Extension</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Extension</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SME_Monthly_Initial_Batch.cls
global class SME_Monthly_Initial_Batch implements Database.Batchable<sObject> ,Database.Stateful{
    public String query;
    private Map<String,Team_Structure__c> teamMap;
    private List<String> monthList = new List<String>{
        'มกราคม',
        'กุมภาพันธ์',
        'มีนาคม',
        'เมษายน',
        'พฤษภาคม',
        'มิถุนายน',
        'กรกฎาคม',
        'สิงหาคม',
        'กันยายน',
        'ตุลาคม',
        'พฤศจิกายน',
        'ธันวาคม'
    };
    private Date todayDateFromNow;
    private Integer currentYear;
    global SME_Monthly_Initial_Batch() {
	    this.query = 'SELECT Id,Call_Report__c,Call_Report_Customer_Others__c,Call_Report_Customer_Pool__c,Call_Report_Customer_Port__c,Call_Report_for_Relationship__c,Call_Report_for_Sales__c,Face_to_Face__c,Months__c,Phone_Call__c,Team_Structure__c,User__r.ProfileId,User__r.Profile.Name,User__r.Employee_Id__c,User__r.RC_Code__c,Number_of_RM_under_Team__c,Last_Month_Stamp__c,User__r.IsActive FROM User_Extension__c WHERE Team_Structure__c!=null and User__r.IsActive = true';
	    teamMap = new Map<String,Team_Structure__c>([SELECT Id,Call_Report__c,Call_Report_Customer_Others__c,Call_Report_Customer_Pool__c,Call_Report_Customer_Port__c,Call_Report_for_Relationship__c,Call_Report_for_Sales__c,Face_to_Face__c,Months__c,Phone_Call__c,Name,AH_Name__c,NH_Name__c,RC_Code__c,Number_of_RM_under_Team__c,AH_RC_Code__c,NH_RC_Code__c FROM Team_Structure__c]);
	    DateTime dT = System.now();
        todayDateFromNow = date.newinstance(dT.year(), dT.month()-1, dT.day());
        currentYear = (todayDateFromNow.year()<2500)?todayDateFromNow.year()+543:todayDateFromNow.year();
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
    return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, list<User_Extension__c> userExList) {
    	Map<String,User_Extension__c> userExMap = new Map<String,User_Extension__c>(userExList);

        Map<String,Monthly_Performance__c> monthlyMap = new Map<String,Monthly_Performance__c>();
            
        String exKey;
        String teamKey;
        Integer numberOfDays;
        for(User_Extension__c eachExt : userExMap.values()){
            for(Integer i = 1;i<System.now().month();i++){
                exKey = eachExt.User__r.Employee_Id__c + ' ' + i + ' ' + currentYear;
                teamKey = eachExt.User__r.RC_Code__c + ' ' + i + ' ' + currentYear;
                numberOfDays = Date.daysInMonth(todayDateFromNow.year(), i);
                if(!monthlyMap.containsKey(exKey)){
                    monthlyMap.put(exKey,new Monthly_Performance__c(
                        External_ID__c = exKey,
                        Name = monthList.get(i-1) +' '+currentYear,
                        User__c = eachExt.Id,
                        //Team__c = eachExt.Team_Structure__c,
                        Call_Report__c = 0,
                        Call_Report_Customer_Port__c = 0,
                        Call_Report_Customer_Pool__c = 0,
                        Call_Report_Customer_Others__c = 0,
                        Call_Report_for_Sales__c = 0,
                        Call_Report_for_Relationship__c = 0,
                        Face_to_Face__c = 0,
                        Phone_Call__c = 0,
                        Contacted_Customer_Other_My_Penetrate__c = 0,
                        Contacted_Customer_Pool_My_Penetrate__c = 0,
                        Contacted_Customer_Port_My_Penetrate__c = 0,
                        //Total_Call_Report__c = 0,
                        //Total_Face_to_Face_Call__c = 0,
                        //Total_Sales_Relationship__c = 0,
                        Date__c = Date.newInstance(todayDateFromNow.year(), i, numberOfDays),
                        Months__c = i
                    ));
                }
                if(!monthlyMap.containsKey(teamKey)){
                    monthlyMap.put(teamKey,new Monthly_Performance__c(
                        External_ID__c = teamKey,
                        Name = monthList.get(i-1) +' '+currentYear,
                        //User__c = eachExt.Id,
                        Team__c = eachExt.Team_Structure__c,
                        Call_Report__c = 0,
                        Call_Report_Customer_Port__c = 0,
                        Call_Report_Customer_Pool__c = 0,
                        Call_Report_Customer_Others__c = 0,
                        Call_Report_for_Sales__c = 0,
                        Call_Report_for_Relationship__c = 0,
                        Face_to_Face__c = 0,
                        Phone_Call__c = 0,
                        Contacted_Customer_Other_My_Penetrate__c = 0,
                        Contacted_Customer_Pool_My_Penetrate__c = 0,
                        Contacted_Customer_Port_My_Penetrate__c = 0,
                        //Total_Call_Report__c = 0,
                        //Total_Face_to_Face_Call__c = 0,
                        //Total_Sales_Relationship__c = 0,
                        Date__c = Date.newInstance(todayDateFromNow.year(), i, numberOfDays),
                        Months__c = i
                    ));
                }
            }
        }
        GlobalUtility.initialMonthly = true;
        upsert monthlyMap.values() External_ID__c;
    }

    global void finish(Database.BatchableContext BC) {
    	GlobalUtility.initialMonthly = false;
    	Database.executeBatch(new SME_Performance_Batch(1).runMontly(true).runSummaryAtTheEnd().noFlag());
    }
}