objects/SME_Admin__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>To store the SME Admin proflle and UserID used as a default &quot;no ownership&apos; customer owner</description>
    <fields>
        <fullName>User_Record_ID__c</fullName>
        <label>User Record ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>SME Admin</label>
</CustomObject>

objects/Team_Structure__c.object
<CustomObject>
    <fields>
        <fullName>AH_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AH Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Team Structure</relationshipLabel>
        <relationshipName>Team_Structure</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NH_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NH Name</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>Team Structure (NH Name)</relationshipLabel>
        <relationshipName>Team_Structure1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RC_Code__c</fullName>
        <label>RC Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Team Structure</label>
    <nameField>
        <label>Team Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Structure</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>AH_Name__c</fullName>
        <label>AH Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NH_Name__c</fullName>
        <label>NH Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RC_Code__c</fullName>
        <label>RC Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/SME_TeamStructureInitial_Batch.cls
global class SME_TeamStructureInitial_Batch implements Database.Batchable<sObject> {
	
	String query;
	
	global SME_TeamStructureInitial_Batch() {
		query = 'SELECT Id, RC_Code__c, AH_Name__c, AH_Name__r.OwnerId, NH_Name__c, NH_Name__r.OwnerId FROM Team_Structure__c';
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<Team_Structure__c> scope) {
   		SME_Admin__c smeAdmin = SME_Admin__c.getOrgDefaults();

   		if(TeamStructure_Service.userMapByRCCode == null)
   			TeamStructure_Service.userMapByRCCode = TeamStructure_Service.getUserMapByRCCode();

   		User eachUser;
		for(Team_Structure__c eachTeam : scope) {
			if(TeamStructure_Service.userMapByRCCode.containsKey(eachTeam.RC_Code__c)) {
				eachUser = TeamStructure_Service.userMapByRCCode.get(eachTeam.RC_Code__c);
				if(eachUser.IsActive)
					eachTeam.OwnerId = eachUser.Id;
				else if(eachUser.Manager != null && eachUser.Manager.IsActive)
		            eachTeam.OwnerId = eachUser.ManagerId;
		        else if(eachUser.Manager.Manager != null && eachUser.Manager.Manager.IsActive)
		            eachTeam.OwnerId = eachUser.Manager.ManagerId;
			} else if(eachTeam.AH_Name__c != null)
				eachTeam.OwnerId = eachTeam.AH_Name__r.OwnerId;
			else if(eachTeam.NH_Name__c != null)
				eachTeam.OwnerId = eachTeam.NH_Name__r.OwnerId;
			else
				eachTeam.OwnerId = smeAdmin.User_Record_ID__c;
		}
		update scope;
	}
	
	global void finish(Database.BatchableContext BC) {}
	
}