objects/SME_Admin__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>To store the SME Admin proflle and UserID used as a default &quot;no ownership&apos; customer owner</description>
    <fields>
        <fullName>User_Record_ID__c</fullName>
        <label>User Record ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>SME Admin</label>
</CustomObject>

objects/User_Extension__c.object
<CustomObject>
    <description>To store user&apos;s information.</description>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Extension</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Extension</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Extension</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SME_UserExtensionOwnerInitial_Batch.cls
global class SME_UserExtensionOwnerInitial_Batch implements Database.Batchable<sObject> {
	
	private String query;

	global SME_UserExtensionOwnerInitial_Batch() {
		this.query = 'SELECT Id, User__c, User__r.IsActive, User__r.ManagerId, User__r.Manager.ManagerId, User__r.Manager.Manager.ManagerId, User__r.Manager.IsActive, User__r.Manager.Manager.IsActive, User__r.Manager.Manager.Manager.IsActive FROM User_Extension__c';
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<User_Extension__c> userExtList) {
   		SME_Admin__c smeAdmin = SME_Admin__c.getOrgDefaults();

   		List<User_Extension__c> userExtInitialList = new List<User_Extension__c>();

		for(User_Extension__c eachUserExt : userExtList) {
			if(eachUserExt.User__c != null) {
				if(eachUserExt.User__r.IsActive)
					eachUserExt.OwnerId = eachUserExt.User__c;
				else if(eachUserExt.User__r.Manager != null && eachUserExt.User__r.Manager.IsActive)
		            eachUserExt.OwnerId = eachUserExt.User__r.ManagerId;
		        else if(eachUserExt.User__r.Manager.Manager != null && eachUserExt.User__r.Manager.Manager.IsActive)
		            eachUserExt.OwnerId = eachUserExt.User__r.Manager.ManagerId;
		        else if(eachUserExt.User__r.Manager.Manager.Manager != null && eachUserExt.User__r.Manager.Manager.Manager.IsActive)
		            eachUserExt.OwnerId = eachUserExt.User__r.Manager.Manager.ManagerId;
		        else
		        	eachUserExt.OwnerId = smeAdmin.User_Record_ID__c;
				userExtInitialList.add(eachUserExt);
			}
		}

		if(!userExtInitialList.isEmpty()) {
			TriggerHandler.bypass('UserExtensionTriggerHandler');
			update userExtInitialList;
		}
	}
	
	global void finish(Database.BatchableContext BC) {}
	
}