objects/SME_Admin__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>To store the SME Admin proflle and UserID used as a default &quot;no ownership&apos; customer owner</description>
    <fields>
        <fullName>User_Record_ID__c</fullName>
        <label>User Record ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>SME Admin</label>
</CustomObject>

objects/Team_Structure__c.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RC_Code__c</fullName>
        <label>RC Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Team Structure</label>
    <nameField>
        <label>Team Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Structure</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Employee ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RC_Code__c</fullName>
        <label>RC Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/User_Extension__c.object
<CustomObject>
    <description>To store user&apos;s information.</description>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <formula>User__r.Employee_ID__c</formula>
        <label>Employee ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Team_Structure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>Team_Structure__c</referenceTo>
        <relationshipLabel>User Extension</relationshipLabel>
        <relationshipName>User_Extension</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Extension</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Extension</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Extension</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SME_UserExtensionInitial_Batch.cls
global class SME_UserExtensionInitial_Batch implements Database.Batchable<sObject>, Database.Stateful {
	
	private String query;
	private Map<String, Team_Structure__c> teamMapByRc;
	private List<User_Extension__c> userExtList;

	global SME_UserExtensionInitial_Batch() {
		// Delete old extension
		if(userExtList == null) {
			userExtList = new List<User_Extension__c>();
			userExtList = [SELECT Id FROM User_Extension__c];
		}
		
		this.query = 'SELECT Id, Name, Employee_ID__c, RC_Code__c, IsActive, ManagerId, Manager.ManagerId, Manager.Manager.ManagerId, Manager.IsActive, Manager.Manager.IsActive, Manager.Manager.Manager.IsActive FROM User';
 		if(Test.isRunningTest()) this.query += ' LIMIT 100';

		teamMapByRc = new Map<String, Team_Structure__c>();
		List<Team_Structure__c> teamList = [SELECT Id, External_ID__c FROM Team_Structure__c];
		for(Team_Structure__c eachTeam : teamList) {
			teamMapByRc.put(eachTeam.External_ID__c, eachTeam);
		}
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<User> userList) {
   		SME_Admin__c smeAdmin = SME_Admin__c.getOrgDefaults();

   		if(userExtList != null && !userExtList.isEmpty()) {
   			delete userExtList;
   			userExtList.clear();
   		}

   		List<User_Extension__c> userExtInitialList = new List<User_Extension__c>();

   		User_Extension__c eachUserExt;
		for(User eachUser : userList) {
			if(eachUser.Employee_ID__c != null) {
				eachUserExt = new User_Extension__c();
				
				if(eachUser.IsActive)
					eachUserExt.OwnerId = eachUser.Id;
				else if(eachUser.Manager != null && eachUser.Manager.IsActive)
		            eachUserExt.OwnerId = eachUser.ManagerId;
		        else if(eachUser.Manager.Manager != null && eachUser.Manager.Manager.IsActive)
		            eachUserExt.OwnerId = eachUser.Manager.ManagerId;
		        else if(eachUser.Manager.Manager.Manager != null && eachUser.Manager.Manager.Manager.IsActive)
		            eachUserExt.OwnerId = eachUser.Manager.Manager.ManagerId;
		        else
		        	eachUserExt.OwnerId = smeAdmin.User_Record_ID__c;

				eachUserExt.Name = eachUser.Name;
				eachUserExt.User__c = eachUser.Id;
				eachUserExt.External_ID__c = eachUser.Employee_ID__c;
				if(eachUser.RC_Code__c != null && teamMapByRc.containsKey(eachUser.RC_Code__c)) {
					eachUserExt.Team_Structure__c = teamMapByRc.get(eachUser.RC_Code__c).Id;
				}
				userExtInitialList.add(eachUserExt);
			}
		}

		if(!userExtInitialList.isEmpty()) {
			insert userExtInitialList;
		}
	}
	
	global void finish(Database.BatchableContext BC) {}
	
}