objects/User.object
<CustomObject>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Employee ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/User_Extension__c.object
<CustomObject>
    <description>To store user&apos;s information.</description>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <formula>User__r.Employee_ID__c</formula>
        <label>Employee ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>User Extension</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Extension</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SME_UserExtensionOwnerInitial_Test.cls
@isTest
private class SME_UserExtensionOwnerInitial_Test {
	
	@testSetup static void setupTest(){
		Mockup_Test mt = new Mockup_Test().setUpTest();
	}
	
	@isTest	static void testInitial(){
		Test.startTest();
			Database.executeBatch(new SME_UserExtensionOwnerInitial_Batch());
		Test.stopTest();
				
		User_Extension__c targetRMUser = [SELECT Id, OwnerId FROM User_Extension__c WHERE External_ID__c=:Mockup_Test.userEmpIdRM LIMIT 1];
		User_Extension__c targetTMUser = [SELECT Id, OwnerId FROM User_Extension__c WHERE External_ID__c=:Mockup_Test.userEmpIdTM LIMIT 1];

		User targetOwnerRM = [SELECT Id FROM User WHERE Employee_Id__c = :Mockup_Test.userEmpIdRM];
		User targetOwnerTM = [SELECT Id FROM User WHERE Employee_Id__c = :Mockup_Test.userEmpIdTM];

		System.assertEquals(targetOwnerRM.Id,targetRMUser.OwnerId);
		System.assertEquals(targetOwnerTM.Id,targetTMUser.OwnerId);
	}
}