objects/User_Extension__c.object
<CustomObject>
    <description>To store user&apos;s information.</description>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Extension</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Extension</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Extension</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Account_Util.cls
/**
* @author komsan.wi@beryl8.com
* @14/07/2015 createddate
*/
public class Account_Util {
    public static Boolean isProfile(String profileName,User user){
        return user.ProfileId!=null && user.Profile.Name==profileName;
    }
    public static Boolean isProfile(String profileName,User_Extension__c user){
        return user.User__r.ProfileId!=null && user.User__r.Profile.Name==profileName;
    }
}