objects/User.object
<CustomObject>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Employee ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Year_End_Assignment__c.object
<CustomObject>
    <description>This object tracks the re-assignment of customer to RM port / TM port or Pool, Refer out at the end of the year</description>
    <fields>
        <fullName>Owner_Employee_ID__c</fullName>
        <label>Owner Employee ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Year-End Assignment</label>
    <nameField>
        <displayFormat>Ref-{00000}</displayFormat>
        <label>REF#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Year-End Assignment</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/YearEndAssignmentTriggerHandler.cls
/**
 * @author chutiwat.s@beryl8.com
 * @15/09/2015 created date
 */
public class YearEndAssignmentTriggerHandler extends TriggerHandler {
	public override void beforeInsert() {
   		//Owner = Query ID from User where Employee_ID__c = Owner_Employee_ID__c
		List<String> userEmpId = new List<String>();
        Map<String, Id> userMapByEmpId = new Map<String, Id>();

        for(Year_End_Assignment__c eachYearEnd : (List<Year_End_Assignment__c>) Trigger.new){
            if(eachYearEnd.Owner_Employee_ID__c!=null) userEmpId.add(eachYearEnd.Owner_Employee_ID__c);
        }
        List<User> userList = new List<User>();
        userList = [SELECT Id, Employee_ID__c FROM User WHERE Employee_ID__c IN :userEmpId];
        if (userList!=null && userList.size() > 0) {
            for (User eachUser : userList) {
        	   userMapByEmpId.put(eachUser.Employee_ID__c, eachUser.Id);
            }
        }

        if (userMapByEmpId.size() > 0) {
            for (Year_End_Assignment__c eachYearEndAssignment : (List<Year_End_Assignment__c>) Trigger.new) {
            	if (eachYearEndAssignment.Owner_Employee_ID__c!=null && userMapByEmpId!=null && userMapByEmpId.containsKey(eachYearEndAssignment.Owner_Employee_ID__c)) {
            		eachYearEndAssignment.OwnerId = userMapByEmpId.get(eachYearEndAssignment.Owner_Employee_ID__c);
            	}
            }
        }
   		
	}
}